### PR TITLE
LPS-121804 PythonImportsCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

I use https://github.com/liferay/com-liferay-osb-asah-private to test my logic.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/5194

**Pull request closed without merging**
