### PR TITLE
LPS-73560 set java.awt.headless to true unless showDocumentation is set

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey Hugo, once you review this, could you forward it to @Ithildir ?  Thanks!

**Comment by gamerson** [comment]
ci:retest

**Comment by hhuijser** [comment]
Hey @gamerson show.documentation is set to false by default, so by default, the code you're removing is never called?

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/50235

**Pull request closed without merging**
