### PR TITLE
lps-101878

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
@hhuijser If tests pass, please ask Brian to publish project-templates and archetypes. 

Thanks

cc @gamerson

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/78676

**Pull request closed without merging**
