### PR TITLE
LPS-113863 Use the implicit LiferayPortletResponse to call getNamespace()

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:bundle

**Comment by hhuijser** [comment]
@ling-alan-huang, can you resend after this one is merged? https://github.com/hhuijser/liferay-portal/pull/4280

Otherwise, we'll keep getting loads of conflicts

**Comment by ling-alan-huang** [comment]
Got it.

**Comment by ling-alan-huang** [comment]
Hi @hhuijser, this fix will change a loads of JPS, I decide to send several "Fix violations" pulls to you first, after all violations fixed I will send the SF fix  to you.

**Pull request closed without merging**
