### PR TITLE
LPS-114570

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Hi @brianwulbern , you added `@ignore` to the test, but to ignore a Poshi test you have to add `@ignore = "true"`. Anyway, I fixed this test here: https://github.com/rodrigocunhaa/liferay-portal/pull/96

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
ci:stop

**Comment by rodrigocunhaa** [comment]
@hhuijser , @ling-alan-huang and @brianwulbern I created this other PR with my fix: https://github.com/hhuijser/liferay-portal/pull/4372

**Comment by hhuijser** [comment]
Thanks @rodrigocunhaa

**Comment by brianwulbern** [comment]
Thanks, @rodrigocunhaa - I tried to ignore it too quickly 🤦

**Pull request closed without merging**
