### PR TITLE
LPS-84119 Add JSONEmptyLinesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

**Issue:** https://github.com/liferay/liferay-portal/commit/d372ccc2676a6e9ac0c5694daf42d98d94a44ec0

**Related pulls:**
master-private: https://github.com/hhuijser/liferay-portal-ee/pull/2967
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/2968
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/2969

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to this pull.

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/78959

I moved the logic to `JSONWhitespaceCheck` to keep it simple and a TINY bit faster.
I like how you're adding test cases every time!
You've been much better at this than me :)

**Pull request closed without merging**
