### PR TITLE
LPS-54032

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
not only wiki portlet use language key wiki our portal layout template also use language key wiki see class AddDefaultLayoutSetPrototypesAction

**Comment by hhuijser** [comment]
Hey @daledotshan 

I think it's correct to remove that key from the language.properties for the modules wiki?

**Comment by daledotshan** [comment]
I think this link will help
https://in.liferay.com/web/global.engineering/forums/-/message_boards/message/7346737

**Comment by hhuijser** [comment]
Hey @daledotshan 

Thanks for pointing to that forum post. That's very helpful.
However, I don't think we should be having duplicates in modules and portal (and it doesn't seem that Ray is saying that). Having duplicates in two different modules is different.

When we build language properties for plugins, we have a check to make sure that we don't have language keys there that already exist in portal and I think we should treat modules the same.
See LangBuilder.java line 564.

**Comment by daledotshan** [comment]
ok, I have reverted my fix and just keep one wiki property in portal

**Comment by hhuijser** [comment]
Sent to Miguel for further review: https://github.com/migue/liferay-portal/pull/437

**Pull request closed without merging**
