### PR TITLE
LPS-84119 Add testcases for app.bnd rules

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser,

I found that the rules for app.bnd have been already finished, so I just added some testcases on this pull.

https://docs.google.com/document/d/1VsBzfc1wRY0wT90XrCmRfAf_FCKNDzgjftr4CP1H46o/edit?ts=5b186022

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Very nice!
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/74058

**Comment by ling-alan-huang** [comment]
SF failures are not related to this pull.

**Pull request closed without merging**
