### PR TITLE
LPS-55874 Fixing tests.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
Closing for now - more bugs found.

**Comment by brandizzi** [comment]
Hello @hhuijser. 

You've sent me a pull request long time ago regarding an issue with reports scheduling. I could only review it now (I sorry :( ) but also I've found the issue is way more complex than the given fix. I've tried to explain the problem [at the ticket](https://issues.liferay.com/browse/LPS-55874?focusedCommentId=669305&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-669305).

Nonetheless, @yuhai fix resolves part of the problem, so I'm sending it back to you so you can forward it to whoever can take care of that. I also fixed the tests so they pass with the new changes.

Let me know if I missed something or if I can help more.

**Comment by brandizzi** [comment]
ci:retest

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/30419

**Comment by hhuijser** [comment]
Closed pull in Brian's queue as it's still breaking tests.
@yuhai, can you look into this?

**Pull request closed without merging**
