### PR TITLE
LPS-76807

### PR DESCRIPTION
**Pull request by yuhai**
Hi Hugo,

I check the logic and it is good for me.

When post the form, for shortcut, its <input name is "rowIdsDLFileShortcut" />, this is generated by https://github.com/yuhai/liferay-portal/blob/master/modules/apps/collaboration/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/search/EntriesChecker.java#L69-L130.

When choose the shortcut, and https://github.com/yuhai/liferay-portal/blob/master/modules/apps/collaboration/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/portlet/action/ActionUtil.java#L153-L154 also used rowIdsDLFileShortcut.

So using rowIdsDLFileShortcut should be on purposed. For shortcut, if we use rowIdsFileEntry, instead of rowIdsDLFileShortcut. when choose the fileEntry and its shortcut, the rowIdsFileEntry will include same values(just like [1000, 1000]).

cc @Seiphon

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:retest

**Comment by hhuijser** [comment]
@yuhai @Seiphon, why do we create a new list fileEntryIdsList. Seems you turn it into a exact copy of fileEntryId?

**Comment by yuhai** [comment]
Hi @hhuijser 

Please refer to https://github.com/yuhai/liferay-portal/blob/0ebb81aa12410621322191a49827806a614305ed/modules/apps/collaboration/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/portlet/action/EditEntryMVCActionCommand.java#L121-L125

In UI, we can choose the document and shortcut (shortcut point at the document) together. That is to say, when fileEntryId=10000 and fileShortcutId =10001 (matches with fileEntryId=10000), when lock fileShortcutId =10001, we may skip the lock action for fileEntryId (avoid same fileEntryId to execute twice.). fileEntryIdsList is doing this. Otherwise, we will loop the long[] fileEntryIds to whether shortcut related with fileEntryId is in this long[] fileEntryIds. 

This changes from SF commit. You may check the first commit, we are looping the array to skip the same fileEntryId.

Regards,
Hai

**Comment by hhuijser** [comment]
@yuhai. I see
I just don't understand why can't we do the same check with `fileEntryIds`:

```java
if (!fileEntryIdsList.isEmpty() &&
    fileEntryIdsList.contains(toFileEntryId)) {

    continue;
}
```

**Comment by yuhai** [comment]
@hhuijser , 
fileEntryIds is array (long[]) and it doesn't own contains() method. I think we only can use the loop to check whether element exist in this long[]. Please let me know if I misunderstand your meaning.

**Comment by hhuijser** [comment]
@yuhai, ah, now I see that the problem is...
No need to create a new list. You can use ArrayUtil.contains method

**Comment by yuhai** [comment]
@hhuijser ,

Cool. Got it(learn it). We will resubmit the PR.

Thanks,
Hai

**Pull request closed without merging**
