### PR TITLE
LPS-58564

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by hhuijser** [comment]
I think we can apply this all across the board for all liferay code? Always use StringUtil.trim(s)?

**Comment by hhuijser** [comment]
@bejondshao 
Should we apply using StringUtil.trim for all cases in liferay code?

**Comment by bejondshao** [comment]
Hey Hugo, from now on, I think fix in the GetterUtil is enough, because all input fields will call GetterUtil methods. For other String.trim(), there might not be ideographic space. By the way, use StringUtil for all trim() will slow down liferay portal. What if latter version of java can trim ideographic space?

**Comment by hhuijser** [comment]
Hey @bejondshao 

Thanks for the explanation.

Two concerns I still have:
I see that you added com.liferay.portal.kernel.util to Import-Package, because we now also need StringUtil (and other depending classes) ffrom kernel.util.

1. I think we need the same in some other bnd.bnd files (I looked at the one in deployment-helper), but there might be more.
2. I see that for other .bnd files we just add all the classes we need to the Include-Resource. Why aren't we following that pattern in the bnd.bnd in portal-wab-extender?

**Comment by bejondshao** [comment]
Hey Hugo, 

Long time ago I sent a pull request, https://github.com/brianchandotcom/liferay-portal/pull/30821 (I fixed it just because GetterUtil locates in Include-Resource). I asked about the right way to fix it.
Later David met this kind of issue https://issues.liferay.com/browse/LPS-60238, https://github.com/daledotshan/liferay-portal/pull/319. So I fix it like him. The difference is, his fix applies to app model, while mine applies to portal model.

In all, I think https://github.com/brianchandotcom/liferay-portal/pull/30821 is a really bad idea. It takes me hours to find all the dependencies, because I need to rebuild module even portal again and again. What if there's another class needed later? Besides, it's no clue for others to maintain this dependency. I asked andrea.digiorgi how he added these dependencies before. He gave me the same way to find the dependencies. 

Would you help me to get a confirm from other engineers?

**Comment by hhuijser** [comment]
What about my first question? Do we need more dependencies for "deployment-helper". It looks like we're calling one of the affected methods from GetterUtil there but are not including StringUtil?

**Comment by bejondshao** [comment]
Hey Hugo,

Sorry I missed the first one. 

Here is it. https://github.com/bejondshao/liferay-portal/pull/17 this is testing. There's no error. I also do ant all and start portal, do some actions. There's no error.

Before add dependency in portal-wab-extender, it throws many exceptions in console. After add in it, there's no exception. I guess portal-wab-extender is a basic module that can be depended on. I haven't found the location of  deployment-helper. So I'm not sure the dependency of it.

Maybe @daledotshan knows about it.

**Comment by mdelapenya** [comment]
Hi @hhuijser Is this code going to be merged? We have this ticket open in our dashboard and we think this solution could be valid.

If you need help with OSGi dependencies, we can help here.

Cheers!

**Pull request closed without merging**
