### PR TITLE
LPS-136864 XMLServiceFinderNameCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Violatons on master:
```
java.lang.Exception: Found 23 formatting issues:
1: Finder name 'AccountEntryUserRel#AEI' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/account/account-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
2: Finder name 'AccountEntryUserRel#AUI' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/account/account-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
3: Finder name 'CTAutoResolutionInfo#CTCollectionId' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/change-tracking/change-tracking-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
4: Finder name 'CTComment#CTCollectionId' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/change-tracking/change-tracking-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
5: Finder name 'CTComment#CTEntryId' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/change-tracking/change-tracking-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
6: Finder name 'CTEntry#CTCollectionId' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/change-tracking/change-tracking-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
7: Finder name 'CTMessage#CTCollectionId' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/change-tracking/change-tracking-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
8: Finder name 'CTPreferences#CollectionId' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/change-tracking/change-tracking-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
9: Finder name 'CTPreferences#PreviousCollectionId' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/change-tracking/change-tracking-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
10: Finder name 'CTProcess#CollectionId' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/change-tracking/change-tracking-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
11: Finder name 'CommerceAccountGroup#CommerceAccountGroupIds' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-account-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
12: Finder name 'CommerceNotificationQueueEntry#LtS' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-notification-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
13: Finder name 'CommerceShipment#GroupIds' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
14: Finder name 'CommerceShipmentItem#CommerceShipment' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
15: Finder name 'DEDataDefinitionFieldLink#DDMStructureId' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/data-engine/data-engine-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
16: Finder name 'DEDataListView#DDMStructureId' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/data-engine/data-engine-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
17: Finder name 'MBMessage#ThreadReplies' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/message-boards/message-boards-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
18: Finder name 'OAuth2Application#C' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
19: Finder name 'OAuth2ApplicationScopeAliases#C' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
20: Finder name 'FinderWhereClauseEntry#Name_Nickname' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/modules/util/portal-tools-service-builder-test-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
21: Finder name 'Organization#CompanyIdLocations' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
22: Finder name 'AssetLink#E1' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portlet/asset/service.xml (SourceCheck:XMLServiceFinderNameCheck)
23: Finder name 'AssetLink#E2' should be combined by comparator prefix and finder colume name: /home/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portlet/asset/service.xml (SourceCheck:XMLServiceFinderNameCheck)

```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/105550

**Pull request closed without merging**
