### PR TITLE
LPS-71555 Source formatter: compress import and taglib declarations in simple JSP files without init.jsp

### PR DESCRIPTION
**Pull request by arboliveira**
Hi Hugo, sending you a tiny improvement for Source Formatter. I'm working on a major new development (10+ standalone portlets) and I was talking to @brianchandotcom earlier about how it would be super convenient to have simple JSP files locally declare their own imports and taglibs, without the need to include an extra init.jsp. He said it would be okay as long as SF could be changed to compress the imports and taglibs in the JSP files themselves, same way init.jsp is already compressed.

(Like this: https://github.com/arboliveira/liferay-portal/blob/039df415f95d38e3d7c2a8e4e599a2ad19a7329c/modules/util/source-formatter/src/test/resources/com/liferay/source/formatter/dependencies/expected/FormatImportsAndTaglibsWithoutInit.testjsp#L17-L30)

I didn't want you to have even more work and it sounded simple enough, so here it is -- fix and tests for JSPSourceProcessor   😄 

Please notice the following 13 JSP files in our codebase currently contain uncompressed or unsorted import / taglib clauses, so this pull request is going to fail `source-format-jdk8` - I'm not sure how to go about that - I think you usually run locally and commit this kind of "mass fixes" as part of review?

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/modules/apps/static/portal-osgi-web/portal-osgi-web-portlet-container-test/src/testIntegration/resources/META-INF/resources/view.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/modules/apps/web-experience/asset/asset-entry-query-processor-custom-user-attributes/src/main/resources/META-INF/resources/custom_user_attributes.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/modules/apps/web-experience/layout/layout-admin-web/src/main/resources/META-INF/resources/control/menu/information_messages.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/modules/apps/web-experience/layout/layout-admin-web/src/main/resources/META-INF/resources/control/menu/customization_settings.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/modules/apps/foundation/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/available_languages.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/modules/apps/collaboration/comment/comment-taglib/src/main/resources/META-INF/resources/init.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/modules/sdk/gradle-plugins-jasper-jspc/src/gradleTest/smoke/src/main/resources/init.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/portal-impl/src/com/liferay/portal/deploy/dependencies/iframe.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/portal-web/docroot/index.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/portal-web/docroot/html/common/themes/body_bottom.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/portal-web/docroot/html/portal/maintenance.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/portal-web/docroot/html/portal/layout.jsp

https://github.com/arboliveira/liferay-portal/tree/fb68476d7a2255e12173b1d29d3a61a29f2bce8b/portal-web/docroot/errors/code.jsp

Thanks!!

https://issues.liferay.com/browse/LPS-71555

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
As I mentioned, `source-format-jdk8` failed due to some of our existing JSP files being already uncompressed right now.

**Comment by hhuijser** [comment]
Hey @arboliveira, is this stuff urgent?

You can see that I am in the process of moving everything out of JSPSourceProcessor to smaller FileCheck files.
The logic to compress imports will be moved soon to it's own class and I can then include your changes.

Right now, we have a lot of extra code (like what you did in populateFileChecks) that makes things messy, which we can avoid if I add it later on.

**Comment by arboliveira** [comment]
No worries. I can send my other pull to Brian using `init.jsp` for now. Just let me know when the big move is finished and I'll resend the fix on the new structure. Thanks! 😃

**Comment by hhuijser** [comment]
@arboliveira, no need to resend the fix, I will incorporate your changes when I get to it (I'll cc you). Thanks for the contribution!

**Comment by hhuijser** [comment]
@arboliveira what's the scenario where tests fail with NPE because of _contentsMap?

**Pull request closed without merging**
