### PR TITLE
LPS-104679 Apply Checkstyles to jsp_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Related pulls:

7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3007
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3006
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3005
7.0.x-private: https://github.com/hhuijser/liferay-portal-ee/pull/3004

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/81525

I redid the SF changes for `JSONNamingCheck`. Please have a look (and check the line numbers in the warning messages more carefully next time).

**Comment by ling-alan-huang** [comment]
Got it, thanks.

**Pull request closed without merging**
