### PR TITLE
LPS-78802

### PR DESCRIPTION
**Pull request by petershin**
@ahdezma @gamerson

### CODE REVIEW

**Comment by hhuijser** [comment]
@petershin @ahdezma @gamerson

What are some cases that we want to be allowed?
For streams, we allow chaining on a stream variable, but not on the class Stream itself.

**Comment by ahdezma** [comment]
@hhuijser 

Why not?

It doesn't make any sense to not allow doing this:

```
return Optional.ofNullable(
    map.get("thing")
).filter(
    string -> !string.isEmpty()
).map(
    string -> string + "other thing"
).orElse(
    "default case"
);
```

and instead forcing developers to do:

```
Optional<String> optional = Optional.ofNullable(map.get("thing"));

return optional.filter(
    string -> !string.isEmpty()
).map(
    string -> string + "other thing"
).orElse(
    "default case"
);
```

Those classes weren't created to be used like this. It is just adding verbosity and complexity, it isn't giving users anything good. And, in the specific case of `Stream`, it leaves the door open for reusing the stream, ending in an exception.

**Comment by hhuijser** [comment]
Hey @ahdezma,

There have been multiple discussions regarding this topic already.
Julio talked to Brian about this before and Brian feels really strongly about only allowing the variable and not the class itself. I can forward you an email thread where this was discussed.

**Comment by hhuijser** [comment]
Closing this one for now...

**Pull request closed without merging**
