### PR TITLE
LPS-105380 Yaml

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: [liferay@bc3bb15](https://github.com/liferay/liferay-portal/commit/bc3bb1501dc23f7b919298eba6e19ea99ea6bc67)

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang, what about what I did here?: https://github.com/ling-alan-huang/liferay-portal/pull/552

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Forward here: [ling-alan-huang#552](https://github.com/ling-alan-huang/liferay-portal/pull/552)

**Pull request closed without merging**
