### PR TITLE
SourceFormat freezes in this pull

### PR DESCRIPTION
**Pull request by pyoo47**
Hugo,
This pull is consistently freezing during the sourceFormat unit test. I am also experiencing freezes when running ../../../gradlew formatSource in modules/test/jenkins-results-parser. Some files are formatted but never finishes. Do you think you can take a look at what might be causing this?

Thanks,
Peter

### CODE REVIEW

**Comment by pyoo47** [comment]
@hhuijser Here's the point in the source formatter test where it froze and eventually aborted.
```
     [exec] com.liferay.portal.tools.data.partitioning.sql.builder.postgresql.exporter.PostgreSQLInsertSQLBuilderTest > testBuildFieldFieldFloat PASSED
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] :util:source-formatter:compileJava
     [exec] :util:source-formatter:buildCSS UP-TO-DATE
     [exec] :util:source-formatter:processResources
     [exec] :util:source-formatter:transpileJS SKIPPED
     [exec] :util:source-formatter:configJSModules SKIPPED
     [exec] :util:source-formatter:copyLibs SKIPPED
     [exec] :util:source-formatter:replaceSoyTranslation UP-TO-DATE
     [exec] :util:source-formatter:classes
     [exec] :util:source-formatter:compileTestJava
     [exec] :util:source-formatter:processTestResources
     [exec] :util:source-formatter:testClasses
     [exec] :util:source-formatter:test
     [exec] 
     [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STARTED
     [exec] 
     [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STANDARD_OUT
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/2.6.0/51dd0d720f3bb4aa9be024b48d73b69152bc93a9/com.liferay.portal.impl-2.6.0.jar!/system.properties
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
     [exec]     Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/classes/system-ext.properties
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
Recording test results
```

**Comment by pyoo47** [comment]
ci:retest

**Comment by hhuijser** [comment]
@pyoo47 I'll have a look later today... holiday time in China, so not online much...

**Comment by hhuijser** [comment]
See https://github.com/pyoo47/liferay-portal/pull/201

**Comment by pyoo47** [comment]
@hhuijser Thanks Hugo!

**Pull request closed without merging**
