### PR TITLE
Lps 133987 more

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@hhuijser Please do whatever refactoring and run whatever CI tests you think are necessary. Thanks!

**Comment by hhuijser** [comment]
@ngriffin7a can't we simplify this by using pattern `*.jspx?`

**Comment by ngriffin7a** [comment]
@hhuijser `*.jspx` is the pattern I specified. Not sure what you mean.

**Comment by hhuijser** [comment]
Does the method take regex pattern? If so, `*.jspx?` takes both `.jsp` and `.jspx`

**Comment by ngriffin7a** [comment]
No, I checked and ultimately it calls this method:
https://docs.osgi.org/javadoc/osgi.core/7.0.0/org/osgi/framework/Bundle.html#findEntries-java.lang.String-java.lang.String-boolean-

And the Javadoc indicates that "pattern" can only take a wildcard.

So even though `*.jsp*` would include both ".jsp" and ".jspx" files, it would also include ".jspf" files which I *think* might be undesirable? It would certainly change the existing behavior, and I didn't want to do that. So that's why there are separate calls for `.jsp` and `.jspx`

**Comment by hhuijser** [comment]
Got it, my bad

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by ngriffin7a** [comment]
@hhuijser Are these failures related? If not, can we try `ci:forward` again? Thanks.

**Comment by hhuijser** [comment]
@ngriffin7a these look unrelated to me... sent the pull straight to Brian: https://github.com/brianchandotcom/liferay-portal/pull/103765

**Comment by ngriffin7a** [comment]
Thanks @hhuijser !

**Pull request closed without merging**
