### PR TITLE
LPS-75509 CKEditor content is cleared when resizeing browser

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by ling-alan-huang** [comment]
ci:retest

**Comment by ling-alan-huang** [comment]
The failures are related to my changes.

**Comment by hhuijser** [comment]
Sent to Patrick for review: https://github.com/pat270/liferay-portal/pull/215

**Pull request closed without merging**
