### PR TITLE
LPS-84119 SF gradle

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/20b1b636beadc0cc144dda4d08133c52736504f1

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Hey @ling-alan-huang I sent to Brian (https://github.com/brianchandotcom/liferay-portal/pull/78677), but there are merging conflicts.
Brian's repo is ahead of `liferay` repo by quite a bit right now.

Can you resend when the `liferay` repo is up-to-date?

**Comment by hhuijser** [comment]
FYI: This is the fix for https://github.com/brianchandotcom/liferay-portal/pull/78677/commits/65c47a5d3e3f6e7fbba8c2a695d7273cfaaa7deb:
https://github.com/brianchandotcom/liferay-portal/pull/78683

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/3771

**Pull request closed without merging**
