### PR TITLE
LPS-105380 ToolsUtil

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: 
https://github.com/JorgeFerrer/liferay-portal/pull/906#issuecomment-872200635
https://liferay.slack.com/archives/C1SJ64S9X/p1625147539033200

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
