### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@vicnate5 repeat failure in the license batch, can you please let Hugo know if it's related to his code?
```
java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-20100-workflow-metrics-processes] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-20100-workflow-metrics-processes] and [action.auto_create_index] is [false]]]
```
@hhuijser The int test failures are a known intermittent issue https://issues.liferay.com/browse/LPS-136151. You can forward this to Brian if Victor has no concerns about the failure in the license test batch.

**Comment by vicnate5** [comment]
@hhuijser The failures are not related to your PR, recommend manual forward.

**Comment by hhuijser** [comment]
thanks @jpince @vicnate5 
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/106014

**Pull request closed without merging**
