### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:bundle

**Comment by hhuijser** [comment]
ci:test:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@hhuijser I'm assuming ant all doesn't compile integration tests. I don't think there's a good solution for this outside of running `relevant` or `forward` when there's a change that could impact int tests.

**Comment by hhuijser** [comment]
@jpince, got it... well at least ci:test:bundle is catching most of the issues :)

**Pull request closed without merging**
