### PR TITLE
LPS-93513 Revert suppression and fix

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

This pull is going to revert yesterday's suppression and fix that issue.

Yesterday's suppression see here: https://github.com/hhuijser/liferay-portal/pull/3528

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/72302

**Pull request closed without merging**
