### PR TITLE
LPS-105380 ChainingCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Previous pull: https://github.com/hhuijser/liferay-portal/pull/4331

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4359

**Comment by ling-alan-huang** [comment]
> I see
> 4:52
> We should add the url statement inside the try. MalformedURLException extends IOException (edited) 
> 4:54
> I am going to send the LPS-105380 Fix violations commits to Brian (except for BaseUserDemoDataCreator.java, you can redo that one)
> 4:56
> For the changes to ChainingCheck... let's rename the key to chaining.avoid.new.instance and the method to _checkChainingOnNewInstance to keep it in sync with the other logic
> 4:56
> Can you take care of that and send that?
> 
> Alan Huang  4:56 PM
> Sure, I will resend.
> 
> Hugo Huijser:city_sunset:  4:57 PM
> because it's really not an inlining issue
> 4:57
> I'd say just warn with Avoid chaining on new class instantiation and add documentation to chaining_check.markdown to explain more, if needed
> 
> Alan Huang  4:58 PM
> Got it.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/4385

**Pull request closed without merging**
