### PR TITLE
LPS-84119 Also scan *.tld in util-taglib/src/META-INF

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Auto SF for 7.0.x-private: https://github.com/hhuijser/liferay-portal-ee/pull/2907

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/75731

**Pull request closed without merging**
