### PR TITLE
LPS-52278

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by hhuijser** [comment]
Couple of questions:
1. Can't we simply use StringUtil.count instead of StringUtils.countOccurrencesOf?
2. Do we need to make getElementNames recursive? It seems that that only makes sense if we have dynamic-element elements inside a dynamic-element, which we don't?
3. sb.appends are messy (line 271-290). Sometimes you end with the space, sometimes you start with it... make it more consistent. Also, do we really need that much info there? Can we keep it a bit shorter and instead make a comment in the code there?
4. Line 938. You create a random that you then use for all structures? Is that right or should we create a new random for each structure?
5. Line 650: !newTemplateVariable.equals(StringPool.NULL) is a bit unusual. Is it okay when it's blank but not when value is "null"? Woudl we have to check for null value (not the string "null") as well to avoid NPE?

**Comment by jonathanmccann** [comment]
@BryanEngler

**Comment by BryanEngler** [comment]
1) yes. i can change it...

2) ya you can have dynamic elements inside dynamic elements. thats basically whats causing this issue. ill attach a structure.xml file to the lps

3) if i put the explanation in a comment, and then just put something like "content doesnt match for article X. see VerifyJournal.updateArticlesUsingStructure() for explaination" in the log message does that work?

4) random- i think my reasoning was that because some structures have parent structures, we basically want to treat them both as one structure as far as the names go. so i figured use the same Random object for them all. im not an expert on randoms so i dont know for sure, but i think either way we still get a random number between 1000 and 9999 that is independent of all the other values in the sequence? as far as this use case goes it probably doesnt really matter since i wouldnt think people are using structures where they have that many duplicated element names. even if the random returned the same number twice, it would only cause problems if it did it for two elements that also happen to have the same name. and even if that did happen, you could run the verify process again and it would generate new numbers for the elements that still had duplicate names. 

5) i agree that its a little strange, but i can explain it...
the check at line 650 can actually be removed. the names are being added on line 175 and we do the check there. 
what is happening is that we are calling the getElementTemplateName method with the root element and StringPool.BLANK as arguments at line 172. ("element" gets passed into getElementTemplateNames as the root element at 629, 642). inside the method, attributeValue("name") for the root element returns null, but that is appended to StringPool.BLANK which gives us the string "null".

let me know if you have any more questions. if not let me know and i can send you a new pr with the few updates

**Comment by hhuijser** [comment]
No need to resend for now...
I'll try to look at this one more later today, but not sure if I'll be able to...

**Comment by hhuijser** [comment]
One more quick question:
Is it necessary to loop through structure twice? Can we do the updateTemplateVariables and updateArticlesUsingStructure in a single loop or did you loop twice on purpose?

**Comment by BryanEngler** [comment]
we need to loop twice because articles can be using a structure that has a parent structure. so we need to update all of the structures first, then we can update the articles without having to worry about the article using a structure with a parent structure that hasnt been updated yet

**Comment by hhuijser** [comment]
Made some changes and sent back to Bryan.

**Pull request closed without merging**
