### PR TITLE
LPS-104679 SF JSP

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

I tried to apply `MapBuilderCheck` for JSP today, but I could't make it.

```
<module name="com.liferay.source.formatter.checkstyle.checks.MapBuilderCheck">
	<property name="checkInline" value="true" />
	<property name="enabled" value="false" />
	<message key="builder.include" value="Include method call ''{0}'' ({1}) in ''{2}'' ({3})" />
	<message key="builder.inline" value="Inline variable definition ''{0}'' ({1}) inside ''{2}'' ({3})" />
	<message key="builder.use" value="Use ''{0}'' ({1}, {2})" />
	<message key="builder.use.instead" value="Use ''{0}'' instead of new instance of ''{1}''" />
	<message key="null.value.incorrect" value="Null values are not allowed in ''{0}''" />
</module>
```
1.

```
Inline variable definition 'assetRenderer' (126) inside 'HashMapBuilder' (149): /modules/apps/journal/journal-content-web/src/main/resources/META-INF/resources/view.jsp 126 (Checkstyle:MapBuilderCheck)
Inline variable definition 'assetRenderer' (147) inside 'HashMapBuilder' (149): /modules/apps/journal/journal-content-web/src/main/resources/META-INF/resources/view.jsp 147 (Checkstyle:MapBuilderCheck)
... ...
... ...
Inline variable definition 'selLayout' (30) inside 'HashMapBuilder' (100): /modules/apps/layout/layout-seo-web/src/main/resources/META-INF/resources/layout/screen/navigation/entries/open_graph.jsp 30 (Checkstyle:MapBuilderCheck)
Inline variable definition 'url' (195) inside 'HashMapBuilder' (197): /portal-web/docroot/html/portal/setup_wizard.jsp 195 (Checkstyle:MapBuilderCheck)
```

For `checkInline`, it doesn't apply to JSP, so I can simply disable it in `checkstyle-jsp.xml`.

-----------------------------------------

2.

```
Include method call 'contextObjects.put' (201) in 'HashMapBuilder' (189): /modules/apps/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/view.jsp 189 (Checkstyle:MapBuilderCheck)
Include method call 'data.put' (43) in 'HashMapBuilder' (31): /modules/apps/product-navigation/product-navigation-site-administration/src/main/resources/META-INF/resources/sites/site_administration_body.jsp 31 (Checkstyle:MapBuilderCheck)
Include method call 'data.put' (52) in 'HashMapBuilder' (40): /modules/apps/site-navigation/site-navigation-item-selector-web/src/main/resources/META-INF/resources/view_site_navigation_menus.jsp 40 (Checkstyle:MapBuilderCheck)
Include method call 'data.put' (86) in 'HashMapBuilder' (76): /modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/asset_display/preview.jsp 76 (Checkstyle:MapBuilderCheck)
Include method call 'data.put' (88) in 'HashMapBuilder' (74): /modules/apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/view_resources.jsp 74 (Checkstyle:MapBuilderCheck)
Include method call 'editCategoriesData.put' (356) in 'HashMapBuilder' (342): /modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/view.jsp 342 (Checkstyle:MapBuilderCheck)
Include method call 'editTagsData.put' (331) in 'HashMapBuilder' (317): /modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/view.jsp 317 (Checkstyle:MapBuilderCheck)
Include method call 'rowData.put' (64) in 'HashMapBuilder' (52): /modules/apps/journal/journal-web/src/main/resources/META-INF/resources/view_entries.jsp 52 (Checkstyle:MapBuilderCheck)
```

For _"Include method call..."_, we don't have the switcher to enable/disable it, I think we need to add a logic to determine if the code(content) is real Java code or transformed code from JSP.
Maybe I can check if the content contains _"// PLACEHOLDER"_ or the filename ends with _".jsp"_, I'm working on it...

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@joshchong @xbrianlee failing search tests. Please retest if they are flaky.
`SearchDifferentScopesViaSearchWidget` `Search#SearchGlobalTemplateSmoke`

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
Waiting for https://github.com/brianchandotcom/liferay-portal/pull/87583 before re-testing

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.
Test again..

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Running test one more time here: https://github.com/hhuijser/liferay-portal/pull/4141

If that one test still fails, I'll send to Brian directly

**Pull request closed without merging**
