### PR TITLE
LPS-136078 JIRAUtil

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
Hey @hhuijser,
Issue:
https://issues.liferay.com/browse/LPS-136078
https://liferay.slack.com/archives/C19PWQ74J/p1626900938148400

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@ling-alan-huang @hhuijser thank you!

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
