### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@jpince

**Comment by jpince** [comment]
@hhuijser please forward. I see the `SharepointConnectionTest.classMethod` failure in the [previous test result](https://github.com/hhuijser/liferay-portal/pull/5825#issuecomment-904107485) under "failures in common with upstream"

cc/ @austinchiang

**Comment by austinchiang** [comment]
ci:forward

**Comment by jpince** [comment]
@austinchiang has the magic touch :mage_man: Thank you!

**Pull request closed without merging**
