### PR TITLE
LPS-59610

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
the reason is that even "web-content" is defined in "modules/app/journal" -> 

but when click "export/import", it is actually use another module, "export_portlet.jsp"

similar use "referenced-content"

**Comment by hhuijser** [comment]
Can you document this clearly on the LPS.
The comment on the LPS right now is not very helpful...

**Comment by daviddotzhang** [comment]
updated

**Comment by hhuijser** [comment]
Sent to Julio for review: https://github.com/juliocamarero/liferay-portal/pull/3730

**Pull request closed without merging**
