### PR TITLE
LPS-74089 - Auto sort "apply plugin" logic

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @petershin 

I would rather have this be part of a bigger task that would apply all the sorting rules specified in the readme (like we do for *.java).
What do you think?

**Comment by petershin** [comment]
@hhuijser - Do you want to consolidate all the gradle sorting logic into one big GradleXXXCheck.java or do you mean something else?

**Comment by hhuijser** [comment]
Correct. 

Now you have logic to make sure the "apply plugin" code is in the correct location.
Got a feeling you'll want to reuse some of the logic for other sorting?

You might want to parse it a bit and write a comparator? You can split up that up in seperate classes.

**Comment by hhuijser** [comment]
Closing for now

**Pull request closed without merging**
