### PR TITLE
LPS-65685 Use the right path to prevent NPE

### PR DESCRIPTION
**Pull request by epgarcia**
Hi @hhuijser,

The UpgradeSchema was failing for Journal Service because the relative path to the update.sql could not be resolved after moving the class to another package. I set an absolute path and this should fix it. Alternatively you could move the update.sql to a resource package matching the path of the UpgradeSchema class.

Thanks

### CODE REVIEW

**Comment by epgarcia** [comment]
Stills fails to read the update.sql. I moved the update.sql to the v0_0_4/dependencies package.

**Comment by hhuijser** [comment]
ci:retest

**Comment by epgarcia** [comment]
@hhuijser I think it worked this time. Could you please confirm? Thanks!

**Comment by hhuijser** [comment]
Yes!! Thank you so much! Tried too many times myself...
Will send to Brian in a bit...

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/39776

**Pull request closed without merging**
