### PR TITLE
LPS-84119 Do not initialize capacity with the numeric literal

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/cc44834780f7aeb227b0b915ad25dc9aa5cf0a3a

This is the output by `SFDebugHelper.printStructure(detailAST);` for my test case https://github.com/hhuijser/liferay-portal/commit/e2502921697424324068cc27159866135e32a4ee :

```
+--VARIABLE_DEF 262
    +--MODIFIERS 262
    +--TYPE 262
        +--IDENT (List) 262
        +--TYPE_ARGUMENTS 262
            +--GENERIC_START (<) 262
            +--TYPE_ARGUMENT 262
                +--IDENT (String) 262
            +--GENERIC_END (>) 262
    +--IDENT (list1) 262
    +--ASSIGN (=) 262
        +--EXPR 262
            +--LITERAL_NEW (new) 262
                +--IDENT (ArrayList) 262
                +--TYPE_ARGUMENTS 262
                    +--GENERIC_START (<) 262
                    +--GENERIC_END (>) 262
                +--LPAREN (() 262
                +--ELIST 262
                +--RPAREN ()) 262
+--VARIABLE_DEF 266
    +--MODIFIERS 266
    +--TYPE 266
        +--IDENT (List) 266
        +--TYPE_ARGUMENTS 266
            +--GENERIC_START (<) 266
            +--TYPE_ARGUMENT 266
                +--IDENT (String) 266
            +--GENERIC_END (>) 266
    +--IDENT (list2) 266
    +--ASSIGN (=) 266
        +--EXPR 266
            +--LITERAL_NEW (new) 266
                +--IDENT (ArrayList) 266
                +--TYPE_ARGUMENTS 266
                    +--GENERIC_START (<) 266
                    +--GENERIC_END (>) 266
                +--LPAREN (() 266
                +--ELIST 266
                    +--EXPR 266
                        +--METHOD_CALL (() 266
                            +--DOT (.) 266
                                +--IDENT (list1) 266
                                +--IDENT (size) 266
                            +--ELIST 266
                            +--RPAREN ()) 266
                +--RPAREN ()) 266
+--VARIABLE_DEF 268
    +--MODIFIERS 268
    +--TYPE 268
        +--IDENT (List) 268
        +--TYPE_ARGUMENTS 268
            +--GENERIC_START (<) 268
            +--TYPE_ARGUMENT 268
                +--IDENT (String) 268
            +--GENERIC_END (>) 268
    +--IDENT (list3) 268
    +--ASSIGN (=) 268
        +--EXPR 268
            +--LITERAL_NEW (new) 268
                +--IDENT (ArrayList) 268
                +--TYPE_ARGUMENTS 268
                    +--GENERIC_START (<) 268
                    +--GENERIC_END (>) 268
                +--LPAREN (() 268
                +--ELIST 268
                    +--EXPR 268
                        +--NUM_INT (1) 268
                +--RPAREN ()) 268
+--VARIABLE_DEF 270
    +--MODIFIERS 270
    +--TYPE 270
        +--IDENT (List) 270
        +--TYPE_ARGUMENTS 270
            +--GENERIC_START (<) 270
            +--TYPE_ARGUMENT 270
                +--IDENT (String) 270
            +--GENERIC_END (>) 270
    +--IDENT (list4) 270
    +--ASSIGN (=) 270
        +--EXPR 270
            +--LITERAL_NEW (new) 270
                +--IDENT (ArrayList) 270
                +--TYPE_ARGUMENTS 270
                    +--GENERIC_START (<) 270
                    +--GENERIC_END (>) 270
                +--LPAREN (() 270
                +--ELIST 270
                    +--EXPR 270
                        +--IDENT (_SIZE) 270
                +--RPAREN ()) 270
+--VARIABLE_DEF 272
    +--MODIFIERS 272
    +--TYPE 272
        +--IDENT (Map) 272
        +--TYPE_ARGUMENTS 272
            +--GENERIC_START (<) 272
            +--TYPE_ARGUMENT 272
                +--IDENT (String) 272
            +--COMMA (,) 272
            +--TYPE_ARGUMENT 272
                +--IDENT (String) 272
            +--GENERIC_END (>) 272
    +--IDENT (map) 272
    +--ASSIGN (=) 272
        +--EXPR 272
            +--LITERAL_NEW (new) 272
                +--IDENT (HashMap) 272
                +--TYPE_ARGUMENTS 272
                    +--GENERIC_START (<) 272
                    +--GENERIC_END (>) 272
                +--LPAREN (() 272
                +--ELIST 272
                    +--EXPR 272
                        +--NUM_INT (2) 272
                +--RPAREN ()) 272




+--VARIABLE_DEF 304
    +--MODIFIERS 304
        +--LITERAL_PRIVATE (private) 304
        +--FINAL (final) 304
    +--TYPE 304
        +--IDENT (List) 304
        +--TYPE_ARGUMENTS 304
            +--GENERIC_START (<) 304
            +--TYPE_ARGUMENT 304
                +--IDENT (String) 304
            +--GENERIC_END (>) 304
    +--IDENT (_list5) 304
    +--ASSIGN (=) 304
        +--EXPR 304
            +--LITERAL_NEW (new) 304
                +--IDENT (ArrayList) 304
                +--TYPE_ARGUMENTS 304
                    +--GENERIC_START (<) 304
                    +--GENERIC_END (>) 304
                +--LPAREN (() 304
                +--ELIST 304
                    +--EXPR 304
                        +--NUM_INT (1) 304
                +--RPAREN ()) 304
    +--SEMI (;) 304

```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Hey @ling-alan-huang 
- I don't think this applies to all these types. The fact it's bad practice for `HashMap` is that HashMap uses a `load factor` (See https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html)
- Why are you skipping constants?

**Comment by hhuijser** [comment]
Also, for something like this, I think it's easier to create a `SourceCheck` that autofixes these?

**Comment by ling-alan-huang** [comment]
Closing, I will check it.

**Pull request closed without merging**
