### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@jpince

**Comment by jpince** [comment]
@hhuijser I would say manually forward this one, the failure seems like a fluke, and your changes to commerce were only modifying text, not logic (so I would say this is low risk).

@iovaneale potential flaky test `LocalFile.CommerceFrontStore#ViewStoreFrontSimpleProduct`, can you please refer to the right Commerce QA lead?

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/100852

**Comment by iovaneale** [comment]
Thanks @jpince 

@lorenzolapescara

**Pull request closed without merging**
