### PR TITLE
LPS-84119 Rename

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,
Issue: https://github.com/liferay/liferay-portal/commit/7e76f571287c1238ce202fb9548398808ca7a0f2

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by jpince** [comment]
@ling-alan-huang I quarantined the Sites Templates tests here: https://github.com/brianchandotcom/liferay-portal/pull/87745

**Comment by ling-alan-huang** [comment]
> @ling-alan-huang I quarantined the Sites Templates tests here: [brianchandotcom#87745](https://github.com/brianchandotcom/liferay-portal/pull/87745)

Thanks.

**Comment by ling-alan-huang** [comment]
Rebase and retest.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@hhuijser, I resolved SF failures in https://github.com/hhuijser/liferay-portal/pull/4148.

**Comment by ling-alan-huang** [comment]
Closing, merged commits into https://github.com/hhuijser/liferay-portal/pull/4148

**Pull request closed without merging**
