### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@cvanut Can you guys address the [Forms test failures](https://liferay.spiraservice.net/16/Build/21238.aspx) - either quarantine those tests or direct me to the fix(es) for them?  Thanks!

**Comment by brianwulbern** [comment]
Failures are either commonly flaky or known issues.

Sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/91890

**Comment by cvanut** [comment]
Hi @brianwulbern , 
[Forms Test Suite](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1246246035) has only two tests failing, which we are already working on fixes for them. 
- Forms#AddFormWithDuplicateTextFields
- Forms#PreviewAndPublishForm

I noticed that some other tests failed on [development suite](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1246494524&testrayComponentId=863785156), but as these failures has not happened on Forms test suite nor locally, we believe that it could be environment failures (we're still analyzing that).

**Pull request closed without merging**
