### PR TITLE
LPS-114565

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:bundle

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward @john-co yarn failure

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@suilin @xbrianlee fyi the Search test failures, both flaky.
https://testray.liferay.com/home/-/testray/cases/865147948
https://testray.liferay.com/home/-/testray/cases/865147938

@austinchiang fyi the one flaky [Blogs test](https://testray.liferay.com/home/-/testray/cases/867509024) failure

**Comment by hhuijser** [comment]
ci:forward

**Comment by xbrianlee** [comment]
@brianwulbern Sorry it looks like we didn't get to these failures in time. The Liferay logs no longer exist, but I suspect something happened during startup that would offer clues as to what happened. We'll keep an eye out for more of those failures.

**Pull request closed without merging**
