### PR TITLE
LPS-62328

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @daledotshan 

Did @bejondshao did test your changes?

**Comment by bejondshao** [comment]
Hey Hugo,

I tested my change but I didn't test @daledotshan 's change.

**Comment by daledotshan** [comment]
@hhuijser 
I tested it by myself, it works.
@bejondshao 
Could you test it again with my fix to double check it?

**Comment by bejondshao** [comment]
Hey @daledotshan , I'll do it tomorrow

**Comment by bejondshao** [comment]
Hey @daledotshan , the new sf pattern misses end quote
`
"src=\"((?!(\\s*http://|\\s*https://)).+)"
`

**Comment by daledotshan** [comment]
Hey Bejond,
Thanks for catching the misses end quotation issue. I fixed it and update this pull request.
As for the fail test case, I can not replicate in my side

**Comment by bejondshao** [comment]
Hey @daledotshan ,

Yes, I rebase the code on latest master. There's no errors.

**Comment by hhuijser** [comment]
Sent to Mate for further review: https://github.com/matethurzo/liferay-portal/pull/1356

**Pull request closed without merging**
