### PR TITLE
LPS-93510 Poshi Script SF: Enforce one space between command keyword, command name, and opening brace

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

If this is good to you, please send to Kenji.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
sf:test:relevant

**Comment by ling-alan-huang** [comment]
SF test results: https://github.com/ling-alan-huang/liferay-portal/pull/70#issuecomment-495504250

**Comment by hhuijser** [comment]
Sent to Kenji for review: https://github.com/kenjiheigel/liferay-portal/pull/495

**Comment by ling-alan-huang** [comment]
Good changes.

**Pull request closed without merging**
