### PR TITLE
LPS-123309 BNDLiferayRelengBundleCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://liferay.slack.com/archives/GV90WPXCK/p1607319189000100

Related pull: 7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3171

Also, I fixed clean SF issue on 7.2.x and 7.1.x.
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3173
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3172

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:f

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
