### PR TITLE
LPS-84119 Enforce compatible minor version for frontend-js-web

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser,

See the issue here: https://github.com/brianchandotcom/liferay-portal/pull/74471

There is no violations on master, 7.1.x, 7.0.x.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
Let's use a property in `source-formatter.properties` to do this.
This way we can simply add there if we want to apply to other dependencies.

You can see how we do this in `GradleDependencyArtifactsCheck` with property `source.check.gradle.dependency.artifacts.check.enforceVersionArtifacts`

**Comment by ling-alan-huang** [comment]
Got it, closing.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/3598

**Pull request closed without merging**
