### PR TITLE
COMMERCE-5534 SF match jsp filenames to *MVCRenderCommand on render functions

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-5534

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:reevaluate:1122004_4149

**Comment by dsitu** [comment]
ci:forward

**Pull request closed without merging**
