### PR TITLE
LPS-20

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@timpak, still seeing the `LocalFile` failures here in my own queue...

**Comment by timpak** [comment]
@hhuijser i'll take a look into both PRs

**Comment by timpak** [comment]
@hhuijser none of the functional failures are related to your changes in both PRs you mentioned me on. those failures are known issues in upstream.

**Pull request closed without merging**
