### PR TITLE
LPS-60558

### PR DESCRIPTION
**Pull request by samuelkong**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
@samuelkong @hhuijser 

I think we can,t remove "HtmlUtil.render", it was added by LPS-48485, as we need to extract some css style, can be like  "<span>edit-x</span>.  see LPS-48485

this fix has a regression, when mouse over the "Edit" button, it only shows "Edit", but it should show "Edit-X", "X" is the title.

**Comment by hhuijser** [comment]
Sent to Tomas: https://github.com/topolik/liferay-portal/pull/226

**Comment by samuelkong** [comment]
@daviddotzhang 

I don't understand, you version of the code actually looks like 'Edit' in the HTML. But my version will at least preserve the XSS script in the HTML. I'll see if I have time later today to post a little more details.

**Comment by topolik** [comment]
I did the analysis and fix for LPS-48485 is for sure incorrect. It is intended behavior to have the HTML there. I found the same scenario in search-web/view_content.jsp, added by Julio, so I'm not sure what's the correct fix.

I cannot reproduce LPS-48485 right now, so it seems to be fixed elsewhere.

Moreover there seems to be a regression in master with resource bundles, modules are not loading portal-impl localizations (edit-x-x only works when present in the module itself).

However, having HtmlUtil.render(HtmlUtil.escape()) is a vulnerability, because it de-escapes the escaped content.

**Comment by samuelkong** [comment]
Thanks @topolik. I agree, the `HtmlUtil.escape(HtmlUtil.render()) thing is definitely not correct. The code you sent Julio looks good.

**Pull request closed without merging**
