### PR TITLE
LPS-105380 YMLStylingCheck, remove empty descriptions

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://liferay.slack.com/archives/GV90WPXCK/p1628782729006800

_Related pulls:_
7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/35214
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/35213
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/35212

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/106018

**Pull request closed without merging**
