### PR TITLE
PS-105380 BNDImportsCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/brianchandotcom/liferay-portal-ee/commit/49368a016b9efcd06c89f32839c2b0261fe31c1b

Related pulls:
7.3.x: https://github.com/hhuijser/liferay-portal-ee/pull/3244
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3245
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3246
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3247

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Closing, let me check sf failures on 7.x.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Hey @ling-alan-huang, let's set to `99.0.0` instead of `9999.0.0` (think 99 should be enough)

Go ahead and send straight to Brian (also the backports)

**Comment by ling-alan-huang** [comment]
Got it, I will resent.

**Pull request closed without merging**
