### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
ci:forward

**Comment by brianwulbern** [comment]
errors are flaky and unrelated, manually forwarding:
https://github.com/brianchandotcom/liferay-portal/pull/93027

**Pull request closed without merging**
