### PR TITLE
LPS-62414

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by hhuijser** [comment]
@daviddotzhang 

Do we have the same issue in DLFileEntryActivityInterpreter.getBody?
If not, can you explain why?

**Comment by hhuijser** [comment]
I guess it's only for MBThreads/MBMessages because those are being used by other modules?

**Comment by daviddotzhang** [comment]
@ I have not found the same use case.

but still added as the same pattern.

On Wed, Jan 27, 2016 at 11:56 AM, Hugo Huijser <notifications@github.com>
wrote:

> I guess it's only for MBThreads/MBMessages because those are being used by
> other modules?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hhuijser/liferay-portal/pull/2612#issuecomment-175377246>
> .
>



-- 
David

Jr. Engineer, Technical Support

Subscription Services

Liferay Dalian Software Co., Ltd.

**Comment by daviddotzhang** [comment]
@hhuijser 

issue can be reproduced on DLFileEntryActivityInterpreter.getBody

1: "download-file"
2: "go-to-folder"

for other places using "wrapLink", it will show the title .

**Comment by daviddotzhang** [comment]
Hi Andre,


As Julio suggested, I think you must be very experienced with this search
infrastructure. I send this to you for review.

Origin PR: https://github.com/juliocamarero/liferay-portal/pull/4288

New PR:   https://github.com/arboliveira/liferay-portal/pull/154




Thanks,
David.

On Fri, Oct 14, 2016 at 8:40 PM, Dale Shan <dale.shan@liferay.com> wrote:

> Hey David,
> Could you please resend your pull request to Andre? Julio mentioned this
> fix might effect search infrastructure.
>
> Thanks,
> Dale
>



-- 
David

Jr. Engineer, Technical Support

Subscription Services

Liferay Dalian Software Co., Ltd.

**Pull request closed without merging**
