### PR TITLE
LPS-57377

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @daledotshan 

Can you explain on the LPS why we need to upgrade c3p0?

**Comment by daledotshan** [comment]
Hey Hugo,
There is a deadlock issue in version 0.9.2.1 (refer to http://sourceforge.net/p/c3p0/bugs/117/), upgrade to version 0.9.5.1 to solve this issue.

I just explained the upgrade reason in LPS-57377 too.

Thanks

**Comment by hhuijser** [comment]
Sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/1579

**Comment by hhuijser** [comment]
Resent: https://github.com/shuyangzhou/liferay-portal/pull/1593

**Pull request closed without merging**
