### PR TITLE
LPS-127081 Turn off WhitespaceCheck for TSSourceProcessor

### PR DESCRIPTION
**Pull request by wincent**
Because TypeScript files are basically just JavaScript files with type annotations inside them, so they get formatted by Prettier as per our globs [here](https://github.com/liferay/liferay-portal/blob/ed697e67cc77/modules/npmscripts.config.js#L15-L25).

This should stop Prettier and SF fighting over the details like I saw in [liferay-frontend#874](https://github.com/liferay-frontend/liferay-portal/pull/874#issuecomment-796868724).

Note that I'm also adding ".jsx" to the list of extensions, because [those are TypeScript too](https://www.typescriptlang.org/docs/handbook/jsx.html). We don't currently have any of these in this repo, but we certainly will in the future. We have lots in [Clay](https://github.com/liferay/clay), for example, and as we migrate more bits of liferay-portal to TypeScript this extension will be cropping up more and more.

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> ❌ ci:test:sf - 0 out of 1 jobs passed in 18 minutes

`ant format-source-current-branch` wasn't enough 😀 — will add a commit to fix this presently.

**Comment by wincent** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
