### PR TITLE
LPS-93513 Poshi Script SF: Sort variable names in macros

### PR DESCRIPTION
**Pull request by ling-alan-huang**
@hhuijser,

I added additional changes to fix https://github.com/ling-alan-huang/liferay-portal/blob/50550a2c9834c8e11bb06701ab5dad2f77546815/portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/dynamicdatalists/cpdynamicdatalists/CPDynamicdatalists.testcase#L3724-L3738

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:relevant

There was an issue with test-1-9 earlier.

**Comment by ling-alan-huang** [comment]
Closing, will resolve conflicts and resend.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/3506

**Pull request closed without merging**
