### PR TITLE
 LPS-84119 Apply JavaMultiPlusConcatCheck to test files

### PR DESCRIPTION
**Pull request by ling-alan-huang**
**Issues:** https://github.com/liferay/liferay-portal/commit/1169809981b311799768bc81396e31bce4d2a776

**Related pulls:**
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/2918
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/2917

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Hi @hhuijser,

I just found that I should use:

[testIntegrationCompile project(":core:petra:petra-string") ](https://github.com/liferay/liferay-portal/commit/1169809981b311799768bc81396e31bce4d2a776#diff-dd3703b46895600777b8f090ebc23883R6)
instead of 
[compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "1.3.0"](https://github.com/hhuijser/liferay-portal-ee/pull/2917/commits/54710db536b84503c0bd561cdaed259bfa4f9b15#diff-75db9c0a650177feb63858fcf081c6b7R8) ?

I will fix that tomorrow morning, sorry for my bad.

**Comment by hhuijser** [comment]
@petershin, can you explain when we use `project(":core:petra:petra-string") ` vs `group: "com.liferay", name: "com.liferay.petra.string", version: "1.3.0"`?

**Comment by petershin** [comment]
@hhuijser - In general, `project dependencies` are used on `master`, `module dependencies` are used in the release branches (i.e. `7.x.x` branches).

**Comment by ling-alan-huang** [comment]
Thanks @petershin.

**Comment by ling-alan-huang** [comment]
Closing, this pull's already sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/76733

**Pull request closed without merging**
