### PR TITLE
LPS-84119 Add MissingGenericCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser,

The issue: https://github.com/liferay/liferay-portal/commit/a4c335d74c7d18103c066ca7c659de09194b9cb1

I removed `EnumMap` from [private static final String[] _GENERIC_CLASSES](https://github.com/hhuijser/liferay-portal/compare/master...ling-alan-huang:LPS-84119_MissingGenericCheck_20190719_01?expand=1#diff-82fc5733e2b4956258c7d609449747a8R86) ,
Reason: https://github.com/ling-alan-huang/liferay-portal/pull/84#issuecomment-512756713
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/frontend-taglib/frontend-taglib-util/src/main/java/com/liferay/frontend/taglib/util/TagResourceHandler.java:180: error: cannot infer type arguments for EnumMap<K,V>
     [exec] 		new EnumMap<>(Position.class) \{
     [exec] 		           ^
     [exec]   reason: cannot use '<>' with anonymous inner classes
     [exec]   where K,V are type-variables:
     [exec]     K extends Enum<K> declared in class EnumMap
     [exec]     V extends Object declared in class EnumMap
     [exec] 1 error

```

So the rule is only for non-parameter in `Constructor`.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
Hi @ling-alan-huang 

Couple of things:

1. The issue with `EnumMap` in `TagResourceHandler.java` can happen for any of the types that we are checking. It happens when you create an anonymous class. In a case like this, we need to specify the type inside the diamond operator.

In `TagResourceHandler.java`, the following code would compile without problems:
```
    private static final EnumMap<Position, String> _webKeysEnumMap =
        new EnumMap<Position, String>(Position.class) {
            {
                put(Position.BOTTOM, WebKeys.PAGE_BODY_BOTTOM);
                put(Position.TOP, WebKeys.PAGE_TOP);
            }
    };
```
You can see we do the same thing for example for regular lists/maps: https://github.com/liferay/liferay-portal/blob/master/modules/apps/calendar/calendar-web/src/main/java/com/liferay/calendar/web/internal/search/CalendarResourceSearch.java#L47-L61

So, no need to exclude `EnumMap`

2. Can we rename the check to `DiamondOperatorCheck`
Also, change the warning something like:
` Missing diamond operator '<>' for 'ArrayList'`

Even better would be if we can make the check smart enough to detect the anonymous class cases where we need to specify the types inside the operator and have that somehow show in the warning message.

Anyway, I am going to close this pull. You can make the changes and resend.

Thanks!

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/3671

**Pull request closed without merging**
