### PR TITLE
 LPS-84119 Sort specific keys

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to this pull request.

**Comment by hhuijser** [comment]
@ling-alan-huang, I am not a big fan of hardcoding `- in: query` in the Comparator.
Feels like we're going to run into this again in the future with some other key.
Can we do this smarter?

**Comment by ling-alan-huang** [comment]
@hhuijser,
Yes, it might be reused again in the future, “in:query” has and use the order key “name” in this case.

But in the future and in other case, we can not sure it will have and use the same key “name”.

I will think about it a little bit more.

**Comment by ling-alan-huang** [comment]
Closing, will resend.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/3492

**Pull request closed without merging**
