### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@jpince

**Comment by jpince** [comment]
@diogo can you please look at the failure in `DDMStructureLocalServiceTest.testSearchByKeywords2` in this PR and tell us if it is related to Hugo's [changes in DDM](https://github.com/hhuijser/liferay-portal/pull/5464/commits/d560ca2e82a5db2a064930fe357adfb262dd7902#diff-8ab95207e8dc8580b8a4c9b8bce0490b1382e656c06f5cedbb22f91e29f623c8)?

**Comment by jpince** [comment]
@diogocordeiro can you please look at the failure in DDMStructureLocalServiceTest.testSearchByKeywords2 in this PR and tell us if it is related to Hugo's changes in DDM?

**Comment by carolmariaabb** [comment]
> @diogocordeiro can you please look at the failure in DDMStructureLocalServiceTest.testSearchByKeywords2 in this PR and tell us if it is related to Hugo's changes in DDM?

Hi @jpince! From what I saw, it's flaky.

**Comment by jpince** [comment]
ci:test:relevant @hhuijser let's run this one again since all of the non-smoke functional tests failed.
@brianwulbern can someone in CNQA please take a quick look at this PR later today for unique failures?

**Comment by jpince** [comment]
@carolmariaabb thanks for the information. Can you or someone on the team please fix or ignore the test so it doesn't block pull requests?

**Comment by carolmariaabb** [comment]
> @carolmariaabb thanks for the information. Can you or someone on the team please fix or ignore the test so it doesn't block pull requests?

Sure!

**Comment by brianwulbern** [comment]
Stable failure is a [flaky Upgrade test failure](https://testray.liferay.com/home/-/testray/cases/1310700728)

**Comment by brianwulbern** [comment]
Stable-wise, this pull is safe to send to BChan.

**Comment by jpince** [comment]
@hhuijser you can manually forward to Brian

**Comment by hhuijser** [comment]
Thanks guys. See https://github.com/brianchandotcom/liferay-portal/pull/100994

**Pull request closed without merging**
