### PR TITLE
LPS-104679 Apply some Checkstyles to jsp_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

**Related pulls:**
master-private: no violations
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3003
7.2.x-private: no violations
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3002
7.1.x-private: no violations
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3001
7.0.x-private: https://github.com/hhuijser/liferay-portal-ee/pull/3000

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/81423

**Pull request closed without merging**
