### PR TITLE
SourceFormatter JSPSourceProcessorTest.testFormatBooleanScriptlet()

### PR DESCRIPTION
**Pull request by arboliveira**
Hi Hugo! Sending you a new JSP test - sorry I'm not sending a fix too, but I'm not sure which code convention is correct.

Local `formatSource` left my JSP file unchanged, so I went ahead with a pull request. However CI PR tester (https://github.com/arboliveira/liferay-portal/pull/253#issuecomment-295041874) tells me it should be `collapsible="&lt;%= true %>"`:

```
Exception in thread "main" com.liferay.source.formatter.SourceMismatchException: ./modules/apps/foundation/portal-search/portal-search-web/src/main/resources/META-INF/resources/type/facet/view.jsp expected:&lt;...icon" persistState="[&lt;%= true %>">
     [java] 			&lt;liferay-ui:panel collapsible="&lt;%= true %>" cssClass="search-facet" id='&lt;%= renderResponse.getNamespace() + "facetAssetEntriesPanel" %>' markupView="lexicon" persistState="&lt;%= true %>]" title="type">
     [java] 				...> but was:&lt;...icon" persistState="[true">
     [java] 			&lt;liferay-ui:panel collapsible="true" cssClass="search-facet" id='&lt;%= renderResponse.getNamespace() + "facetAssetEntriesPanel" %>' markupView="lexicon" persistState="true]" title="type">
     [java] 				...>
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.processFormattedFile(BaseSourceProcessor.java:902)
```

So I wrote the test in this commit to assert for the expected value from the failed CI PR test run. I suppose this PR is probably going to pass this test then, however when I run it locally the test goes red expecting `collapsible="true"`:

```
com.liferay.source.formatter.JSPSourceProcessorTest > testFormatBooleanScriptlet FAILED
    org.junit.ComparisonFailure: expected:<...icon" persistState="[true">
        <liferay-ui:panel collapsible="true" cssClass="search-facet" id='<%= renderResponse.getNamespace() + "facetAssetEntriesPanel" %>' markupView="lexicon" persistState="true]" title="type">> but was:<...icon" persistState="[<%= true %>">
        <liferay-ui:panel collapsible="<%= true %>" cssClass="search-facet" id='<%= renderResponse.getNamespace() + "facetAssetEntriesPanel" %>' markupView="lexicon" persistState="<%= true %>]" title="type">>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.liferay.source.formatter.BaseSourceProcessorTestCase.test(BaseSourceProcessorTestCase.java:205)
        at com.liferay.source.formatter.BaseSourceProcessorTestCase.test(BaseSourceProcessorTestCase.java:101)
        at com.liferay.source.formatter.BaseSourceProcessorTestCase.test(BaseSourceProcessorTestCase.java:80)
        at com.liferay.source.formatter.JSPSourceProcessorTest.testFormatBooleanScriptlet(JSPSourceProcessorTest.java:26)
```

I'll change my original JSP file to what CI PR tester expects, and hope `formatSource` still leaves it unchanged 😅

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
Well, that was unexpected 😃  Apparently `JSPSourceProcessorTest` prefers `collapsible="true"` under both command line and CI PR Tester, while `formatSource` will enforce `collapsible="<%= true %>` under CI only.

**Comment by hhuijser** [comment]
I got a feeling this is not working properly under JSPSourceProcessorTest as it's not properly grabbing the correct java tag classes that are needed to check if the tag is a boolean or not.
I will look into that more later. I'll leave the pull open for now.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/48578

**Pull request closed without merging**
