### PR TITLE
LPS- Checkstyle dependency update in REST Builder to avoid known vulnerability

### PR DESCRIPTION
**Pull request by javierdearcos**
Hello Hugo,

So sorry to bother you.

I'm working on this issue LPS-128311 to update the checkstyle dependency in REST Builder. 

As I'm also updating the dependency in the Java Parser module, I'm worried about affecting Service Builder and Source Formatter and there is a lot of knowledge about gradle dependencies that I don't have...

Maybe the change in the Java Parser module it is not needed with the code in the build.gradle file
```
from (configurations.compile) {
		include "checkstyle-*.jar"
	}
```
but I don't understand what this code is doing under the hood.

I have also assumed that with the change in the Java Parser dependency, a new version will be released with number 1.0.37, that I have referenced from the REST Builder build.gradle file.

Can you please check if I'm doing something incorrect.

It might not have any sense at all...

Thank you very much!

### CODE REVIEW

**Comment by hhuijser** [comment]
@javierdearcos looks alright to me, can I go ahead and forward this to Brian?

**Comment by javierdearcos** [comment]
Sure. Thank you very much for checking!

Don't know if it is needed to change in the same PR the Service Builder and Source Formatter dependencies to avoid problems with them.

If not, go ahead and forward it.

Thank you very much!

**Comment by hhuijser** [comment]
ci:forward

**Comment by javierdearcos** [comment]
I've checked the errors and the only one that it is clear for me is that I'm referencing a Java Parser version that does not exist. That is because I've updated the Portal Tools REST Builder dependency to point to a new version of Java Parser that will include the updated dependencies of checkstyle, but this version does not exist yet...

Not sure about what to do? I leave the Java Parser dependency in Portal Tools REST Builder pointing to the old version?

**Comment by hhuijser** [comment]
You'll need to do `gradlew installCache updateFileVersions` and commit the modified files with a `FAKE GRADLE CACHE` commit, which Brian will ignore.

Let me know if you have issues

**Comment by javierdearcos** [comment]
Thank you! I did it a time ago for the project-template-rest-builder but it didn't come to my mind with this case.

I'll do it right now and update the PR

**Comment by javierdearcos** [comment]
😞 I've tried to repeat the steps after a rebase but now I have failures.

I will execute an ant all and try again and update the PR tomorrow.

Sorry for all the noise

**Comment by javierdearcos** [comment]
Make all the steps again after rebasing master and seems that there are no more problems.

Follow the instructions int he slack thread. Hope to got it right and that test would catch something in case I don't.

Thank you very much for your support

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
Sorry @hhuijser. I will close the PR and forward it from the team github user to not disturb you with all the noise. I'll ping you when it is successfully forwarded to Brian.

Sorry and thank you for your support

**Pull request closed without merging**
