### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@natocesarego @cvanut flaky tests, please fix or ignore
`UpgradeDDMFormInstanceSettingsTest.testAddRequireAuthenticationSetting`
`UpgradeDDMFormInstanceSettingsTest.testEnableAutosaveSetting`
Not sure if this is related to https://issues.liferay.com/browse/LPS-83443
The same tests failed in upstream acceptance here: https://test-1-21.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=13,label_exp=!master/47554/#showFailuresLink

**Comment by jpince** [comment]
modules-unit failure needs https://github.com/Preston-Crary/liferay-portal/pull/1016/commits/000163afe819d97b5bbd4beb6df7874665792c65

@rodrigocunha flaky test? `WorkflowMetrics#ViewTopAsigneePerformance`
@manoelcyreno @david-gutierrez-mesa @xbrianlee headless/search int test flakiness? https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/392953/#showFailuresLink
@austinchiang flakiness/race condition? error in [PortalLogAssertorTest](https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6,label_exp=!master/392953//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog)
This is data for you guys, you do not need to respond directly to me about your findings.

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
resent: https://github.com/hhuijser/liferay-portal/pull/4128

**Pull request closed without merging**
