### PR TITLE
LPS-105380 XMLWorkflowDefinitionFileNameCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Hey @Preston-Crary We got a lot of `missing language key` errors, I found that you moved Language.properties [here](https://github.com/liferay/liferay-portal/commit/0afa46c6375bebf577aa08d1b609796da73a4fc1) yesterday, can you have a look at these errors? Thanks.

**Comment by Preston-Crary** [comment]
Sent a pull to fix the issue https://github.com/brianchandotcom/liferay-portal/pull/104640, thanks for bringing it to my attention!

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Pull request closed without merging**
