### PR TITLE
LPS-105380 NullAssertionInIfStatementCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Hugo,

Null check for variable should always be first before using it in if-statement.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
```

public boolean method1(List<String> list) {
	if (list.isEmpty() || (list == null)) {
		return false;
	}

	return true;
}
+--LITERAL_IF (if) 354
    +--LPAREN (() 354
    +--EXPR 354
        +--LOR (||) 354
            +--METHOD_CALL (() 354
                +--DOT (.) 354
                    +--IDENT (list) 354
                    +--IDENT (isEmpty) 354
                +--ELIST 354
                +--RPAREN ()) 354
            +--LPAREN (() 354
            +--EQUAL (==) 354
                +--IDENT (list) 354
                +--LITERAL_NULL (null) 354
            +--RPAREN ()) 354
    +--RPAREN ()) 354
    +--SLIST ({) 354
        +--LITERAL_RETURN (return) 355
            +--EXPR 355
                +--LITERAL_FALSE (false) 355
            +--SEMI (;) 355
        +--RCURLY (}) 356

```

**Comment by ling-alan-huang** [comment]
```
public boolean method2(List<String> list) {
	if ((list.size() == 3) && (list != null)) {
		return false;
	}

	return true;
}
+--LITERAL_IF (if) 362
    +--LPAREN (() 362
    +--EXPR 362
        +--LAND (&&) 362
            +--LPAREN (() 362
            +--EQUAL (==) 362
                +--METHOD_CALL (() 362
                    +--DOT (.) 362
                        +--IDENT (list) 362
                        +--IDENT (size) 362
                    +--ELIST 362
                    +--RPAREN ()) 362
                +--NUM_INT (3) 362
            +--RPAREN ()) 362
            +--LPAREN (() 362
            +--NOT_EQUAL (!=) 362
                +--IDENT (list) 362
                +--LITERAL_NULL (null) 362
            +--RPAREN ()) 362
    +--RPAREN ()) 362
    +--SLIST ({) 362
        +--LITERAL_RETURN (return) 363
            +--EXPR 363
                +--LITERAL_FALSE (false) 363
            +--SEMI (;) 363
        +--RCURLY (}) 364

```

**Comment by ling-alan-huang** [comment]
```
public boolean method3(
	List<String> nameList1, List<String> nameList2, String name) {

	if (((nameList1 != null) && (nameList2 != null) &&
		 (nameList1.size() > nameList2.size)) ||
		((nameList1.size() > 5) && name.equals("Liferay") &&
		 (nameList1 != null))) {

		return false;
	}

	return true;
}
+--LITERAL_IF (if) 372
    +--LPAREN (() 372
    +--EXPR 373
        +--LOR (||) 373
            +--LPAREN (() 372
            +--LAND (&&) 372
                +--LAND (&&) 372
                    +--LPAREN (() 372
                    +--NOT_EQUAL (!=) 372
                        +--IDENT (nameList1) 372
                        +--LITERAL_NULL (null) 372
                    +--RPAREN ()) 372
                    +--LPAREN (() 372
                    +--NOT_EQUAL (!=) 372
                        +--IDENT (nameList2) 372
                        +--LITERAL_NULL (null) 372
                    +--RPAREN ()) 372
                +--LPAREN (() 373
                +--GT (>) 373
                    +--METHOD_CALL (() 373
                        +--DOT (.) 373
                            +--IDENT (nameList1) 373
                            +--IDENT (size) 373
                        +--ELIST 373
                        +--RPAREN ()) 373
                    +--DOT (.) 373
                        +--IDENT (nameList2) 373
                        +--IDENT (size) 373
                +--RPAREN ()) 373
            +--RPAREN ()) 373
            +--LPAREN (() 374
            +--LAND (&&) 374
                +--LAND (&&) 374
                    +--LPAREN (() 374
                    +--GT (>) 374
                        +--METHOD_CALL (() 374
                            +--DOT (.) 374
                                +--IDENT (nameList1) 374
                                +--IDENT (size) 374
                            +--ELIST 374
                            +--RPAREN ()) 374
                        +--NUM_INT (5) 374
                    +--RPAREN ()) 374
                    +--METHOD_CALL (() 374
                        +--DOT (.) 374
                            +--IDENT (name) 374
                            +--IDENT (equals) 374
                        +--ELIST 374
                            +--EXPR 374
                                +--STRING_LITERAL ("Liferay") 374
                        +--RPAREN ()) 374
                +--LPAREN (() 375
                +--NOT_EQUAL (!=) 375
                    +--IDENT (nameList1) 375
                    +--LITERAL_NULL (null) 375
                +--RPAREN ()) 375
            +--RPAREN ()) 375
    +--RPAREN ()) 375
    +--SLIST ({) 375
        +--LITERAL_RETURN (return) 377
            +--EXPR 377
                +--LITERAL_FALSE (false) 377
            +--SEMI (;) 377
        +--RCURLY (}) 378
```

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
