### PR TITLE
LPS-101814 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by gamerson**
cc @petershin

### CODE REVIEW

**Comment by gamerson** [comment]
hey @hhuijser  please ask BChan to publish project-templates.

**Comment by gamerson** [comment]
thanks

**Comment by gamerson** [comment]
all tests passed here: https://github.com/gamerson/liferay-portal/pull/348#issuecomment-532843584

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/78584

**Pull request closed without merging**
