### PR TITLE
LPS-84119 Apply to *.wsdl files

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures 3~71: https://github.com/hhuijser/liferay-portal-ee/pull/2956

**Comment by hhuijser** [comment]
Think I rather suppress those files in `third-party` from being formatted

**Comment by ling-alan-huang** [comment]
Closing, I will resend.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/3759

**Pull request closed without merging**
