### PR TITLE
LPS-84119 Format comment for Poshi Script

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
@ling-alan-huang, this one is not correct: https://github.com/hhuijser/liferay-portal/pull/4113/files#diff-fc1c7403c5f5a4953db8d15ea886d63cL2074

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4122

**Pull request closed without merging**
