### PR TITLE
Lps 61383

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @mtambara 

Just curious... was this causing issues for you? Seems like the behavior should be the same with or without HEAD?

http://www.git-scm.com/docs/git-diff: *If <commit> on one side is omitted, it will have the same effect as using HEAD instead.*

**Comment by mtambara** [comment]
@hhuijser `current-branch` and `latest-author` were generating the wrong file names when files were renamed. Specifically, it tried to format the deleted files. 

The documentation is somewhat ambiguous about which commit it thinks is omitted (\<commitId> [HEAD] or [HEAD] \<commitId>), but from what I can tell it assumes HEAD should be the second commit.  

I've tested this locally, `git diff HEAD HEAD~1` and `git HEAD~1` are inverses of each other, with the latter being the correct diff.

**Comment by hhuijser** [comment]
@mtambara 

Sounds good. Thanks for the explanation!

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/34356

**Pull request closed without merging**
