### PR TITLE
LPS-105380 Add dxp path for JavaServiceObjectCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by jpince** [comment]
@inacionery it's a bit discouraging for me when I purposefully ignored this test to help Hugo... and then I see it failing again on Hugo's pull. https://issues.liferay.com/browse/LPS-112339. Please ignore if you can't fix it today.
cc/ @rodrigocunhaa

**Comment by rodrigocunhaa** [comment]
@jpince , this test was supposed to be fixed, but it still failing. I ignored it again https://github.com/brianchandotcom/liferay-portal/pull/88982. Sorry for the inconvenience.

**Comment by jpince** [comment]
@rodrigocunhaa thank you!

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
