### PR TITLE
LPS-56735

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Information from Hai:

When staging site exist inherit relation, we shouldn't allow user to disable(delete) the parentSite staging because it will break inherit relation. And it should be same as we don't allow to delete parentSite when this parentSite includes childSite.

Case1:
When exist below case "parentSite->childSite", if we try to delete parentSite, the parentSite won't be deleted and one warning message will be displayed "You cannot delete sites that have subsites." in UI

Case2:
When exist below case "parentSite(enable parentSite staging)->childSite", if we enable childSite staging, for staging site, it will keep inherit relation. When disable parentSite staging, the issue will occur and you will find childSite still keep parentSite's inherit relation. This is wrong as LPS-56735.

In LPS-42169, we added the feature (commit:Fix parentGroupId when enabling staging) when enable childSite staging, if its parentSite also enables staging, it will keep inherit relation in staging site. So if we keep the inherit relation, we shouldn't disable parentSite staging before disable childSite staging. Case 2 should keep same behavior as Case1.

In addition, if we use groupPersistence.countByC_P() in GroupLocalServiceImpl.deleteGroup(), it will cause LPS-27781 issue. For portlet scope group, it will make childSite for the current site.

Please help review.

**Comment by hhuijser** [comment]
So, for staging groups, groupPersistence.countByC_P_S == 0, but hasChildStagingGroup(group) is true?

How come?
What is different about what happens in the method hasChildStagingGroup compared to groupPersistence.countByC_P_S?
Checking for regular site is different from checking for site?

**Comment by yuhai** [comment]
Hi Hugo,

"for staging groups, groupPersistence.countByC_P_S == 0, but hasChildStagingGroup(group) is true?"

Yes. Please refer to the below case:
1. Create one inherit relation: ParentSite->ChildSite
2. Enable ParentSite staging(groupId=10000, site=0 (because staging group's site ==0)).
3. Enable ChildSite staging, due to the fix (LPS-42169, we added the feature (commit:Fix parentGroupId when enabling staging) when enable childSite staging), ChildSite staging will be groupId 10008, parentGroupId:10000, site=0.

When disable parentSite staging(this means delete parentSite staging group(groupId:10000)), for groupPersistence.countByC_P_S(companyId, 10000, true) ==0 because staging group's site==0.

**hasChildStagingGroup will return "true" when disable parentSite staging as the above case.**

"Checking for regular site is different from checking for site?"
Sorry, I might understand the question wrong. In here, childGroup.isRegularSite() will exclude the below case:

1. Create one site "SiteA", and then enable SiteA staging "SiteA staging" (staging groupId:10010).
2. in "SiteA staging", add one layout testPage.
3. Go to testPage, place one MB portlet.
4. Click on configuration of the MB portlet --> Scopes --> Current page(testPage). It will create one scope group in group_ table. for example, groupId:10020, parentGroupId:10010, site:0, classNameId:layout. This also create one inherit relation (CurrentSiteGroup(parent)->layoutScopeGroup(child)).**So childGroup.isRegularSite() will exclude the layout scope group so that we can disable "SiteA staging".**

Please let me know if my explanation is not clear.

Thanks,
Hai

**Comment by hhuijser** [comment]
Sent to Mate for further review: https://github.com/matethurzo/liferay-portal/pull/1135

**Pull request closed without merging**
