### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@yichenroy weird CI error? this ran last night, before this morning's git issues.
```
curl: (6) Could not resolve host: mirrors.lax.liferay.com; Unknown error
Build step 'Execute shell' marked build as failure
Recording test results
ERROR: Step ???Publish JUnit test result report??? failed: No test report files were found. Configuration error?
```

**Comment by jpince** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
@jpince looks like it was a network issue:
`curl: (6) Could not resolve host: mirrors.lax.liferay.com; Unknown error`

We'll keep an eye out on other builds, but for now the re-run should do.

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
