### PR TITLE
LPS-121804_Python_20201015

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,
I tested your changes, it's good.
I fixed ticket number and sent back to you.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@hhuijser Btw, Peter said that its easier to add it to each subrepo rather than bundling it inside SF.

> Peter Shin  1:20 AM
> it might be worthwhile to ask hugo about this too.  he added checkstyle inside sf, so it may be possible to follow that same pattern

Looks like we have only one subrepo that contains Python files, if this pull is OK to you and Brain, we can just copy the logic to the gradle in that subrepo.

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
