### PR TITLE
LPS-84119 Ignore _checkExceptionVariableName for catch statement

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser,

See: https://github.com/liferay/com-liferay-osb-faro-private/pull/1688#discussion_r301818019

Thanks.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/75542

**Pull request closed without merging**
