### PR TITLE
LPS-114570 BaseTagAttributesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://issues.liferay.com/browse/LPS-114570

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:bundle

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Closing this one because of conflicts... I'll take your commit and resend

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4343

@ling-alan-huang Can you take care of the backports after this in?

**Comment by ling-alan-huang** [comment]
@hhuijser, got it.

**Pull request closed without merging**
