### PR TITLE
LPS-129342 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by hhuijser** [comment]
Looks good to me

**Comment by hhuijser** [comment]
ci:forward

**Comment by lawrence-lee** [comment]
fixed SF issues

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
i'm going to fix this and resend

**Pull request closed without merging**
