### PR TITLE
Lps 58564

### PR DESCRIPTION
**Pull request by bejondshao**
Hi Hugo,

Dale helps me find the cause. It's because of portal-wab-extender only includes GetterUtil but other classes. So all the modules which import portal-wab-extender would throw this exception.

### CODE REVIEW

**Comment by hhuijser** [comment]
We only need to add StringUtil? Let's do that instead of adding entire portal.kernel.util

**Comment by bejondshao** [comment]
We should add StringUtil. But StringUtil imports other classes which are in
kernel util, further more, imported classes need to import more classes
which are in kernel util. It will lead more than tens of classes. So I
import the kernel.util package instead.



Bejond Shao

Jr. Engineer, Technical Support

Subscription Services

Liferay Dalian Software Co., Ltd.

**Comment by hhuijser** [comment]
How come bnd.bnd in tld-formatter has StringUtil and for the rest only 8 other imports from kernel/util?

Let's keep the same pattern that lots of other modules are using and add the imports, if it's not crazy many...

**Comment by hhuijser** [comment]
Btw. just to explain why I am suggesting this.
We'd want to keep the modules as "light" as possible, therefore we won't add a lot of additional classes if we don't have to.

**Comment by bejondshao** [comment]
Hi Hugo,

Thanks for the example. Since StringUtil is treated as include-resource in
tld-formatter, I can do the same as tld-formatter.

Bejond Shao

Jr. Engineer, Technical Support

Subscription Services

Liferay Dalian Software Co., Ltd.

**Pull request closed without merging**
