### PR TITLE
LPS-85042 When setting to "Display Scheduler Only", multiple <div> tags are added when moving to a page that has a Calendar portlet

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by ling-alan-huang** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Adam for further review: https://github.com/brandizzi/liferay-portal/pull/564

**Pull request closed without merging**
