### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@alexcandidos @xbrianlee consistent failures
`AppBuilder#DeleteFormViewFieldFromObject`
`PermissionCheckerTest.testHasPermissionWithMissingResourcePermissions`

**Comment by alexcandidos** [comment]
hey @jpince , I just removed some tests from relevant: https://github.com/brianchandotcom/liferay-portal/pull/88966

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@xbrianlee looks like we need to ignore more tests in WorkflowTaskPermissionCheckerTest, I can send in ignores

**Comment by brianwulbern** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/89001

**Comment by brianwulbern** [comment]
The `lpkg-controller-jdk8` error: 
```NoSuchResourceActionException: com.liferay.polls#PERMISSIONS```
was filed here https://issues.liferay.com/browse/LPS-107533, but it was a flaky /difficult to reproduce issue

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
