### PR TITLE
Lps 58564

### PR DESCRIPTION
**Pull request by bejondshao**
Hi Hugo,

I fetch latest master and repush this commit. Let's see if the errors still there.

### CODE REVIEW

**Comment by hhuijser** [comment]
@bejondshao 

Did you figure out what the issue was or did you run the test that failed before on this commit?
If not, I'd be surprised that it's not breaking the test again this time as it seemed that the broken test was caused by this...

**Comment by bejondshao** [comment]
Hi Hugo,

I didn't figure out the reason. I looked through the errors I don't think it's related with my change. Because the only potential exception would be NPE. But it's the same potential for str.trim(). So I did a rebase. If it works, it seems the test errors has some other related components. By the way, I've merged Dale and your commits.

**Comment by hhuijser** [comment]
@bejondshao 

Let's run the test to be sure first.

In the pr that failed there were no other commits than ours (https://github.com/brianchandotcom/liferay-portal/pull/30248) and it didn't seem trunk was giving any errors at that time...

I looked at the stack-trace as well and although it seemed unrelated, I couldn't guarantee it (we COULD get a NPE as a result of a different return value for the trim method), so let's be safe and test ourselves before sending the exact thing back to Brian without testing...

**Comment by hhuijser** [comment]
Please resend after we figure out how to auto-test our pull requests...

**Pull request closed without merging**
