### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:bundle

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@rodrigocunhaa this error fails `PortalLogAssertorTest.testScanXMLLog` in all 3 runs, and I don't think Hugo's change would cause this. Is this a known issue in upstream?
```
    [junit] 04:32:36,520 INFO  [com.liferay.portal.workflow.kaleo.test-executor-thread][CompanyIndexFactory:51] 
    [junit] 04:33:03,630 WARN  [com.liferay.portal.workflow.kaleo.test-executor-thread][ProxyMessageListener:88] java.lang.RuntimeException: org.elasticsearch.index.IndexNotFoundException: [liferay-50615] IndexNotFoundException[no such index]
    [junit] java.lang.RuntimeException: org.elasticsearch.index.IndexNotFoundException: [liferay-50615] IndexNotFoundException[no such index]
    [junit] 	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:182)
    [junit] 	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteWriteIndex(IndexNameExpressionResolver.java:282)
```
cc/ @xbrianlee

**Comment by rodrigocunhaa** [comment]
Hi @jpince, I talked to Inácio about this error and he told me that it's actually not related to the Workflow, but Search.

**Comment by xbrianlee** [comment]
I mentioned this to my team and we decided it really was a Search issue even though it seems to only affect `com.liferay.portal.workflow.kaleo.test`. We're going to prioritize a fix for this issue.
https://liferay.slack.com/archives/CLBEAPQ5D/p1589221380126200?thread_ts=1589220600.125900&cid=CLBEAPQ5D

I would recommend bypassing `ci:forward` for now if all others tests pass. Sorry for the inconvenience.

**Pull request closed without merging**
