### PR TITLE
[TS] LPS-86545 doAsUserId parameter removed from URL when links to pages belonging to other sites of the portal

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

My second comment is a fix to change the action from _redirect_ to _forward_ If a URL starts with portalURL like http://localhost:8008/web/guest, so that we can preserve the doAsUserId in request when we click it.

Please have a look at this portion of code:
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/FriendlyURLServlet.java#L149-L167

Thanks,
Alan

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by ling-alan-huang** [comment]
cc/ @samuelkong

**Comment by ling-alan-huang** [comment]
It seems the failures are related to my changes, I will check it tomorrow.

**Comment by hhuijser** [comment]
@ling-alan-huang, feels like we'd need to apply here as well?
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/FriendlyURLServlet.java#L392-L396

**Comment by hhuijser** [comment]
I'll close this now, please resend

**Pull request closed without merging**
