### PR TITLE
LPS-69271

### PR DESCRIPTION
**Pull request by dustinryerson**
Hey Hugo,

Here are the changes you requested.

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Thanks @dustinryerson!
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/45105

**Comment by hhuijser** [comment]
Hey @dustinryerson 

Can you resend?
It fails because it touches journal (thought I could fix that with an extra revert commit, but doesn't work like that.)
Please send another pull straight to Brian.

Thanks!

**Comment by hhuijser** [comment]
@dustinryerson make sure you run it after this one gets in: https://github.com/brianchandotcom/liferay-portal/pull/45107

**Comment by dustinryerson** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/45129

**Pull request closed without merging**
