### PR TITLE
LPS-105380_PropertiesBuildIncludeDirsCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://liferay.slack.com/archives/C1SJ64S9X/p1599004119001100

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
