### PR TITLE
LPS-84119 Fix regex for allowing the hyphen(-) in the filename

### PR DESCRIPTION
**Pull request by ling-alan-huang**
**Regex matches:**
`/opt/dev/projects/github/liferay-portal-7.2.x-private/test.cloud-10-0-19-122.lax.liferay.com.properties`
**Regex matches:**
`/opt/dev/projects/github/liferay-portal-7.2.x-private/test.cloud-10-0-110-111.lax.liferay.com.properties`
**Regex matches:**
`/opt/dev/projects/github/liferay-portal-7.2.x/test.case.method.names.properties`

_**Regex doesn't match:**_
`/opt/dev/projects/github/liferay-portal-7.2.x-private/test.cloud-10-0-110-111.lax.liferay.com..properties`
_**Regex doesn't match:**_
`/opt/dev/projects/github/liferay-portal-7.2.x/source-formatter.properties`

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
@hhuijser,
I found that `ci:test:relevant` failures are caused by this commit.
https://github.com/liferay/liferay-portal/commit/e0e0c5ca4d6abe933ab392d9c907e8ea2d080e4c
But I don't know why this commit causes the failures.

I also ran `../../../gradlew test TestIntegration` from `master/liferay-portal/modules/util/source-formatter`, the failures are the same.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/75233

**Pull request closed without merging**
