### PR TITLE
LPS-52910

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Hugo,

The issue is that the Related Assets portlet render weight is 1, since it waits for the Asset Publisher portlet to load first. Since the Nested Portlet render weight is 50, it is being rendered before the Related Assets portlet.

Let me know if you have any questions. Thanks.

**Comment by hhuijser** [comment]
Where exactly does that value "1" come from?
I see either "50" or "0" in all other files that have the property "com.liferay.portlet.render-weight"...

**Comment by jonathanmccann** [comment]
It is taken from https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/WEB-INF/liferay-portlet.xml#L1515 where the Related Asset portlet's render weight is set to 1. If we set the Nested Portlet's render weight to 0, then it would be rendered serially, and this issue might still occur.

**Comment by hhuijser** [comment]
Sent to Julio for further review: https://github.com/juliocamarero/liferay-portal/pull/3214

**Pull request closed without merging**
