### PR TITLE
LPS-56577

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Hugo,
We can not test this fix in trunk since trunk staging function broken, we have tested it in ee-6.2.x it works well.

**Comment by daledotshan** [comment]
Please send this pull request to Mate

**Comment by hhuijser** [comment]
Hey @zxdgoal 

A few suggestions:

1. In LayoutCache, let's create two maps instead of having the two methods use the same one (a bit faster to split the map, if the maps is very big).
2. Let's rename the existing method getRole to getRoleByName since we have two getRoleXX methods now.

**Comment by zxdgoal** [comment]
https://github.com/hhuijser/liferay-portal/pull/2396

**Pull request closed without merging**
