### PR TITLE
LPS-84119 rename

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/29728ff20169badc275ed9df0d95f3a5738f9ee8

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test doesn't work today?

**Comment by ling-alan-huang** [comment]
Too many changes, let's wait for ci:test.

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/85858

**Pull request closed without merging**
