### PR TITLE
LPS-84119 Format comment for Poshi Script

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant flaky test https://issues.liferay.com/browse/LPS-110417

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4126

**Pull request closed without merging**
