### PR TITLE
LPS-105380 BaseEmptyLinesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

_Issue:_ https://github.com/liferay/liferay-portal/commit/e9fddcb59640bd94f6dee1a66577e71c7c273eda

_Related pulls:_
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3181
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3182
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3183

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
