### PR TITLE
[TS] LPS-74083

### PR DESCRIPTION
**Pull request by yuhai**
Hi Hugo,

Please refer to the below case:

DXP site: exist one page "testPage",  http://localhost:8080/web/guest/testPage
Export **Site1**: create one web content, its content includes: 
`<p><a href="http://localhost:8080/web/guest/testPage">invoke testPage from DXP site</a></p>`
Import Target **Site2**:

When we export, guest will be replaced with DATA_HANDLER_GROUP_FRIENDLY_URL.
When import this lar, it will be replaced with Import Target Site2 group, Please refer to 
 https://github.com/yuhai/liferay-portal/blob/c6e8030ca5e11f7408925020169adb77c8ebf9ef/modules/apps/web-experience/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/content/processor/DefaultTextExportImportContentProcessor.java#L1009-L1010. Its content will be
`<p><a href="http://localhost:8080/web/site2/testPage">invoke testPage from DXP site</a></p>`. 
Please note **guest** is replaced with **site2**, this is wrong. 

So the fix is when exportLayoutReferences's group (DXP site) is not current group(group:Site1), we should keep its group. Otherwise, when import it to targetGroup (group: Site2), it will be replaced with targetGroup(Site2).

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
Other pull request also encountered the error. Please refer to https://github.com/Robert-Frampton/liferay-portal/pull/405#issuecomment-322834594

**Comment by yuhai** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to mbowerman for review: https://github.com/mbowerman/liferay-portal/pull/40

**Pull request closed without merging**
