### PR TITLE
LPS-84119 Fix CSSWhitespaceCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Issue: https://github.com/brianchandotcom/liferay-portal/pull/67706/commits/bb60c6b30a505e5437e628f05c6f67b73fdcbd62

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/67868

**Pull request closed without merging**
