### PR TITLE
LPS-133689 Multi-value PortletRequest parameters contain null instead…

### PR DESCRIPTION
**Pull request by ngriffin7a**
… of an empty string

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by ngriffin7a** [comment]
@hhuijser Same with this one -- I don't think that the failure is related to this PR. I'd be much obliged if you could take a look. Thanks!

**Comment by hhuijser** [comment]
Sent to Shuyang: https://github.com/shuyangzhou/liferay-portal/pull/10065

**Comment by ngriffin7a** [comment]
@hhuijser Thanks!

**Pull request closed without merging**
