### PR TITLE
LPS-60832:While adding page, titles should be validated irrespective of HEAD

### PR DESCRIPTION
**Pull request by mosoni**
While adding wiki page validation was based on HEAD = true , in this case Head remains false because its in pending status and doesn't validate it. So when it tries to add same title in DB it throws an exception. therefore i have made changes in validation , so that it can check all the available titles irrespective of HEAD. proper validation message has been added as well.

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
Hey @mosoni 

We're also using the method isUsedTitle in the method renamePage (line 1770). Do we need to change the logic here as well?

**Comment by mosoni** [comment]
Hi @hhuijser,

I checked that as well and found that below logic is there to check duplicate page
	
       if (StringUtil.equalsIgnoreCase(title, newTitle)) {
			throw new DuplicatePageException(newTitle);
	}
So, i think we don't have to add new logic to this method.
On the other hand, i thought to add the logic while updating the page, therefore i realized that while updating we do not allow user to change the title from UI

Thanks,
Mohit

**Comment by mosoni** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Sergio for review: https://github.com/sergiogonzalez/liferay-portal/pull/2779

**Pull request closed without merging**
