### PR TITLE
LPS-84119 Sort properties alphabetically in *.yaml

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@hhuijser ,
Does `ci:test:sf` check private modules on this pull?

**Comment by hhuijser** [comment]
> @hhuijser ,
> Does `ci:test:sf` check private modules on this pull?

Yes, you can ignore that here as long as you make sure you also fix in master-private

**Comment by hhuijser** [comment]
@ling-alan-huang conflicting files again? Resend?

**Comment by ling-alan-huang** [comment]
Closing, will resend.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/3478

**Pull request closed without merging**
