### PR TITLE
LPS-114565

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
similar failures as https://github.com/cgoncas/liferay-portal/pull/510, please speak with @liulukiwi before retesting. You can probably cherry-pick the test ignore/fix and retest, or wait until after it's merged.

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@tim-cao @liulukiwi please check consistent `ContentPages#ViewRestrictionVisualFeedbackWhenDragSectionCardOverColumnOfRow` failure

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
