### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@hhuijser SB failure looks related: `username` to `userName` 
```
     [echo] --- a/portal-kernel/src/com/liferay/portal/kernel/service/UserLocalService.java
     [echo] +++ b/portal-kernel/src/com/liferay/portal/kernel/service/UserLocalService.java
     [echo] @@ -469,7 +469,7 @@ public interface UserLocalService
     [echo]  	 */
     [echo]  	@Transactional(propagation = Propagation.SUPPORTS)
     [echo]  	public long authenticateForDigest(
     [echo] -			long companyId, String username, String realm, String nonce,
     [echo] +			long companyId, String userName, String realm, String nonce,
     [echo]  			String method, String uri, String response)
     [echo]  		throws PortalException;
     [echo]  
     [echo] diff --git a/portal-kernel/src/com/liferay/portal/kernel/service/UserLocalServiceUtil.java b/portal-kernel/src/com/liferay/portal/kernel/service/UserLocalServiceUtil.java
     [echo] index b4e4dfc15bc4..7ebaa758efb5 100644
     [echo] --- a/portal-kernel/src/com/liferay/portal/kernel/service/UserLocalServiceUtil.java
     [echo] +++ b/portal-kernel/src/com/liferay/portal/kernel/service/UserLocalServiceUtil.java
     [echo] @@ -558,12 +558,12 @@ public class UserLocalServiceUtil {
     [echo]  	 <code>0</code> otherwise
     [echo]  	 */
     [echo]  	public static long authenticateForDigest(
     [echo] -			long companyId, String username, String realm, String nonce,
     [echo] +			long companyId, String userName, String realm, String nonce,
     [echo]  			String method, String uri, String response)
     [echo]  		throws com.liferay.portal.kernel.exception.PortalException {
     [echo]  
     [echo]  		return getService().authenticateForDigest(
     [echo] -			companyId, username, realm, nonce, method, uri, response);
     [echo] +			companyId, userName, realm, nonce, method, uri, response);
     [echo]  	}
     [echo]  
     [echo]  	/**
     [echo] diff --git a/portal-kernel/src/com/liferay/portal/kernel/service/UserLocalServiceWrapper.java b/portal-kernel/src/com/liferay/portal/kernel/service/UserLocalServiceWrapper.java
     [echo] index 51f3e5699c56..c50df7958ed5 100644
     [echo] --- a/portal-kernel/src/com/liferay/portal/kernel/service/UserLocalServiceWrapper.java
     [echo] +++ b/portal-kernel/src/com/liferay/portal/kernel/service/UserLocalServiceWrapper.java
     [echo] @@ -564,12 +564,12 @@ public class UserLocalServiceWrapper
     [echo]  	 */
     [echo]  	@Override
     [echo]  	public long authenticateForDigest(
     [echo] -			long companyId, String username, String realm, String nonce,
     [echo] +			long companyId, String userName, String realm, String nonce,
     [echo]  			String method, String uri, String response)
     [echo]  		throws com.liferay.portal.kernel.exception.PortalException {
     [echo]  
     [echo]  		return _userLocalService.authenticateForDigest(
     [echo] -			companyId, username, realm, nonce, method, uri, response);
     [echo] +			companyId, userName, realm, nonce, method, uri, response);
     [echo]  	}
     [echo]  
     [echo]  	/**
```

**Pull request closed without merging**
