### PR TITLE
LPS-53975

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
detailed information see https://issues.liferay.com/browse/LPS-53975

**Comment by hhuijser** [comment]
Sent to Marcellus for further review: https://github.com/marcellustavares/liferay-portal/pull/428

**Comment by zxdgoal** [comment]
Hey Hugo 

I have turned off the annoying reformat on pasting.

Sorry for that.

**Comment by hhuijser** [comment]
Sent new pull to Marcellus: https://github.com/marcellustavares/liferay-portal/pull/429

**Comment by zxdgoal** [comment]
Thanks

**Pull request closed without merging**
