### PR TITLE
LPS-105380 JSP inline

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

1.

Fix regex for https://github.com/liferay/liferay-portal/commit/5903c364b3b0a6c58939d603ad9888871808de00#diff-4d0c5ffabc7d2c9b7b553c3debb791b7L150
I want to filter out **variable + (**, like: `onChangeTitle(eve`,
because the variable and the method have the same name.

2.

Fix `portal-imp` is for edge case: https://github.com/liferay/liferay-portal/commit/5903c364b3b0a6c58939d603ad9888871808de00#diff-4d0c5ffabc7d2c9b7b553c3debb791b7L153
**\\"** doesn't mean we are inside quote: `placeholder="<%= LanguageUtil.get(request, "title") + StringPool.BLANK + \" *\" %>"`

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Rebase and retest.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Hey @ling-alan-huang think that these changes are not needed after this commit: https://github.com/liferay/liferay-portal/commit/cd2737729ffb2015dcf03e7c52e6487d11413ab9

Can you double check?

**Comment by ling-alan-huang** [comment]
@hhuijser, I will check it tomorrow.

**Comment by ling-alan-huang** [comment]
@hhuijser, you are right. I removed unnecessary commit and resent: https://github.com/hhuijser/liferay-portal/pull/4144

**Pull request closed without merging**
