### PR TITLE
LPS-84119 checkstyle chaining

### PR DESCRIPTION
**Pull request by ling-alan-huang**
**Issues:**
https://github.com/liferay/liferay-portal/commit/39366ceea6dad0006230054352c72af59d4c1660
https://github.com/liferay/liferay-portal/commit/ad3024d5a946881b9ae56c80a76336a8ad26b800

**Skip checking these lines:**
https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-vulcan/portal-vulcan-impl/src/main/java/com/liferay/portal/vulcan/internal/param/converter/DateParamConverter.java#L45

https://github.com/liferay/liferay-portal/blob/master/modules/core/petra/petra-reflect/src/test/java/com/liferay/petra/reflect/ObjectGraphUtilTest.java#L116

https://github.com/liferay/liferay-portal/blob/master/modules/test/poshi-runner/poshi-runner/src/main/java/com/liferay/poshi/runner/selenium/BaseWebDriverImpl.java#L1264

**Added allowedClassNames for this lines:**
https://github.com/liferay/liferay-portal/blob/master/util-java/src/com/liferay/util/HTMLParser.java#L33

https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-test-util/src/main/java/com/liferay/exportimport/test/util/internal/exportimport/staged/model/repository/DummyFolderStagedModelRepository.java#L87

https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-test-util/src/main/java/com/liferay/exportimport/test/util/internal/exportimport/staged/model/repository/DummyStagedModelRepository.java#L80

https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-expression/src/main/java/com/liferay/dynamic/data/mapping/expression/internal/DDMExpressionEvaluatorVisitor.java#L224

https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal/portal-upgrade-test/src/testIntegration/java/com/liferay/portal/upgrade/v7_0_0/test/UpgradeWorkflowTest.java#L40

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang, I think a better way to do this is to do something similar to what we do for `TokenTypes.TYPECASE` (so, you'd add `TokenTypes.LITERAL_NEW` to `getDefaultTokens` and add a new method to check that one)

I went over the cases you mentioned with my comments in _cursive_:

**Skip checking these lines**:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-vulcan/portal-vulcan-impl/src/main/java/com/liferay/portal/vulcan/internal/param/converter/DateParamConverter.java#L45
_What's the problem with creating a variable `simpleDateFormat`?_

https://github.com/liferay/liferay-portal/blob/master/modules/core/petra/petra-reflect/src/test/java/com/liferay/petra/reflect/ObjectGraphUtilTest.java#L116
_What's the problem with creating a variable `linkedType1` for?_

https://github.com/liferay/liferay-portal/blob/master/modules/test/poshi-runner/poshi-runner/src/main/java/com/liferay/poshi/runner/selenium/BaseWebDriverImpl.java#L1264
_Same here... can't we create a var for that whole class and do a `callable._init(this)`?_

**Added allowedClassNames for this lines:**
https://github.com/liferay/liferay-portal/blob/master/util-java/src/com/liferay/util/HTMLParser.java#L33

https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-test-util/src/main/java/com/liferay/exportimport/test/util/internal/exportimport/staged/model/repository/DummyFolderStagedModelRepository.java#L87
_Why? we can't create variable `defaultParser`?_

https://github.com/liferay/liferay-portal/blob/master/modules/apps/export-import/export-import-test-util/src/main/java/com/liferay/exportimport/test/util/internal/exportimport/staged/model/repository/DummyStagedModelRepository.java#L80
_Why? we can't create variable `dummy`? If we do, rename to `dummy1` and `dummy2`?_

https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-expression/src/main/java/com/liferay/dynamic/data/mapping/expression/internal/DDMExpressionEvaluatorVisitor.java#L224
_Instead of excluding `Object`, let's add logic to exclude cases with array values_

https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal/portal-upgrade-test/src/testIntegration/java/com/liferay/portal/upgrade/v7_0_0/test/UpgradeWorkflowTest.java#L40
_Why? we can't create variable `upgradeWorkflow`?_

**Comment by hhuijser** [comment]
Also, the cases in `DLOpenerGoogleDriveManager.java` should be allowed (ending with `Builder`)

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/4331

**Pull request closed without merging**
