### PR TITLE
LPS-52733

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
This fix refer to the fix on https://issues.liferay.com/browse/LPS-37352

Note:
For the property journal.char.blacklist, we copy all the characters from the field INVALID_CHARACTERS of class AssetUtil except following character CharPool.NEW_LINE  CharPool.RETURN CharPool.COMMA
we use comma to split character, so we can not use it in property journal.char.blacklist anymore, for the character CharPool.NEW_LINE and CharPool.RETURN we can not type them

**Comment by daledotshan** [comment]
This fix refer to https://issues.liferay.com/browse/LPS-52733
For the property journal.char.blacklist=&,\',@,\\,],},:,=,>,/,<,[,{,%,|,+,#,`,?,\",;,*,~, we copy all the characters from field INVALID_CHARACTERS of class AssetUtil class except character CharPool.COMMA, CharPool.NEW_LINE, CharPool.RETURN

1. we remove comma because we use comma to split string
2. seems user can not type a folder name include CharPool.NEW_LINE and CharPool.RETURN through UI (even through api directly) so we remove them.

**Comment by hhuijser** [comment]
Hey David

Is this one urgent? Let's talk about this one on Thursday...

**Comment by daviddotzhang** [comment]
Thanks hhuijser,

it,s  not a urgent one,let,s check tomorrow .

**Comment by hhuijser** [comment]
Sent to Eudaldo for further review: https://github.com/ealonso/liferay-portal/pull/310

**Pull request closed without merging**
