### PR TITLE
LPS-104679

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@hhuijser @ling-alan-huang LPS-99991 https://github.com/brianchandotcom/liferay-portal/compare/04f3b3358d...6454c63328#diff-a907146bb9d085f2e3d614f3f70e654fR70

I pushed your SF commit to BChan's origin, feel free to do the same in the future. https://github.com/brianchandotcom/liferay-portal/commit/6c0971a3144d5338f53180be96f4220ac155f718

**Comment by ling-alan-huang** [comment]
ci:close

**Comment by ling-alan-huang** [comment]
SF and resent: https://github.com/hhuijser/liferay-portal/pull/4171

**Pull request closed without merging**
