### PR TITLE
 LPS-84119 Apply JavaMultiPlusConcatCheck to test files

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

**Issue:** https://github.com/liferay/liferay-portal/commit/1169809981b311799768bc81396e31bce4d2a776

**Related pulls:**
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/2916
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/2915

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
Hey @ling-alan-huang 
For these, it's nicer to do `StringBundler.concat` calls instead of creating new instances of `StringBundler`
I know this was a lot of manual work, but let's do this well :(

**Comment by ling-alan-huang** [comment]
Got it, I will resend.

**Pull request closed without merging**
