### PR TITLE
LPS-93507 Poshi Script SF: Braces that are in the wrong line

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser.

I removed your this commit: https://github.com/kenjiheigel/liferay-portal/pull/498/commits/2b9ab38ffd7e7e3cf75a899f9288ebc7ab63796a
and added the last commit to change the testcase

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF test results see: https://github.com/ling-alan-huang/liferay-portal/pull/76#issuecomment-503409981

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Kenji for review: https://github.com/kenjiheigel/liferay-portal/pull/499

**Pull request closed without merging**
