### PR TITLE
LPS-54901

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @daledotshan @daviddotzhang 

I see in DLFolderLocalServiceImpl that there are two ways of getting an InvalidFolderException.
- Move folder into iself (line 1406-1410)
- Move folder into one of its children (line 1417-1422)

Can we also reproduce the bug for the second scenario?

We pass a messageString to the InvalidFolderException, so we can check that at least in the jsp?

**Comment by daledotshan** [comment]
yes, check error message in jsp should more safe, in case we print wrong
notification message

**Comment by daviddotzhang** [comment]
scenario2:Move folder into one of its children (line 1417-1422)

can,t be reproduced, since the children folder won,t appear in the list when we do that.

**Comment by hhuijser** [comment]
Okay, thanks guys!

**Comment by hhuijser** [comment]
Sent back to David to test: https://github.com/daviddotzhang/liferay-portal/pull/5

**Comment by hhuijser** [comment]
Sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/2115

**Pull request closed without merging**
