### PR TITLE
LPS-62517

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by blzaugg** [comment]
Thanks for the cc.

**Comment by hhuijser** [comment]
@zxdgoal 

Do we need this in PortletResponseUtil.setHeaders  as well?

**Comment by zxdgoal** [comment]
PortletResponseUtil.setHeaders is only used by PortletResponseUtil.sendFile, which are only used by tow methods https://github.com/daledotshan/liferay-portal/blob/2d3a3e55301b6f3e73e8a5054c98e03d245778bd/modules/apps/configuration-admin/configuration-admin-web/src/main/java/com/liferay/configuration/admin/web/portlet/action/ExportConfigurationMVCResourceCommand.java#L147-L150 and https://github.com/daledotshan/liferay-portal/blob/2d3a3e55301b6f3e73e8a5054c98e03d245778bd/portal-service/src/com/liferay/portal/kernel/portlet/bridges/mvc/BaseRSSMVCResourceCommand.java#L47-L50 where the content-type is hard coded as ``ContentTypes.TEXT_XML_UTF8``

Right now the issue is not affected to PortletResponseUtil. But we are not sure about the future.

**Comment by hhuijser** [comment]
Got it... I'll still add the same fix to PortletResponseUtil as well, just to keep the code in sync

**Comment by hhuijser** [comment]
Sent to Byran for review: https://github.com/blzaugg/liferay-portal/pull/165

**Pull request closed without merging**
