### PR TITLE
Lps 127030

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
>  SF request: 
> Hi Hugo can you add a new sf rule? 
> See https://github.com/hhuijser/liferay-portal/pull/5265.
> This added a new test rule `InitializeKernelUtilClassTestRule` which Brian wants automatically added to all unit tests by sf.
> 
> It should be applied to all unit tests except the ones that use `NewEnvTestRule` or `AspectJNewEnvTestRule` and also should not be used with `@RunWith(PowerMockRunner.class)`

Hey @mtambara,

I will work on this tomorrow.
Just one question, why did you apply this rule [here](https://github.com/hhuijser/liferay-portal/pull/5265/commits/284be690426cda87d994b134166823babe9df8e7#diff-0e279262c42cb774a50f307f54611548a46bb8cff21e986aa2e6e19ef14c3359R28-R30)? This file uses `NewEnvTestRule`.

**Comment by mtambara** [comment]
@ling-alan-huang My bad, that shouldn't be there. Pushed the change

**Comment by ling-alan-huang** [comment]
Got it. Thanks.

**Comment by ling-alan-huang** [comment]
Hey @mtambara Just check with you again. I can see 2000+ violations on master, any conditions are we missing?
For example, why don't we apply the SF rule [here](https://github.com/mtambara/liferay-portal/blob/LPS-127030/modules/apps/data-engine/data-engine-rest-impl/src/test/java/com/liferay/data/engine/rest/internal/dto/v2_0/util/DataDefinitionRuleParameterUtilTest.java) and [here](https://github.com/mtambara/liferay-portal/blob/LPS-127030/modules/apps/layout/layout-page-template-test/src/testIntegration/java/com/liferay/layout/page/template/service/test/LayoutPageTemplateEntryServiceTest.java)

**Comment by mtambara** [comment]
@ling-alan-huang I expected that we'd see the rule added a lot of places, I don't believe there should be any more conditions. We don't apply to `DataDefinitionRuleParameterUtilTest` because it uses `MockitoJUnitRunner` and we don't apply to `LayoutPageTemplateEntryServiceTest` because it's an integration test

**Comment by ling-alan-huang** [comment]
Thanks @mtambara 

> We don't apply to `DataDefinitionRuleParameterUtilTest` because it uses `MockitoJUnitRunner`

`AddFormInstanceRecordMVCResourceCommandTest` also uses `MockitoJUnitRunner` [here](https://github.com/hhuijser/liferay-portal/pull/5265/commits/01fb65b14bd72e660f2cb822ca90f9c36f3d0b83#diff-00be60dcc22de2ba7b01317aff6535c026e99e183d348af0a35796c37dba6ef7R57), but you did apply to it.


>  we don't apply to `LayoutPageTemplateEntryServiceTest` because it's an integration test

I am not familiar with test area, how do I know it is an integration test? The path contains `testIntegration`?

**Comment by mtambara** [comment]
`AddFormInstanceRecordMVCResourceCommandTest` shouldn't have the rule, pushed that fix. Yeah, integration tests will contain `testIntegration` and usually use the `@RunWith(Arquillian.class)` test runner

**Comment by ling-alan-huang** [comment]
Hey @mtambara It is not easy to automatically add `InitializeKernelUtilClassTestRuleCheck` in SF, SF usually doesn't change logic on any files. I just added one SF rule to check missing `InitializeKernelUtilClassTestRuleCheck` and display message, I can see 1000+ files need to be manually add `InitializeKernelUtilClassTestRuleCheck`, can you help to check we really need to change those files?

**Comment by mtambara** [comment]
@ling-alan-huang If there are 1000+ that need to be modified, it would be nice if SF could automatically add the rule to at least some of them, even if it is just the easier cases where there isn't an existing test rule. With a list that large, it'll be faster to just add the rule and see if any of the tests break since Brian wants the rule on as many unit tests as possible.

**Comment by mtambara** [comment]
@ling-alan-huang For example, for unit tests that don't have any @ClassRule currently, they just need the new rule added. Even having just this automated would cut down the number of tests that need a manual change, something more complicated like using the AggregateTestRule

**Comment by mtambara** [comment]
@ling-alan-huang As part of the SF rule can you enforce that people aren't doing `FileUtil.setFile(new FileImpl())` or `PropsUtil.setProps(new PropsImpl())` or anything like that? We want to ensure that everyone goes through the test rule for setting up utils like that

**Comment by ling-alan-huang** [comment]
> As part of the SF rule can you enforce that people aren't doing FileUtil.setFile(new FileImpl()) or PropsUtil.setProps(new PropsImpl()) or anything like that? 

@mtambara Because `InitializeKernelUtilClassTestRule` already calls `FileUtil.setFile()` and `PropsUtil.setProps()`?
SF is not enought smart to know that. Even SF knows that, if we add other method calls in `InitializeKernelUtilClassTestRule` in the future, SF wouldn't even know that.

**Comment by mtambara** [comment]
@ling-alan-huang what do you mean? Aren’t there already SF rules that restrict using certain method calls? (Like the HashMapBuilder rule). It wouldn’t need to automatically detect what gets set up in InitializeKernelUtilClassTestRule, if we add more in the future it’ll just have to get manually added to SF

**Comment by mtambara** [comment]
Hey @ling-alan-huang, any updates?

**Comment by ling-alan-huang** [comment]
Hi @mtambara I saw you [new pull](https://github.com/ling-alan-huang/liferay-portal/pull/367), I will work on that next week.

**Pull request closed without merging**
