### PR TITLE
Deprecate

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @hhuijser I think that this should deal with the deprecation you told me. I didn't know if you have a ticket for it, so I didn't add any LPS to the commit.
Let me know if you have any question.
Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @Preston-Crary can you confirm the fix above looks good?
Thanks!

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/62413

**Comment by sergiogonzalez** [comment]
Hey @Preston-Crary we could just deprecate it, but I don't know if we might be breaking something because we used to have a permission registered with the model.class.name MBThread and if we just remove it there might be something broken. 
If you think it shouldn't break anything we could just deprecate it.

Regarding the property overwrite it was my bad, I wanted to register it for both class names, not override it. It should be an array instead of a new line.

@Preston-Crary Let us know what you think to decide whether just deprecate it or registered it for both.

Thanks!

**Comment by Preston-Crary** [comment]
I think we should just try removing it and see if anything breaks on the CI and do some manual testing with MB and permissions to make sure we think it's a safe change.  Once we know if it's safe or not we can make a better choice.

**Pull request closed without merging**
