### PR TITLE
[TS] Lps 78406 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:retest

**Comment by hhuijser** [comment]
Hey @arthurchan35 

This doesn't make sense to me. All you're doing is basically reverting all the logic from LPS-70467 (except for the changes to portal.properties).

The reason `secureFilterTest` is there is exactly for the reason to test it's always enabled?

**Comment by arthurchan35** [comment]
@hhuijser,
Looking at the commit order, I have reason to believe the code changes are redundant, because once the securityFilter property is removed from portal.properties, the portal will set its parent filter(basePortalFilter) to be true by default, there is no way for a running portal to have a turned off securityFilter.
Thus the code changes and the tests are not neccassry.

**Comment by arthurchan35** [comment]
@marianoalvarosaiz,
I am removing some of your changes from LPS-70467, because parent class(basePortalFilter) of securityFilter has already have a default behavior of setting enable to true. As a matter of fact, your change of removing the property in portal.properties have effectively enforced the portal to enable securityFilter no matter what.
So I wanted to remove the code changes in the securityFilter class since they are causing regression for LPS-78406. Plus the tests you added.

**Comment by marianoalvarosaiz** [comment]
Hi @arthurchan35, @hhuijser,
 I would rather chose a different approach:

In LPS-70467 is stated that the _SecureFilter_ cannot be disabled. Because the code to read the enabled properties is generic we override _isFilterEnabled_ implementation to force that _SecureFilter_ is always enabled, and it should remain like that.

The problem is with _SharepointFilter_, I think is not a good approach to extend _SecureFilter_, but because it's like that you could follow the following alternatives:

1. Use a _sharepointFilterEnabled attribute in the SharepointFilter class that holds the information about the enabled property. That would mean changing _SharepointFilter.init_ method and overriding _SharepointFilter.isFilterEnabled,_ like in:
```
@Override
public void init(FilterConfig filterConfig) {
    super.init(filterConfig);

    setUsePermissionChecker(true);
		
    setSharepointFilterEnabled( 
        GetterUtil.getBoolean(
	    PropsUtil.get(getClass().getName()), true));
}
...
@Override
public boolean isFilterEnabled() {
    return _sharepointFilterEnabled;
}
...
private boolean _sharepointFilterEnabled = false;
```

2. Modify _BasePortalFilter._filterEnabled_ access modifier, so that in can be viewed from its children and the _SharepointFilter.isFilterEnabled_ properly overriden:
```
@Override
public boolean isFilterEnabled() {
    return filterEnabled;
}
```

Kind regards.

**Comment by hhuijser** [comment]
Sent to Mariano for review: https://github.com/marianoalvarosaiz/liferay-portal/pull/82

**Pull request closed without merging**
