### PR TITLE
LPS-79348

### PR DESCRIPTION
**Pull request by arthurchan35**
Hugo,
Previous PR https://github.com/pavel-savinov/liferay-portal/pull/158 was rejected because it was not the best place to add filtering, and it would cause pagination issue.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Pavel for review: https://github.com/pavel-savinov/liferay-portal/pull/161

**Pull request closed without merging**
