### PR TITLE
LPS-137599 Add support for the HEADER_PHASE of the Portlet 3.0 Lifecy…

### PR DESCRIPTION
**Pull request by ngriffin7a**
…cle to MVCPortlet

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@hhuijser Please review and run whatever tests you feel are necessary. Since this touches MVCPortlet, it might be best to run the full `ci:test`

**Comment by ngriffin7a** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@hhuijser If you look at the code in the commits of this pull, then I think that the only concern we should have (from a CI perspective) is whether or not `ant all` successfully builds all of the source. I think that's indeed the case here. The only thing that would be affected at runtime are portlets that opt-in to Portlet 3.0, of which only [PortletConfigurationPortlet.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portlet-configuration/portlet-configuration-web/src/main/java/com/liferay/portlet/configuration/web/internal/portlet/PortletConfigurationPortlet.java#L125) would be included. In light of that, should the test failures be considered to be unrelated, or should the tests be run again?

**Comment by hhuijser** [comment]
@ngriffin7a I'll have a look in a bit... I'll run `ci:forward` after

**Comment by hhuijser** [comment]
@ngriffin7a see https://github.com/hhuijser/liferay-portal/pull/5809
Made some SF changes, but feel free to check if I didn't mess up stuff

**Comment by ngriffin7a** [comment]
@hhuijser I rebased and tested your SF changes. All is well. Thanks!

**Pull request closed without merging**
