### PR TITLE
LPS-74536 Gradle file parser

### PR DESCRIPTION
**Pull request by petershin**
Hi Hugo,

Andrea reviewed the automated changes in a separate pull.

See https://github.com/brianchandotcom/liferay-portal/pull/52308 / https://github.com/brianchandotcom/liferay-portal/pull/52316

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by hhuijser** [comment]
1. Failing tests?
2. Are we formatting imports twice now (GradleImportsCheck)

**Comment by petershin** [comment]
@hhuijser 

The other commits were merged in last night, so it should pass now.  Added a commit to remove the other check

**Comment by petershin** [comment]
ci:retest

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
I'll send this as a new pull to make sure it has the other fixes

**Pull request closed without merging**
