### PR TITLE
LPS-84119 Sort method calls

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/96fccd408c2cc806e4dd3577f7a2698f435b8033

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Just resolved conflicts.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failure is not related to my changes.

**Comment by ling-alan-huang** [comment]
Note:

> I am gonna think about that one more... for some reason, I just don't like what were doing there
> 11:02
> In the future, every time we want a BaseJavaTermCheck applied to jsp, we'd have to rebuild the thing, like we do here, which is just not right
> 11:02
> Also, your fix is not working for jsp, since importNames is always empty when applying to jsp
> 11:03
> Anyway, gonna keep you pull open, but thinking of a better way to do this
> 
>

**Comment by hhuijser** [comment]
Closing for now. Let's go the approach we discussed. I'll let you know when the framework for that is in place

**Pull request closed without merging**
