### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

`AddSelectConfigurationFragmentToDisplayPageTemplate` is a confirmed flaky test since April 8 (from flaky test slack channel) @manoelcyreno

`SiteMemberships#OrganizationsView` looks flaky based on the history https://issues.liferay.com/browse/LRQA-58465

DisplayPageTemplate test fix was merged to upstream https://github.com/brianchandotcom/liferay-portal/pull/88373

not sure about index-related tests, will retest @xbrianlee

**Comment by jpince** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@hhuijser this one fails on rebase , can you resend.

**Comment by xbrianlee** [comment]
> not sure about index-related tests, will retest @xbrianlee

Thanks @jpince! There's still a few uncommon failures that we need to resolve (tracked under https://issues.liferay.com/issues/?filter=48564). We're trying to work on these when we aren't working on Sidecar.

**Pull request closed without merging**
