### PR TITLE
LPS-84119 Apply to *.wsdl files

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/78422

**Pull request closed without merging**
