### PR TITLE
LPS 122730

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
@4lejandrito failures seem related...
is this right: https://github.com/hhuijser/liferay-portal/pull/4999/files#diff-465e21ea4e0e62b25cce8e4182611578a3e3064fc6801b3aa9e60a1a05c36ce1R92

**Comment by 4lejandrito** [comment]
😓 I'll fix and resend.

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by hhuijser** [comment]
See https://github.com/4lejandrito/liferay-portal/pull/541

**Pull request closed without merging**
