### PR TITLE
LPS-56934

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @bejondshao 

In DynamicCSSUtil._getThemeImagesPath we use the cdnhost as well.
Do we need to do the same thing there?
If so, we should move the logic to PortalImpl.getCDNHost?

**Comment by hhuijser** [comment]
Actually, looking at your fix, the description of your fix is "don't get resource from CDN host when in control panel", but your fix does more than that. It completely sets the cdn host to BLANK. Are you sure this is not too aggresive?

**Comment by bejondshao** [comment]
Hi @hhuijser ,

When we really need to get theme images, that means we are out of control panel. At that time, the friendly url would be different from the value of cdn.exclude.paths. So we still can get cdn resources.

**Comment by bejondshao** [comment]
For your first comment, in DynamicCSSUtil._getThemeImagesPath we use the cdnhost as well. I think move the logic to getCDNHost is better.

Thanks

**Comment by bejondshao** [comment]
Hi @hhuijser ,

For the second comment, when we go to control panel, we should completely disable cdn. So friendly url has well control of this. All resources would come from host, not cdn host.

**Comment by hhuijser** [comment]
Okay, can you go ahead and resend?
Make sure the commit messages tell you exactly what is happening

**Comment by daledotshan** [comment]
Each http request will trigger ServicePreAction call, so each url call will
be intercept, unless the request does not include friendly url

Am I right?

**Comment by bejondshao** [comment]
Yes, so that means no matter if we move logic to getCDNHost or not, control
panel would not use CDN.

Bejond Shao

Jr. Engineer, Technical Support

Subscription Services

Liferay Dalian Software Co., Ltd.

**Pull request closed without merging**
