### PR TITLE
LPS-41440

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by hhuijser** [comment]
@yuhai 

The method getInstalledApps is using AppTitleComparator to sort the list in the end.
Looks like the new method does not use that comparator (appPersistence.findByCategory(category) does not use any comparator).

Should we apply this sorting to your fix?

**Comment by yuhai** [comment]
Hi Hugo,

For current logic "appPersistence.findByCategory(category)", I didn't change it (this is original logic,  please see getApps(String category)). If we apply this sorting in new method, I think it is ok and we also should change it in getApps(String category), is it right?. 

Thanks,
Hai

**Comment by hhuijser** [comment]
We should look into how appPersistence sorts when no comparator is used. The natural way of sorting might be good enough and we might not need the comparator (in getInstalledApps we need it for sure as we have a bunch of different lists combined). We just need to look into this and maybe test.

**Comment by yuhai** [comment]
Hi Hugo,

Got it. I debug our code and find that the comparator is by using AppModelImpl.compareTo(App app) order by appId asc (by invoking AppPersistenceImpl.findByCategory() {Collections.sort(list);}).

Thanks for your guide. :)

Please kindly let me know if there are other concerned.

Thanks,
Hai

**Comment by hhuijser** [comment]
Sent to Ryan Park for review: https://github.com/lionah/liferay-portal/pull/58

**Pull request closed without merging**
