### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@david-gutierrez-mesa @rodrigocunhaa @austinchiang flaky tests?
@xbrianlee the last PortalLogAssertorTest failure (under failures in common) might be search-related?

**Comment by xbrianlee** [comment]
@austinchiang Regarding the PortalLogAssertorTest failure for `com.liferay.document.library.test`, maybe we need to be more deliberate about the files we create. This issue seems similar to the one described in [TIKA-2530](https://issues.apache.org/jira/browse/TIKA-2530), where depending on the contents of the file there can be a buffer underrun.
```
    [junit] Caused by: org.apache.poi.util.LittleEndian$BufferUnderrunException: buffer underrun
    [junit] 	at org.apache.poi.util.LittleEndian.readInt(LittleEndian.java:690)
    [junit] 	at org.apache.tika.parser.executable.ExecutableParser.parsePE(ExecutableParser.java:98)
    [junit] 	at org.apache.tika.parser.executable.ExecutableParser.parse(ExecutableParser.java:74)
    [junit] 	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
    [junit] 	... 63 more
```

**Comment by hhuijser** [comment]
ci:test:relevant

**Pull request closed without merging**
