### PR TITLE
LPS-103872 Add SF rules for portal.properties

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Previous PR: https://github.com/hhuijser/liferay-portal/pull/3840#issuecomment-548337597

Commit [LPS-103872 Skip adding empty line if … …](https://github.com/hhuijser/liferay-portal/commit/188faa5e83989bbd08493c344ced5ddc32a97fce): Skip adding empty line [here](https://github.com/hhuijser/liferay-portal/commit/3751098c8bb7644c6eb27d82781d6f7c6e176442#diff-70e7a8b9586d2a3f809fcc9e9e22e2b3R4363)

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/80403

**Comment by brianwulbern** [comment]
@pyoo47,

Have you seen the [CI bot comment](https://github.com/hhuijser/liferay-portal/pull/3845#issuecomment-548715478) doing this recently - it looks off: "ci:test:ci:test:sf"

**Pull request closed without merging**
