### PR TITLE
Code example of removing import issue

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
Hi @hhuijser ,

This is a quick example. Please run `../../../gradlew formatSource` in `modules/portal-cache/portal-cache-ehcache` and the import of `PortalCacheManagerNames` will be removed from `MultiVMEhcachePortalCacheManager2.java`.

**Comment by hhuijser** [comment]
@dantewang 

Just FYI, the source of this problem is somewhere in ClassUtil (probably method _processAnnotationParameters). I'll look at this, but his is all code I am not familiar with. Not sure if I have time for this today...

**Comment by hhuijser** [comment]
Sent fix to Brian: https://github.com/brianchandotcom/liferay-portal/pull/30530

**Comment by dantewang** [comment]
Thank you!

**Pull request closed without merging**
