### PR TITLE
LPS-84119 BaseTagAttributesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Can I make this change?

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:test:bundle

**Comment by ling-alan-huang** [comment]
ci:help

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
@jonmak08, does this look alright. I don't remember why back in the days I excluded these kind of tags when applying this logic, but apparently the tests all pass without problems?

**Comment by jonmak08** [comment]
Hey @hhuijser,

Those changes look good.  I thought before we changed the quotes, but a few years ago, we stopped doing that.  I do not remember the full logic or reasoning, but I thought it had something to do with the taglib being executed first so the wrapping double quotes and the double quotes within the taglib would not be an issue, but I am not sure.

Either way, it looks good with the changes.

Please let me know if you have any questions. Thanks!

**Comment by ling-alan-huang** [comment]
I am resolving the conflicts.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:bundle

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Testing again, I don't understand why compile error happened, I can build it successfully on my end. Let's test again.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by jpince** [comment]
Needs https://github.com/brianchandotcom/liferay-portal/pull/88675. Not sure how many tests this will fix.

**Comment by hhuijser** [comment]
@ling-alan-huang don't worry about rebasing, I'll generate on my end

**Comment by hhuijser** [comment]
@ling-alan-huang 
Sending generated files first: https://github.com/hhuijser/liferay-portal/pull/4272
We'll need this backported too, before we can do the changes in SF

**Comment by hhuijser** [comment]
Ha, I realize we can't do that... okay will send this thing all together and ask Brian to generate for the 7.x branches

**Comment by hhuijser** [comment]
btw, let's not use LPS-84119 anymore... that one is too old
we have LPS-105380 and probably time to create a new one

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4275

**Pull request closed without merging**
