### PR TITLE
LPS-105380 XMLDTDVersionCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

_Issue:_ 
https://github.com/brianchandotcom/liferay-portal-ee/pull/32123#issuecomment-721369758

_Related pulls:_
7.3.x: https://github.com/hhuijser/liferay-portal-ee/pull/3199
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3200
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3201
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3202

### CODE REVIEW

**Comment by hhuijser** [comment]
@ling-alan-huang the failures in the pulls for the 7.x branches, are those all unrelated?

**Comment by ling-alan-huang** [comment]
@hhuijser, I will check those errors.

**Comment by ling-alan-huang** [comment]
Closing, I will look into the test failures.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/5262

**Pull request closed without merging**
