### PR TITLE
LPS-55196

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
we build language because we manually change some translation for customer.

**Comment by hhuijser** [comment]
@zxdgoal, how did you generate those properties files in your second commit? Looks like you manually did stuff there?

@daledotshan, your commits are not needed. This key is a book title, which means it should be uppercase and no period at the end. When it's a proper sentence (with correct sentence structure), then we use lowercase and period at the end. See http://en.wikibooks.org/wiki/Basic_Book_Design/Capitalizing_Words_in_Titles

**Comment by hhuijser** [comment]
Closing... John will resend...

**Comment by daledotshan** [comment]
Thanks Hugo let us know this

**Pull request closed without merging**
