### PR TITLE
LPS-111459 SF

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @hhuijser  we don't need to publish anything yet, as we have many more changes that need to happen to workspace template so we can hold off, but if we can merge that, that would be good.

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
