### PR TITLE
Source Formatter's JavaServiceUtilCheck finds false positives

### PR DESCRIPTION
**Pull request by amosfong**
(?s) single line mode causes "." to match line breaks

http://www.regular-expressions.info/modifiers.html

### CODE REVIEW

**Comment by amosfong** [comment]
FYI @bawachhe

**Comment by bawachhe** [comment]
FYI @petershin 
I think the sensitivity to newlines was the objective in this case.
Did you find a bug with this regarding that newline sensitivity?

**Comment by bawachhe** [comment]
@amosfong 
See history on file: https://github.com/liferay/liferay-portal/commits/master/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/JavaServiceUtilCheck.java

**Comment by amosfong** [comment]
We don't want to match across multiple lines right? Imports shouldn't be more than one line?

See description in https://issues.liferay.com/browse/LPS-74188 that has an example where it matches incorrectly.

**Comment by bawachhe** [comment]
I think my goal in that regex was to catch [and iterate through] all the instances in which it should rightly flag these imports, and so the effort for catching newlines only applies to the `.`s on the end, not the middle, so yes that's definitely a valid issue, but as for the edges of the regex, I still wish to catch those newlines.  Perhaps we could use the regex I previously had?: https://github.com/liferay/liferay-portal/commit/231d5fcb4404fc3773f562dd3a54a03d354a061f

**Comment by amosfong** [comment]
I think it's unnecessary to catch any chars around the import statements, especially since it's a * which means it doesn't have to exist. So it wouldn't have an effect on whether the match is true or false.

I think the only reason would be if you needed to get the matched regex group into a string and do something with that.

**Comment by bawachhe** [comment]
Some StackOverflow reference: https://stackoverflow.com/questions/8923398/regex-doesnt-work-in-string-matches
Java's `String.matches()` attempts to run the regex against the entire string, rather than any part of it, so the statement will always return false in any file that's more than one line, hence the necessity for allocating for newlines apart from `.*`

**Comment by amosfong** [comment]
ah ok, that makes sense. find() makes more sense to me, but I think whatever is faster would be best.

ok, closing this PR, thanks @bawachhe!

**Comment by bawachhe** [comment]
ci:stop

**Pull request closed without merging**
