### PR TITLE
LPS-93507 Poshi Script SF: Braces that are in the wrong line

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-93507

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF test results: https://github.com/ling-alan-huang/liferay-portal/pull/75#issuecomment-501582870

**Comment by hhuijser** [comment]
Sent to Kenji for review: https://github.com/kenjiheigel/liferay-portal/pull/498

**Pull request closed without merging**
