### PR TITLE
LPS-84119 Add YMLStylingCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/brianchandotcom/liferay-portal/pull/79642#issuecomment-542991713

Please review LPS-84119, if it is OK to you please send to @petershin to review others.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
cc: @dgarciasarai

**Comment by ling-alan-huang** [comment]
```
     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: Truncated message :
     [java] ./modules/private/apps/portal-workflow/portal-workflow-metrics-rest-impl/rest-openapi.yaml expected:<...        description:[
     [java]                 https://schema.org/AssigneeUser
     [java]             properties:
```
 It is not current branch.

```
     [java] 2: ./build.properties expected:<...try-impl,\
     [java]     #    [dxp/apps,\
     [java]     #    ]util/portal-tools-db...> but was:<...try-impl,\
     [java]     #    []util/portal-tools-db...>
```
It is not related to my changes.

**Comment by dgarciasarai** [comment]
Thanks all of you for this effort :)

**Comment by dgarciasarai** [comment]
Any updates on this? Thanks.

**Comment by hhuijser** [comment]
Sent to Peter Shin for review: https://github.com/petershin/liferay-portal/pull/759

**Pull request closed without merging**
