### PR TITLE
LPS-93506 Poshi Script SF: Sorting of annotations

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser,

This is another Poshi Script SF task.
https://issues.liferay.com/browse/LPS-93506

Please refer to [Poshi Script Annotations](https://github.com/liferay/com-liferay-poshi-runner/blob/master/poshi-script.markdown#annotations).

No violations on master.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
@ling-alan-huang what about these: https://github.com/liferay/com-liferay-poshi-runner/blob/e286983/poshi-runner/src/test/resources/com/liferay/poshi/runner/dependencies/elements/PoshiScript.testcase#L104-L105

**Comment by ling-alan-huang** [comment]
Nice catching, will do the same thing to `test annotations `.
Correct, comparing the entire annotations string can do the same thing.
Closing, I will resend tomorrow.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/3512

**Pull request closed without merging**
