### PR TITLE
LPS-105380_VariableNameCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,
https://github.com/brianchandotcom/liferay-portal/pull/96386#issuecomment-735518425

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
