### PR TITLE
LPS-132651

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@jpince

**Comment by jpince** [comment]
@hhuijser failures in `AMImageEntryProcessorTest` look related to your changes, can you please take a look? Everything else looks unrelated based on the [QA analysis](https://liferay.slack.com/archives/CL84ZPHAT/p1622819723071700)

**Comment by hhuijser** [comment]
@Preston-Crary can you help fixing the `AMImageEntryProcessorTest` failure?

**Comment by Preston-Crary** [comment]
Please see https://github.com/hhuijser/liferay-portal/pull/5636

**Comment by hhuijser** [comment]
Thanks @Preston-Crary

**Pull request closed without merging**
