### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@jpince

**Comment by jpince** [comment]
@hhuijser I will ask QA to review the test results. Could you please hold onto this until after the EP2/GA2 release? We are hoping to build today, and a massive rename like this seems risky at this point. But please lmk if I'm misreading your changes and the risk of regression is actually low.

**Comment by hhuijser** [comment]
@jpince this can wait... no urgency

**Comment by xbrianlee** [comment]
@hhuijser I took a look at the results and they look good for the most part. [Here's a list of tests that failed here, but not in a gauntlet run around the same SHA](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1535542395&testrayRunIdA=1535416343&statusB=2).

Two main issues:
1. Most of these failures are Commerce tests throwing an exception ([example](https://testray.liferay.com/reports/production/logs/2021-05/test-1-11/test-portal-acceptance-pullrequest(master)/8998/modules-integration-mysql57-jdk8/0/11/jenkins-console.txt.gz))
1. There are quite a few aborted tests (see [Jenkins Report](https://test-1-11.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8998/jenkins-report.html)) so we should re-run this PR after (1) is fixed

**Pull request closed without merging**
