### PR TITLE
LPS-105380 PoshiEmptyLinesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://liferay.slack.com/archives/C1SJ64S9X/p1621876408010700?thread_ts=1621547483.007600&cid=C1SJ64S9X

I fixed logic to remove the empty line before "}", but keep it when the previous line is a comment line.
we also did the same rule for java, I mean skip empty line before and after the comment line.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/5599
SF failures have been fixed in other pulls

**Pull request closed without merging**
