### PR TITLE
[TS] LPS-88054 The database credentials are exposed in log

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser ,

I did same changes with LPS-83460.

Thanks,
Alan

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:test

**Comment by hhuijser** [comment]
Sent to Tina for review: https://github.com/tinatian/liferay-portal/pull/1130

**Pull request closed without merging**
