### PR TITLE
LPS-114565

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@john-co another `yarnInstallModules` failure in `semantic-versioning` up [above](https://github.com/hhuijser/liferay-portal/pull/4338#issuecomment-637177911), per your [note here](https://liferay.slack.com/archives/C19PWQ74J/p1590769957399900).

And I've linked you [in a comment on the thread](https://liferay.slack.com/archives/CD7939WBE/p1591066795228700?thread_ts=1591005020.211800&cid=CD7939WBE) about the Iframe event firing macros that we now need before interacting with certain elements.

**Comment by brianwulbern** [comment]
ci:stop (Hugo will fix something spotted in the results and run again)

**Pull request closed without merging**
