### PR TITLE
LPS-105380_FTLTagAttributesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

https://github.com/brianchandotcom/liferay-portal/compare/3775684ff3...f0ec87764a

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang Indentation here is incorrect as well: https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/commerce-theme-minium/commerce-theme-minium/src/templates/init_custom.ftl#L24

Can you add that and resend?

**Comment by hhuijser** [comment]
I cherry picked your last 2 commits here: https://github.com/hhuijser/liferay-portal/pull/5177

**Comment by ling-alan-huang** [comment]
Got it.

**Pull request closed without merging**
