### PR TITLE
 LPS-105380 JavaPackagePathCheck.expectedInternalImplementsData

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Related pull:
https://github.com/hhuijser/liferay-portal-ee/pull/3059

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:bundle

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
