### PR TITLE
LPS-115714 BNDLiferayEnterpriseAppCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issues: https://github.com/brianchandotcom/liferay-portal/pull/93610#issuecomment-685260017

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Lots of conflicts :(
Can you resend?

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/4773

**Pull request closed without merging**
