### PR TITLE
LPS-105380_JSPStylingCheck_20200921_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/37375a0321e8904da3d64bc2cdbc5b67fbf2b111

_Related pulls:_
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3134
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3136
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3135

This change doesn't apply to single-quote,
see:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp#L64

Looks like liferay customized tags don't support it.

_Example:_
```
alan:~/liferay_code/master/liferay-portal/modules/apps/account/account-admin-web[LPS-105380_JSPStylingCheck_20200921_master]$ git diff
diff --git a/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp b/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp
index 293bc3237fff..f810c4a6a283 100644
--- a/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp
+++ b/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_users_admin/select_account_entry.jsp
@@ -61,7 +61,7 @@ if (selectAccountEntryManagementToolbarDisplayContext.isSingleSelect()) {
                        %>
 
                        <liferay-ui:search-container-column-text
-                               cssClass='<%= cssClass + " table-title" %>'
+                               cssClass='<%= cssClass %> table-title'
                                name="name"
                                value="<%= HtmlUtil.escape(accountEntryDisplay.getName()) %>"
                        />

```

_Compile error:_
```
* What went wrong:
Execution failed for task ':apps:account:account-admin-web:generateJSPJava'.
> file:/Users/alan/liferay_code/master/liferay-portal/modules/apps/account/account-admin-web/classes/META-INF/resources/account_users_admin/select_account_entry.jsp(92,4) PWC6305: The end tag "&lt;/liferay-ui:search-container-column-text" is unbalanced

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
192 actionable tasks: 6 executed, 186 up-to-date

```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:bundle

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
@ling-alan-huang 

So... you're right about `cssClass='<%= cssClass %> table-title'` not being supported and breaking for `generateJSPJava`
However, SF (JSPTagAttributesCheck) changes `cssClass='<%= cssClass %> table-title'`  to `cssClass="<%= cssClass %> table-title"` and that one does compile without problems

**Comment by ling-alan-huang** [comment]
@hhuijser 

> However, SF (JSPTagAttributesCheck) changes cssClass='<%= cssClass %> table-title' to cssClass="<%= cssClass %> table-title" and that one does compile without problems

Ring the bell.
`BaseTagAttributesCheck.java` won't change it, because the tag name conains colon,
see: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/BaseTagAttributesCheck.java#L272

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4875

**Pull request closed without merging**
