### PR TITLE
LPS-84119 Fix regex, more accurately match *.*.properties, avoid to match the file path which the directory contains dot

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser,

See the issue: https://github.com/hhuijser/liferay-portal-ee/pull/2900#issuecomment-501201647

I analysed `ExcludeSyntaxPattern(ExcludeSyntax.REGEX, ".*/\\w+\\..*\\.properties")`, I think it want to exclude the file name which contains two DOTs, like `app.server.properties` or` portal-legacy-4.4.properties`

My second commit `Auto SF` doesn't break SF rule here: https://github.com/liferay/liferay-portal/commit/4c0d4e54675f38dc17278bd8da58733ef59d9f3f

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:sf:test

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/74671

**Pull request closed without merging**
