### PR TITLE
Revert "LPS-84119 Only enable BNDImportsCheck for master for now"

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser,

Please review these first:
LPS-84119 Auto SF 7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/2875
LPS-84119 Auto SF 7.1.x-Private: https://github.com/hhuijser/liferay-portal-ee/pull/2876
LPS-84119 Auto SF 7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/2877
LPS-84119 Auto SF 7.0.x-Private: https://github.com/hhuijser/liferay-portal-ee/pull/2878

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang waiting with this one, since Peter mentioned tests are breaking in master

**Comment by ling-alan-huang** [comment]
Got it.

**Pull request closed without merging**
