### PR TITLE
LPS-105380 CamelCaseNameCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/c40804fcba0ed6a496c6d37fe8836252dd8fa2b7

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang forgot to communicate with you on this one.
I actually improved the check a bit here: https://github.com/hhuijser/liferay-portal/pull/6091

**Pull request closed without merging**
