### PR TITLE
LPS-52423

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
information from  david
	this issue is caused by old calendar permission file,since we have moved to the
	calendar portlet  from portal to plugin, so we should deprecate the old calendar custom sql definitions and old calendar permission definitions

**Comment by hhuijser** [comment]
@daviddotzhang 

Does this mean, we now have those calendar.xml just sitting there (without anyone using em)?
If so, shouldn't we remove those lines of code (instead of commenting them out) and also remove the calendar.xml files?

**Comment by daviddotzhang** [comment]
@hhuijser 
I think it should be safe ,since there are same files in the calender portlet.

as Dale,s suggestion, it,s safe to keep it.

besides there are also some other CSS file, like "calendar.css".

**Comment by hhuijser** [comment]
Sent to brandizzi for further review: https://github.com/brandizzi/liferay-portal/pull/6

**Pull request closed without merging**
