### PR TITLE
LPS-51790

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @daledotshan @daviddotzhang 

Is this right?
Dale, your commit is changing logic as well, so it's not just source formatting (like your commit message says).
I figure you have talked to David about this, but just make sure your commit messages are clear and let me know that this fix has been tested and it works,

Let me know and I'll review after that,

Thanks,

**Comment by daledotshan** [comment]
Hey Hugo,
I have tested it, it works

**Comment by daledotshan** [comment]
actually my fix did same thing with david, this issue happen when group is staging group. because staging group not a site so we return true directly cause use company level locale not group level locale

in my opinion If david fix is right, declare a new variable liveGroup is just waste since only group is staging group we reassgin a new value to it otherwise  liveGroup always == group

If I am wrong please correct me

**Comment by hhuijser** [comment]
I can see how your code eventually does the same thing as David's code, but that's only because we know that a Staging group is not a site.
It still is a logical change and therefore the commit message "source formatting" is not correct.
I do think your commit is good, but do you mind changing the commit message and resending the pull?

**Comment by daledotshan** [comment]
Hey Hugo,
I modified the commit message and updated this pull request
Please check it

**Comment by hhuijser** [comment]
Sent to Mate for further review: https://github.com/matethurzo/liferay-portal/pull/917

**Pull request closed without merging**
