### PR TITLE
LPS-111518

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@hhuijser just waiting for https://github.com/brianchandotcom/liferay-portal/commit/e5b09b8fef15359b3d39177eb87158aeae412698 to be merged to upstream. There were other blockers earlier. Once it's merged to upstream, you should be able to pass sf.

**Comment by jpince** [comment]
https://github.com/brianchandotcom/liferay-portal/commit/9e892962c922b9959bb17e24a2f43654c0242822 is also needed. @hhuijser  @lingalanhuang you can wait for this to merge to upstream (~2 hours from now) or rebase your branches on Brian's origin.

Please let us know how we can help you guys get code through. CI infrastructure changes can be requested in the #ci Slack channel, @austinchiang or other test leads can help with POSHI/test ignores, and I'm happy to help with anything else :).

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4118

**Pull request closed without merging**
