### PR TITLE
LPS-110344 BNDBundleCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://issues.liferay.com/browse/LPS-110344

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang I sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/86392

Can you add markdown documentation instead of adding the LPS number in the warning message?

**Comment by ling-alan-huang** [comment]
Added markdown file ant sent PR: https://github.com/hhuijser/liferay-portal/pull/4065

**Pull request closed without merging**
