### PR TITLE
LPS-90380 Create SourceFormatter Task to enforce liferay-npm-scripts usage

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/68174

@ling-alan-huang , please check my changes to see if I didn't break anything

**Comment by ling-alan-huang** [comment]
> Sent to Brian for review: [brianchandotcom#68174](https://github.com/brianchandotcom/liferay-portal/pull/68174)
> 
> @ling-alan-huang , please check my changes to see if I didn't break anything

Your changes didn't break anything, thanks.

**Pull request closed without merging**
