### PR TITLE
LPS-105380 Yaml

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issues: https://github.com/liftedkilt/lfrit-lax-network/pull/25

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
I added https://github.com/hhuijser/liferay-portal/pull/4433/commits/6975bb56037f52b225209bdbeaeda69fe6348234, and rebase.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4447

**Pull request closed without merging**
