### PR TITLE
LPS-84119 Add GradleStylingCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
> On Wed, Jun 19, 2019 at 10:37 AM Brian Chan <brian.chan@liferay.com> wrote:
> See modules/apps/message-boards/message-boards-uad/build.gradle
> 
> transformKeys = ["categories-and-threads": "categories-and-threads", "javax.portlet.title.com_liferay_message_boards_web_portlet_MBPortlet": "application.name.com.liferay.message.boards.uad", "root-messages-with-multiple-replies-cannot-be-deleted.-delete-the-thread-instead": "root-messages-with-multiple-replies-cannot-be-deleted.-delete-the-thread-instead"]
> 
> One per line please? And sort them? Thx.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian and merged: https://github.com/brianchandotcom/liferay-portal/pull/74964

**Pull request closed without merging**
