### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
Needs https://github.com/brianchandotcom/liferay-portal/pull/88675

**Comment by jpince** [comment]
Needs https://github.com/brianchandotcom/liferay-portal/pull/88677 (merged)

**Comment by jpince** [comment]
ci:forward

**Comment by hhuijser** [comment]
Thanks @jpince!

**Comment by jpince** [comment]
@manoelcyreno flaky test - I see it in #qa-flaky-tests

**Comment by jpince** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@xbrianlee 
```
failure in bulk execution:
[1]: index [liferay-20099], type [LiferayDocumentType], id [com.liferay.journal.model.JournalArticle_PORTLET_67672], message [ElasticsearchTimeoutException[Failed to acknowledge mapping update within [30s]]]
```

@vicnate5 lpkg-base smoke
```
java.lang.RuntimeException: Element is not present at "xpath=(//div | //li)[(contains(@class,'open') or contains(@class,'show')) and (contains(@class,'dropdown') or contains(.//*/@class,'dropdown'))]//*[self::a or self::span or self::button][normalize-space(text())='Public Page']"
```

**Pull request closed without merging**
