### PR TITLE
Remove unneeded fully qualified class names

### PR DESCRIPTION
**Pull request by codyhoag**
Hi Hugo,

I've fixed the two errors you pointed out in Jim's previous pull request (hhuijser#2324). I've consolidated the commits to allow for an easier review. While testing, I found another problem that I fixed in commit 420cecb177edcdba266544429f690c2901e1b0e1. A brief description of this issue is described in the commit message. Thanks!

cc\ @jhinkey

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @codyhoag 

I am not sure if I fully understand what's going on here https://github.com/hhuijser/liferay-portal/commit/420cecb177edcdba266544429f690c2901e1b0e1

Do we just want to not apply the logic that removes the unnecessary fully qualified class names for the PersistenceImpl methods?
In that case, can we do this with some kind of boolean that we add to the method writeFile?

Your commit feels a bit hacky to me...

**Comment by codyhoag** [comment]
Hey @hhuijser,

I did it this way because we also want to strip the fully qualified names for PersistenceImpl classes. However, since the Persistence and PersistenceUtil classes need the original (non-stripped) PersitenceImpl methods (Persistence/PersitenceUtil have far less imports than PersistenceImpl, so not nearly as many class names need to be stripped), creating a temporary version and preserving its content seemed like a good route.

Let me know your thoughts. Thanks!

**Comment by hhuijser** [comment]
Hey @codyhoag 

Okay, so I think what's the situation, but let me double check first if I understand correctly...

For the *Persistence.java and *Util.java files, we get the javadocs from the *PersistenceImpl.java where we have stripped the fullyQualifiedNames already?

I would still rather see a bit cleaner fix (so it becomes a bit better readable and what if we want to do the same for *FinderUtil or other files?).

1. Instead of that if-statement in writeFile, I'd rather use a boolean stripFullyQualifiedClassNames.
2. Can we maybe somehow return the list of methods (before the stripping of classnames) in createPersistenceImpl and then use that list in createPersistenceUtil and createPersistence (rather than a global variable?

**Comment by codyhoag** [comment]
Hey @hhuijser 

Thanks for your review. I'll close this PR and refactor it so it is a cleaner fix. I'll resend once I'm finished.

**Pull request closed without merging**
