### PR TITLE
LPS-136308 GradleDependenciesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://issues.liferay.com/browse/LPS-136308

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
