### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by petershin**
See https://github.com/petershin/liferay-portal/pull/415#issue-254884073<br /><br />@holatuwol

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:relevant

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:stop

**Comment by petershin** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@holatuwol thanks for the fix.
Need to rewrite still a bit since SF is not smart enough to know which branch to chose when there are multiple properties files with different values. Been on my todo list for a while, but hope to get to that soon.

Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/68475

**Pull request closed without merging**
