### PR TITLE
LPS-74064 New role with all permissions to License Manager fails to view License Manager in control panel

### PR DESCRIPTION
**Pull request by ling-alan-huang**
The license manager permissions are never used. Solving this problem by removing the license manager permissions.

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @ling-alan-huang, simply ignoring a portlet does not feel right to me.

What exactly is the reason that this role with the correct view permission cannot view the portlet?

**Comment by ling-alan-huang** [comment]
Hi @hhuijser ,

I found that the License Manager portlet only has a check about if user has Administor Role.
No permission check about License Manager in the source.

please have a look at the execute() of UpdateLicenseAction.java

**Comment by hhuijser** [comment]
Okay, that means we should fix wherever we set those permissions for the License Manager portlet.

**Comment by hhuijser** [comment]
Incorrect fix.

**Pull request closed without merging**
