### PR TITLE
LPS-104249 Add SF rules for YAML: Sort properties with their's comment(s)

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

https://issues.liferay.com/browse/LPS-104249

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/80886

**Pull request closed without merging**
