### PR TITLE
LPS-110426

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@jpince, 
`java.lang.AssertionError: [projects/github/liferay-portal/modules/util/pmd/../../../modules/apps/archived/opensocial-portlet/docroot/WEB-INF/src/org/apache/shindig/gadgets/oauth/OAuthRequest.java:321:	Avoid unused local variables such as 'stateOwner'.]`
is a valid error, but unrelated to this pull and that file is a generated file

**Comment by jpince** [comment]
@hhuijser PMD is currently passing in upstream https://testray.liferay.com/home/-/testray/case_results/1126226354

I will ask Brian Chan if he's ok ignoring errors like this for archived apps, but I don't know where the failure is coming from.

**Comment by jpince** [comment]
ci:close BChan said to try to fix it. I've been trying to get both commits in here https://github.com/jpince/liferay-portal/pull/137.

**Comment by jpince** [comment]
Made it to BChan! https://github.com/brianchandotcom/liferay-portal/pull/88007

**Pull request closed without merging**
