### PR TITLE
LPS-58564

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Hugo,
I revert the fix for the GetterUtil class in test folder, because it is only used for internal test api.

We only fixed the GetterUtil class in portal service jar, because the issue only happen on when user type a full space through UI, and also we usually acquire the value that user typed with the through background api  ParamUtil.getXXXX()

We did not the fix to other class that due to following two reason:
1. Even right now we change all the class to use StringUtil.trim() but we can not prevent developer still will use jdk core api String.trim() in future

2. So far we can not tell this issue will effect other class

**Comment by hhuijser** [comment]
@bejondshao 

What exactly is a "full space"? Can you provide me with some documentation that describes the difference between full space and half space?
How come we end up with that full space there?

**Comment by bejondshao** [comment]
Full space can be found in LPS-58564. Full space can be typed with Chinese or Japanese input method from UI. There's no "full space" in English input method. In unicode, it's \u3000. Actually it's called ideographic space. I'll change "full space" into "ideographic space" in LPS-58564

**Comment by hhuijser** [comment]
Understand, do you mind updating the LPS and explain that a bit more clearly over there?

**Comment by bejondshao** [comment]
sure thing

**Comment by hhuijser** [comment]
@bejondshao 

Sending this to Brian for review.

Let's open a new ticket and use StringUtil.trim across the entire portal (just in case we ever have the same problem somewhere else). We can add a check to SF for this...

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/30248

**Pull request closed without merging**
