### PR TITLE
LPS-58669

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by hhuijser** [comment]
@zxdgoal 

What does the method JournalArticle.getContentByLocale do? Can we use that one?

**Comment by daledotshan** [comment]
Hey Hugo,
JournalArticle.getContentByLocale will return a xml file, that is not what
we want

**Comment by zxdgoal** [comment]
Yes, see.

```
	public static String getContentByLocale(
		Document document, String languageId, Map<String, String> tokens) {

		TransformerListener transformerListener =
			new LocaleTransformerListener();

		document = transformerListener.onXml(
			document.clone(), languageId, tokens);

		return document.asXML();
	}
```

**Comment by hhuijser** [comment]
Got it... just checking :)

**Comment by hhuijser** [comment]
Sent to Julio for further review: https://github.com/juliocamarero/liferay-portal/pull/3660

**Comment by hhuijser** [comment]
Closed the pull I sent to Julio as tests were broken. Let's test ourselves first to make sure it's not related to your fix...

**Pull request closed without merging**
