### PR TITLE
LPS-105380_Poshi_20201008_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

_Related pulls:_
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3145
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3144
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3143

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4932

**Pull request closed without merging**
