### PR TITLE
LPS-105380 JavaTestMethodAnnotationsCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Previous pull: https://github.com/hhuijser/liferay-portal/pull/4351

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to this pull, @hhuijser alreday fixed them on other pulls.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4395

**Pull request closed without merging**
