### PR TITLE
LPS-105380 BNDCapabilityCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Hugo,

This pull is for https://github.com/liferay/liferay-portal/blob/master/modules/apps/site-initializer/site-initializer-customer-portal/bnd.bnd#L4
also I already removed `modules/apps/site-initializer/source-formatter-suppressions.xml` for it.

But this pull is not for https://github.com/brianchandotcom/liferay-portal/commit/225ba5fbefe92661125f586a279c10a2eed50a99,
because SF is not smart enough to know what `\` exactly is, is for multiple lines or is an extra `\`.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
