### PR TITLE
LPS-84119 Poshi

### PR DESCRIPTION
**Pull request by ling-alan-huang**
**Issue:** 
https://github.com/liferay/liferay-portal/commit/284c8029e18b4f9dbb078be1393ce1b31d7f3533

**Violations only in 7.0.x.:**
https://github.com/hhuijser/liferay-portal-ee/pull/2924

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
This is not correct.
No whitespace after `//` needed when we're commenting out code (just like we do for java. Example: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/deploy/DeployUtil.java#L283)
Not sure if we can make SF smart enough to know when it's a real comment vs commented out code.

**Comment by ling-alan-huang** [comment]
Hi @hhuijser,
Just want to confirm this SF request.
Does this SF request only want 'adding the empty line after single comment'?

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/3787

**Pull request closed without merging**
