### PR TITLE
LPS-78312

### PR DESCRIPTION
**Pull request by petershin**
@hhuijser: There's a few modules that are using LanguageExtender.

[7.0.x-private/modules/private/apps/saml/saml-web/bnd.bnd](https://github.com/liferay/liferay-portal-ee/blob/7.0.x-private/modules/private/apps/saml/saml-web/bnd.bnd#L6-L12)
[com-liferay-osb-lcs-private/blob/7.0.x-private/osb-lcs-web/bnd.bnd](https://github.com/liferay/com-liferay-osb-lcs-private/blob/7.0.x-private/osb-lcs-web/bnd.bnd#L8-L11)

@igorbeslic

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@petershin 

This is incorrect:

The logic changed on commit cce9b23f1af469c957fe17cbe593bef1457a1c90
`bndLanguageProperties` will already be null if no `bnd.bnd` can be found, no need to continue in that case.

Also, let's check for `-lang` module first then, and check the bnd at the very end. A lof of the time, when using `Provide-Capability` it points to the `-lang` module

**Comment by hhuijser** [comment]
@petershin, I'll make the changes. Already almost there anyway :)

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/55875
Can you double check my changes?

**Pull request closed without merging**
