### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@wincent, can you have a look at this:

There is this in the log:
```
     [exec] apps/item-selector/item-selector-web/src/main/resources/META-INF/resources/view_item_selector_view_descriptor.jsp: BAD
     [exec] apps/product-navigation/product-navigation-site-administration/src/main/resources/META-INF/resources/sites/site_administration_body.jsp: BAD
     [exec] Prettier checked 1055 files, 2 files have problems
```

However, I only made whitespace changes to those files?

**Comment by wincent** [comment]
@hhuijser: Sent you a commit on top of this branch here: https://github.com/hhuijser/liferay-portal/pull/4097

> I don't think it was complaining about the lines that your PR touched, Hugo. But seeing as those files were touched, Prettier checked and formatted the entire file, and found that the formatting was wrong. The bad formatting seems to have been added in [60baf53](https://github.com/hhuijser/liferay-portal/commit/60baf5388b0500885d257bdcf00d52d8281f4c0a) and [d1ae251](https://github.com/hhuijser/liferay-portal/commit/d1ae251381e839b39424807496a81607d8188b03), which correspond to:
> 
> * [brianchandotcom#85435](https://github.com/brianchandotcom/liferay-portal/pull/85435)
> 
> * [brianchandotcom#85423](https://github.com/brianchandotcom/liferay-portal/pull/85423)
> 
> 
> Both of those got merged despite failing `ci:test:sf`.

**Comment by wincent** [comment]
Note that #4097 includes a rebase because the branch in this PR no longer applies cleanly on top of upstream `master`.

**Pull request closed without merging**
