### PR TITLE
LPS-121804_Python_ImportPackage

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/brianchandotcom/com-liferay-osb-asah-private/pull/2636#issuecomment-758772018

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
Thank you @ling-alan-huang !

**Comment by ling-alan-huang** [comment]
Closing. I will resend.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/5212

**Pull request closed without merging**
