### PR TITLE
LPS-115709 Merge both JSPs and remove duplicate mvc action

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @hhuijser 

I've refactored things a bit to make a 1:1 mapping between mvc actions and JSP views. Now both portlets can reuse the action name without creating duplicate classes.

Let me know if you see any problem with this approach.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Hey @adolfopa, I like this much better!

After I have been working on this for a bit, I am actually proposing the following rules (Brian has not approved yet, but I think he will)
https://gist.github.com/hhuijser/3ce9c5ef50cca5fe5eb896a10ada08cd

For `message-boards` that would mean:
- the command name in `MBAdminViewBannedUsersMVCRenderCommand` (`/message_boards/view_banned_users`) is violating rule 1 (I would change the class name to `ViewBannedUsersMVCRenderCommand`?)
- the command name in that same class is allowed to be `/message_boards_admin/*` (rule 2)

You can go ahead and send this pull to Brian... I can work on the additional changes

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1032

**Pull request closed without merging**
