### PR TITLE
LRQA-1 Quarantine Workflow upgrades

### PR DESCRIPTION
**Pull request by brianwulbern**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@rodrigocunhaa it looks like the [fix you made](https://github.com/rodrigocunhaa/liferay-portal/pull/103/commits/deca052ddf3b7b9cebcf86163e1cba7e17584072) isn't quite working on the tests.

**Comment by rodrigocunhaa** [comment]
Hi @brianwulbern , my fix wasn't merged to upstream yet when this relevant started to run.

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
@brianwulbern , looks like FI changed the back the tag that I mentioned before. I'll revert my fix.

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Resent it here: https://github.com/hhuijser/liferay-portal/pull/4430

**Comment by rodrigocunhaa** [comment]
ci:close

**Comment by rodrigocunhaa** [comment]
ci:stop

**Comment by rodrigocunhaa** [comment]
ci:stop

**Comment by brianwulbern** [comment]
Thanks, @rodrigocunhaa!  Yeah, I noticed your change took hold, but it was still failing, it makes sense now that it was because FI reverted their original change.

**Pull request closed without merging**
