### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@alexcandidos @jeyvison https://issues.liferay.com/browse/LPS-113672 is blocking this pull request, can we at least turn the failing tests off if we can't prioritize a fix?
Also flaky `AppResourceTest.testGetAppsPage`

@patriciajeanperez flaky member POSHI tests?

**Comment by jeyvison** [comment]
Already done :) @jpince  https://github.com/brianchandotcom/liferay-portal/pull/88966

**Comment by patriciajeanperez** [comment]
Fyi, some flaky [Site Membership tests](https://github.com/hhuijser/liferay-portal/pull/4281#issuecomment-631316929) @david-gutierrez-mesa

**Comment by jpince** [comment]
I think @manoelcyreno since david is on leave?

**Comment by alexcandidos** [comment]
Hi @jpince , this test is not of App Builder. Discussing with @jeyvison we are not able to look on the ticket right now but we don't know if is it okay to ignore this test without contact the WEM team (they probably are offline already)? @manoelcyreno what do you think?

The other unique failure was already ignored here https://github.com/brianchandotcom/liferay-portal/pull/88966.

**Comment by jpince** [comment]
@alexcandidos AppResourceTest is flaky, so I won't give an opinion on whether to ignore, you guys can decide.

If you could please ignore the tests in `PanelAppMyAccountPermissionsTest`, that would be helpful, and just let Echo team know. Also, it would be good to change the component in https://issues.liferay.com/browse/LPS-113672 so it shows up on their JIRA board.

**Comment by hhuijser** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
@jpince I sent the ignores for tests in PanelAppMyAccountPermissionsTest since they are being maintained by USM. Will look into the failures more tomorrow. @manoelcyreno

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by jeyvison** [comment]
@jpince ignoring tests that are failing in upstream related to app-builder

https://github.com/jeyvison/liferay-portal/pull/743

**Comment by jeyvison** [comment]
@patriciajeanperez sent it before me and it's already merged on Brian's Master. Thanks Patricia :)

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
will redo

**Pull request closed without merging**
