### PR TITLE
LPS-93513 Poshi

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issues: https://github.com/brianchandotcom/liferay-portal/pull/78490

If it is OK to you, please send to Kenji.

Thanks.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF test see: https://github.com/ling-alan-huang/liferay-portal/pull/123#issuecomment-532536873

**Comment by hhuijser** [comment]
Sent to Kenji for review: https://github.com/kenjiheigel/liferay-portal/pull/507

**Pull request closed without merging**
