### PR TITLE
LPS-56934

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
close this pull request

**Comment by daledotshan** [comment]
reopen it

**Comment by hhuijser** [comment]
@bejondshao @daledotshan 

Looks like we can improve the performance of this code quite a bit.
If (cdnDynamicResourceEnabled == false), none of this code is required?
So, let's make sure we only perform any of this if (cdnDynamicResourceEnabled == true)?

**Comment by daledotshan** [comment]
Hey @hhuijser 
I just updated this  pull request please help to check

**Comment by bejondshao** [comment]
Hey @daledotshan, @hhuijser ,

cdnHost is for static resource, and dynamicResourcesCDNHost is for dynamic resources. If we visit control panel, both cdnHost and dynamicResourcesCDNHost should be blank. So "String cdnHost = PortalUtil.getCDNHost(request);" is not right.

And then we consider "if (cdnDynamicResourceEnabled)", to set dynamicResourcesCDNHost.

**Comment by daledotshan** [comment]
Sorry, I am going to close this pull request and resent a pull request

**Pull request closed without merging**
