### PR TITLE
LPS-119446

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@jpince

**Comment by hhuijser** [comment]
@jpince, the other failures look related?

**Comment by jpince** [comment]
ci:test:relevant @hhuijser needs a retest since so many basic smoke and upgrade tests failed. It was an inconsistent failure in upstream. Sorry should have let you know that, pending Carolina's response

@carolmariaabb thank you!

**Comment by jpince** [comment]
Seemed like the rest of the failures were related to the ddm issue

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
Sent directly to Brian: https://github.com/brianchandotcom/liferay-portal/pull/102105

**Pull request closed without merging**
