### PR TITLE
LPS-105380 Add JavaMissingXMLPublicIdsCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

I don't have any other better ideas for this issue.

_Previous pull(merged):_
https://github.com/hhuijser/liferay-portal/pull/5262

_Issue:_
https://github.com/brianchandotcom/liferay-portal-ee/pull/33367#issuecomment-781275709

_Related pulls:_
7.3.x: https://github.com/hhuijser/liferay-portal-ee/pull/3213
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3214
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3215
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3216

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
c:forward

**Comment by hhuijser** [comment]
c:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
see https://github.com/hhuijser/liferay-portal/pull/5301

**Pull request closed without merging**
