### PR TITLE
Remove unneeded fully qualified class names

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Hugo,

These commits improve the ServiceBuilder so that it strips out all unnecessary fully qualified class names.

It also cleans up the ServiceBuilder._getJavaClass method introducing clearer param/variable names and adding more robust handling of path separators.

cc/ @codyhoag

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @jhinkey @codyhoag 

In ServiceBuild#_getJavaClass, we're stripping the /src/ from filePath (line 4208).
Don't we need to keep that when we try to retrieve the file (line 4222)?

Can you check that?

**Comment by hhuijser** [comment]
Another thing: we need to make this thing a bit more strict.

For example, If you look at AddressModelImpl.java, you see we have the import com.liferay.portal.model.Address.

Stripping the package like you do in your fix, will cause problems for the following lines: 104, 107, 110, 179 and 1054.

**Comment by jhinkey** [comment]
Hi Hugo,

I'll check the the file retrieval in _getJavaClass.

Good point, that we shouldn't strip the paths out of Strings.

Also in the case that a class has multiple imports that *end* in the same
class name (e.g., com.foo.SomeClass and com.bar.SomeClass), we must leave
their fully qualified class names.

I'll resend it after investigating and fixing. Thanks.

**Comment by jhinkey** [comment]
will resend

**Pull request closed without merging**
