### PR TITLE
LPS-105380_ConsumerTypeAnnotationCheck_20200217_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Hugo:

_Issue:_ https://github.com/brianchandotcom/liferay-portal/commit/c6ba6b532f360f0f51e7d324d1486ca982181c8a

_Related pulls:_
7.3.x: https://github.com/hhuijser/liferay-portal-ee/pull/3207
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3208
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3209
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3210

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
