### PR TITLE
LPS-104679 Apply checkstyles to jsp

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

A lot of violations for BuilderCheck, I just fixed some of them.
**Related pull:** 
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3011
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3010

I  changed `BuilderCheck.java` and added one property `checkInline` in this commit: https://github.com/hhuijser/liferay-portal/commit/f349511d6afa74033a28731cbfa141a7e66bad18, I set it to `false` for JSP files.

If I don't add this property see the SF error below:
[modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/edit_form_view.jsp](https://github.com/ling-alan-huang/liferay-portal/pull/151/files#diff-896ca02ab304b5861f125055e8fa9406R40)

```

<%
String componentId = renderResponse.getNamespace() + "dataLayoutBuilder";
String customObjectSidebarElementId = renderResponse.getNamespace() + "-app-builder-custom-object-sidebar";
String dataLayoutBuilderElementId = renderResponse.getNamespace() + "-app-builder-data-layout-builder";
String editFormViewRootElementId = renderResponse.getNamespace() + "-app-builder-edit-form-view";

long dataDefinitionId = ParamUtil.getLong(request, "dataDefinitionId");
long dataLayoutId = ParamUtil.getLong(request, "dataLayoutId");
boolean newCustomObject = ParamUtil.getBoolean(request, "newCustomObject");
%>

<div class="app-builder-root">
	<aui:form>
		<aui:input name="dataDefinition" type="hidden" />
		<aui:input name="dataLayout" type="hidden" />

		<portlet:renderURL var="basePortletURL" />

		<div class="app-builder-form-view-app" id="<%= editFormViewRootElementId %>">

			<%
			Map<String, Object> data = HashMapBuilder.<String, Object>put(
				"basePortletURL", basePortletURL.toString()
			).put(
				"customObjectSidebarElementId", customObjectSidebarElementId
			).put(
				"dataDefinitionId", dataDefinitionId
			).put(
				"dataLayoutBuilderElementId", dataLayoutBuilderElementId
			).put(
				"dataLayoutBuilderId", componentId
			).put(
				"dataLayoutId", dataLayoutId
			).put(
				"newCustomObject", newCustomObject
			).build();
			%>

			<react:component
				data="<%= data %>"
				module="js/pages/form-view/EditFormViewApp.es"
			/>
		</div>

		<div class="app-builder-form-view-body">
			<div class="app-builder-custom-object-sidebar" id="<%= customObjectSidebarElementId %>"></div>

			<div class="app-builder-sidebar-content" id="<%= dataLayoutBuilderElementId %>">
				<liferay-data-engine:data-layout-builder
					componentId="<%= componentId %>"
					dataDefinitionInputId="dataDefinition"
					dataLayoutId="<%= dataLayoutId %>"
					dataLayoutInputId="dataLayout"
					namespace="<%= renderResponse.getNamespace() %>"
				/>
			</div>
		</div>
	</aui:form>
</div>
```

-----------------------------
```
[java] Inline variable definition 'componentId' (20) inside 'HashMapBuilder' (40). See https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/builders.markdown: ./modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/edit_form_view.jsp 20 (Checkstyle:BuilderCheck)
 [java] Inline variable definition 'customObjectSidebarElementId' (21) inside 'HashMapBuilder' (40). See https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/builders.markdown: ./modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/edit_form_view.jsp 21 (Checkstyle:BuilderCheck)
 [java] Inline variable definition 'dataLayoutBuilderElementId' (22) inside 'HashMapBuilder' (40). See https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/builders.markdown: ./modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/edit_form_view.jsp 22 (Checkstyle:BuilderCheck)
```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
@hhuijser, I finished the check and added one commit.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/81781

**Pull request closed without merging**
