### PR TITLE
LPS-105380 PropertiesBuildIncludeDirsCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang is there a way to detect that ".ignore" instead of using a property?

**Comment by ling-alan-huang** [comment]
@hhuijser, I know what you mean, detect that .ignore, use it to exclude files, then run SF, right?

I am trying it today. closing.

**Comment by hhuijser** [comment]
@ling-alan-huang, correct. In this case, when it happens for a new module, SF will be smart enough to detect, instead of us having to add a property value.

Thanks!

**Pull request closed without merging**
