### PR TITLE
LPS-105380 BaseEmptyLinesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/7ba292a48fc92ff931af740199bcbdc55577a143

Related pulls:
7.3.x: https://github.com/ling-alan-huang/liferay-portal-ee/pull/256
7.2.x: https://github.com/ling-alan-huang/liferay-portal-ee/pull/257
7.1.x: https://github.com/ling-alan-huang/liferay-portal-ee/pull/258
7.0.x: https://github.com/ling-alan-huang/liferay-portal-ee/pull/259

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
