### PR TITLE
LPS-104810 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
@hhuijser @gamerson, Please ask BChan to publish, 

1. portal-tools-bundle-support
2. gradle-plugins-workspace
3. project-templates-extensions
4. project-templates-*
5. project-templates

Thanks!

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/81426

**Pull request closed without merging**
