### PR TITLE
LPS-141904 SetUtilMethodsCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/f8c2e242400e17e83d2e2342e5c3db6059895b92

Related pulls:
https://github.com/ling-alan-huang/liferay-portal/pull/547
https://github.com/ling-alan-huang/liferay-portal/pull/548

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Related pulls:
https://github.com/ling-alan-huang/liferay-portal/pull/547
https://github.com/ling-alan-huang/liferay-portal/pull/548

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/109337

**Pull request closed without merging**
