### PR TITLE
LPS-115709

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
Those two test integration failures were fixed here https://github.com/brianchandotcom/liferay-portal/pull/95824. Therefore, they won't fail in this run(At least they shouldn't).

**Comment by hhuijser** [comment]
Thanks @rafaprax 

Been sent to Brian: https://github.com/hhuijser/liferay-portal/pull/5060

**Pull request closed without merging**
