### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@xbrianlee @rodrigocunhaa are the permission checker test failures related?

@inacionery @rodigocunhaa another PR blocked for `ProcessMetricResourceTest.testGetProcessMetricsPageWithSortString`

**Comment by xbrianlee** [comment]
@jpince Not related

@austinchiang Can you ask your team to look into the permission test failures? The `PermissionCheckerTest` failure ([LPS-110425](https://issues.liferay.com/browse/LPS-110425)) is caused by [LPS-113282](https://issues.liferay.com/browse/LPS-113282). The Workflow one might be too.

**Comment by rodrigocunhaa** [comment]
@jpince , doesn't seem to be related. I reopened this ticket [LPS-111600](https://issues.liferay.com/browse/LPS-111600) and I'll ask the team to take a look.

**Comment by jpince** [comment]
@xbrianlee would you be able to send an ignore for those tests, for now? Then at least Hugo can retest these PRs tonight while Austin/Lima look into the failures.

**Comment by xbrianlee** [comment]
@jpince Sent in https://github.com/brianchandotcom/liferay-portal/pull/88991. Added comments in [LPS-110425](https://issues.liferay.com/browse/LPS-110425) and [LPS-111600 ](https://issues.liferay.com/browse/LPS-111600) to revert the ignores once the tests are fixed.

cc/ @rodrigocunhaa

**Comment by xbrianlee** [comment]
ci:forward

Ignores have been merged upstream

**Comment by hhuijser** [comment]
@xbrianlee @jpince, now I am getting a compile error?!
Doesn't seem related to my commits :(

**Comment by hhuijser** [comment]
resent: https://github.com/hhuijser/liferay-portal/pull/4290

**Pull request closed without merging**
