### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@hhuijser I think this line needs to be updated to get rid of the unresolved requirement error https://github.com/liferay/liferay-portal/blob/master/modules/apps/alloy/alloy-mvc/bnd.bnd#L8

**Pull request closed without merging**
