### PR TITLE
LPS-84119 Fix missing empty line

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/a51a7b350819a0f925bece4e508bd533196b74f8

I only fixed missing empty line issue, not inline for Map<>.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
@ling-alan-huang 

Your regex is too dangerous:
- `\t*` at the start of the regex is meaningless. Something starting with like this `aA<` would still your regex. You probably want something like `[\t\n][A-Z]\\w+`
- Having `<.+>` combined with `Pattern.DOTALL` results in matching pretty much everything, since it's okay if we have `<` on line 1 and '>' on line 1000

Regarding the inlining of `Map<>`. This is something that you don't have to worry about. It's inside a Checkstyle check and I am working on applying that one to jsp soon. Let's talk about that tonight.

**Comment by ling-alan-huang** [comment]
Hi @hhuijser,

I added some additional commits.

Let me explains about [LPS-84119 Fix regex, looking behind](https://github.com/hhuijser/liferay-portal/pull/3876/commits/32652e2130c84546e83a6b8b911cdc63b9fcfa8b):

Example:
```
<%
Group liveGroup = layoutsAdminDisplayContext.getLiveGroup();
LayoutSet selLayoutSet = layoutsAdminDisplayContext.getSelLayoutSet();
boolean showButtons = GroupPermissionUtil.contains(permissionChecker, layoutsAdminDisplayContext.getSelGroup(), ActionKeys.MANAGE_LAYOUTS) && SitesUtil.isLayoutSetPrototypeUpdateable(selLayoutSet);
%>
```

```
private static final Pattern _setVariablePattern = Pattern.compile(
    "[\n\t][A-Z]\\w+(<.+>)? (\\w+) =\\s+((?!\\{\n).)*?;\n", Pattern.DOTALL);
```

Without this commit, regex only matches line 1 and line 3, because the regex already ate `\n` which is the last part thing in the regex.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang, I thought that would have been the reason for your initial change in the regex.
That's the correct way to fix it. Very nice!

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/81176

Related ee pulls:
https://github.com/brianchandotcom/liferay-portal-ee/pull/27708
https://github.com/brianchandotcom/liferay-portal-ee/pull/27709
https://github.com/brianchandotcom/liferay-portal-ee/pull/27710

**Pull request closed without merging**
