### PR TITLE
LPS-74872 Check JavaTerm metadata line breaks

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by hhuijser** [comment]
@petershin 

This cannot be right: https://github.com/petershin/liferay-portal/blob/59a1edc9348fff0a62723033990f96c1fe1d1433/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/parser/JavaClassParser.java#L328

`line.contains(_JAVA_TERM_DEFINITION_REGEX)` should be `line.matches(_JAVA_TERM_DEFINITION_REGEX)`

Your tests should have caught that?

**Comment by petershin** [comment]
@hhuijser 

Hi Hugo, this is to catch cases like this [BundleServletContextAdapter.java#L107](https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/export-import/export-import-resources-importer/src/main/java/com/liferay/exportimport/resources/importer/internal/extender/BundleServletContextAdapter.java#L107)

The check will allow the new metadata logic to work well with the current JavaTerm parsing logic.

**Comment by hhuijser** [comment]
@petershin, I understand that.
Just saying that `line.contains(_JAVA_TERM_DEFINITION_REGEX)` cannot be correct.

Can you resend?

**Comment by petershin** [comment]
Sent with the [changes](https://github.com/hhuijser/liferay-portal/pull/3033).  Sorry about the delay, I was on pto last Friday

**Pull request closed without merging**
