### PR TITLE
LPS-78407 Cannot find symbol "Function" when building the portal

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
@hhuijser  this is not a customer issue.  just master can not build today.

**Comment by daviddotzhang** [comment]
closed it, this one is fixed.

**Comment by hhuijser** [comment]
@daviddotzhang, for these kind of failures, we usually just let whoever broke it take care of it :)

**Comment by daviddotzhang** [comment]
@hhuijser  got it. thanks!

**Pull request closed without merging**
