### PR TITLE
LPS-104679 Apply Checkstyle to jsp_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

I added some checks to jsp.

**Related pulls:**
master-private: no violations
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/2996
7.2.x-private: no violations
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/2997
7.1.x-private: no violations
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/2998
7.0.x-private: https://github.com/hhuijser/liferay-portal-ee/pull/2999

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Hey @ling-alan-huang. Nice work on this.

A few comments though:
- for https://github.com/hhuijser/liferay-portal/pull/3880/commits/eaf9ebf7990b74b107b66f090f83a894310cfd36, some of the initial capacity for the `StringBundler` is now incorrect
- for https://github.com/hhuijser/liferay-portal/pull/3880/commits/0413cfd85969c07985959dbe52e0069efba232ef, this commit makes me a bit nervous. It's so easy to break stuff with commits like these (I can't really tell from the test results if this commit is good or not)  I think checks like `FullyQualifiedNameCheck` we should not apply to jsp, because it checks against the imports, which are too different between `java` and `jsp`

We should carefully check the logic in each `*Check` and decide if it makes sense to apply for *.jsp

**Comment by ling-alan-huang** [comment]
Closing, I will resend.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/3883

**Pull request closed without merging**
