### PR TITLE
LPS-65213 Add connection rule for upgrades and verifies

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @Preston-Crary 

I see you got quite a few  exception cases in source-formatter.properties.
There is no pattern for these that we can somehow detect and make SF smart enough to exclude these?

**Comment by Preston-Crary** [comment]
Here's the list of files with cases:

These open connections in separate threads, I considered re-writing UpgradeCompanyId to use ThrowableAwareRunnable and check for that - we could still do that to have less excludes:
UpgradeCompanyId
VerifyAuditedModel
VerifyGroupedModel
VerifyResourcePermissions
VerifyUUID

I considered hardcoding these to be excluded:
BaseUpgradeTableImpl
UpgradeProcess
UpgradeProcessUtil

This one is where I decided that perhaps having a property would be better to prevent having to change the SF to allow for new cases as we write new upgrade base classes:
BaseKaleoUpgradeTableListener

I wasn't happy about adding the property but it seemed like the most maintainable way to do this to me.  If you have a different idea I'd like to know.

**Comment by hhuijser** [comment]
Okay, let's add the check for ThrowableAwareRunnable, that will reduce the exclusions we'll have to add in the future with quite a bit, I think.

It's also just annoying for developers that they get a warning for a false positive, without a good idea of what's going on...

Do you mind resending?

Thanks!

**Comment by Preston-Crary** [comment]
See https://github.com/hhuijser/liferay-portal/pull/2646

**Pull request closed without merging**
