### PR TITLE
Lps 76335 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by hhuijser** [comment]
@arthurchan35 

1. Tests are broken. Looks like it's related to your changes?

2. With your fix, it seems that now that the address `test@liferay.com.`, which used to be a valid address with the old code, now no longer is a valid address. From the commit messages I can't see if you changed that intentionally or not. If this is an intentional change, make sure you document that properly, with a link to the IETF standards that explain that change.

Please resend.

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Drew for review: https://github.com/drewbrokke/liferay-portal/pull/395

**Pull request closed without merging**
