### PR TITLE
LPS-94466 Fixes imports rely on exported classes and not on internal path structure

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Hugo!

Here's the manual work I did to bring some dependencies into place. Ideally, we should send a SF rule to enforce this in the future and prevent it from breaking loose again :)

In general, because of how we assemble our frontend code, only one version of some modules will be running at the same time in runtime and it will usually be (and should be) shared among all modules. These dependencies are:
- **clay** and all **clay-***
- **metal** and all **metal-***
- **senna**

So, to start, we'd need a rule to check that:
1. In a package.json
2. In the dependencies block
3. The versions of some dependencies match those in a given list:
    a. `clay` and `clay-*` package versions should match those specified in [frontend-taglib-clay/package.json](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/package.json#L22-L50)
    b. `metal` and `metal-*` package versions should match those specified in [frontend-js-metal-web/package.json](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-metal-web/package.json#L3-L35)
    c. `senna` package versions should match that specified in [frontend-js-spa-web/package.json](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-spa-web/package.json#L6)

In the future, we might extend that list to other modules, just in case this somehow changes your approach.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:test

**Comment by hhuijser** [comment]
Added check to SF and sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/72033

**Pull request closed without merging**
