### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@yichenroy can you please take a look at the snippet from the unresolved requirement error? This is what I really need to see:
```
    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.monitoring [284]
    [junit]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.portlet; version="[10.0.0,10.1.0)"
```

**Comment by yichenroy** [comment]
@jpince ticket for this: https://issues.liferay.com/browse/LRCI-1296

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@hhuijser sorry I wasn't clear, there is a real issue with this pull. It's this line https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal/portal-monitoring/bnd.bnd#L5. Based on the history of that file, I think it's ok if you just bump it to [10.1.0,10.2), just cc/ shuyangzhou on the pull request.

**Pull request closed without merging**
