### PR TITLE
LPS-84119 Yaml issue

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

**Issue:** https://liferay.slack.com/archives/CKZUHUWHX/p1580246114018400

The engineer reported that the lists(which start with "-") in yaml shouldn't be sorted because they are in logical order.

This is the original file from the engineer:

```
---
-
    become: true
    hosts: jenkins_slaves
    name: Cache GitHub repos on slaves
    serial: '{{ parallel_slaves | default("10") }}'
    tasks:
        -
            name: Install Git
            package:
                name: git
                state: present
        -
            copy:
                content: '{{ id_rsa_continuous-integration }}'
                dest: /home/rancher/.ssh/id_rsa_continuous-integration@liferay.com
                mode: 384
                owner: rancher
            name: Deploy SSH key
        -
            git:
                accept_hostkey: true
                dest: '/data/slaves/{{ containers[0].hostname }}/git/liferay/{{ item }}'
                repo: 'git@github-dev.liferay.com:liferay/{{ item }}.git'
                ssh_opts: |
                    -i /home/rancher/.ssh/id_rsa_continuous-integration@liferay.com
                    -o UserKnownHostsFile=/dev/null
                update: '{{ update_git_repos | default("false") }}'
            loop: '{{ github_repos }}'
            name: Cache Liferay GitHub repos
            register: gitrepos
        -
            git_config:
                name: remote.upstream.url
                repo: '/data/slaves/{{ containers[0].hostname }}/git/liferay/{{ item }}'
                scope: local
                value: 'git@github.com:liferay/{{ item }}.git'
            loop: '{{ github_repos }}'
            name: Set upstream url
            when: gitrepos.changed
        -
            git_config:
                name: remote.upstream.fetch
                repo: '/data/slaves/{{ containers[0].hostname }}/git/liferay/{{ item }}'
                scope: local
                value: '+refs/heads/*:refs/remotes/upstream/*'
            loop: '{{ github_repos }}'
            name: Set upstream fetch
            when: gitrepos.changed
        -
            git_config:
                name: remote.origin.url
                repo: '/data/slaves/{{ containers[0].hostname }}/git/liferay/{{ item }}'
                scope: local
                value: 'git@github.com:brianchandotcom/{{ item }}.git'
            loop: '{{ github_repos }}'
            name: Set origin url
            when: gitrepos.changed
        -
            git_config:
                name: remote.origin.fetch
                repo: '/data/slaves/{{ containers[0].hostname }}/git/liferay/{{ item }}'
                scope: local
                value: '+refs/heads/*:refs/remotes/origin/*'
            loop: '{{ github_repos }}'
            name: Set origin fetch
            when: gitrepos.changed
        -
            get_url:
                dest: /usr/local/bin/lms
                url: 'https://github.com/wchang22/LuminS/releases/download/v0.3.0/lms'
                mode: 493
            name: Download lms
        -
            command: '/usr/local/bin/lms sync /data/slaves/{{ containers[0].hostname }} /data/slaves/{{ item.hostname }}'
            loop: '{{ containers[1:] }}'
            name: Duplicate Git repos
            when: gitrepos.changed
```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
@hhuijser , SF failure is not related to my changes.

@kenjiheigel, please see sf failure, can we add it to `source-formatter-suppressions.xml`?

**Comment by kenjiheigel** [comment]
@ling-alan-huang, yeah feel free to add it to suppressions. I'll fix it for reals in a follow up pull in https://issues.liferay.com/browse/POSHI-49

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/84965

**Pull request closed without merging**
