### PR TITLE
LPS-101108 Integrate whatever logic we have in XMLFormatter and move to SF

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Related pulls:
7.1.x: hhuijser/liferay-portal-ee#2949
7.0.x: hhuijser/liferay-portal-ee#2948

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not relate to my changes.

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/78118
Check my changes

**Pull request closed without merging**
