### PR TITLE
LPS-95915 Add SF rules for YAML

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-95915

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:revelant

**Comment by hhuijser** [comment]
@ling-alan-huang you can ignore the `GC overhead limit exceeded` error.
This one shoudl fix that issue: https://github.com/brianchandotcom/liferay-portal/pull/73582/commits/5ee6047367cd84a1e6ca6f8f42b85b2bb5369edd

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/73651

**Pull request closed without merging**
