### PR TITLE
LPS-113863 Use liferayPortletResponse.getNamespace()-20200621-1

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

I will fix all violations before send fix.

Issue:

> Brian Chan  1:24 AM
> Hey guys, in JSPs, whereever we have "renderResponse.getNamespace()", or *Response.getNamespace" can you change it to "liferayPortletResponse.getNamespace()
> 1:25
> See portal master 4a701e42d4e8f1e3a11cdcd73952cbe063a8cb1a and dc406dea9d031fd3209834c64a6e1857faa9c69d for more context. Ppl are spending time fixing bugs changing renderResponse, but the proper fix is liferayPortletResponse which will work 100% of the time.
> 
>

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:bundle

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
