### PR TITLE
 LPS-84119 Auto SF

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser,

See: https://github.com/brianchandotcom/liferay-portal/pull/77613#issuecomment-525904268

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
This is already in by now

**Pull request closed without merging**
