### PR TITLE
[TS] LPS-80957

### PR DESCRIPTION
**Pull request by yuhai**
Hi Hugo,

**The first commit** refers to https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/common/themes/portlet_css.jspf#L180-L211 to fix when ufaMargin=false.  Only Border Width, Padding and Margin have UNIT(%,px,em).  We can use (!_unitSet.contains(marginTopValue) to solve the issue. 

For example, when ufaBorderWidth is false, the borderWidth value will be as the below.
`{"top":{"unit":"%","value":""},"left":{"unit":"%","value":""},"bottom":{"unit":"%","value":""},"right":{"unit":"%","value":""},"sameForAll":false}`

**The second commit**: when ufaBorderWidth =true, the logic is using top value as the whole value. 
For example, the borderWidth value will be as the below.
{"top":{"unit":"%","value":""},"left":{"unit":"","value":""},"bottom":{"unit":"","value":""},"right":{"unit":"","value":""},"sameForAll":true}

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
Hi @hhuijser 

You are right. The fix will affect LPS-34387. However, I think the fix is right and LPS-34387 fix is wrong. Please refer to the reasons:

1. LPS-34387 fix invoke the issue on Margin, Padding and BorderWidth.
2. For Border Styles (LPS-34387 reported issue), the issue should be caused by wrong type. I just append the commit to expose it. Please refer to https://github.com/hhuijser/liferay-portal/pull/3302/commits/7b0b0f7fc5a37e725862b61c79f7553084dbc5c2. The wrong type was added by https://github.com/liferay/liferay-portal/commit/8ac1137c56d5a1f5658b1d066b30f9cbd2424e8d.

Without border-width setting, border-style can be used by alone. Please refer to https://www.w3schools.com/cssref/tryit.asp?filename=trycss_border-width4, you may remove the **border-width: 1px;** to check the input.

If my understanding is right, should we use the revert commit as the first commit, instead of the current fix? And then append the commit https://github.com/hhuijser/liferay-portal/pull/3302/commits/7b0b0f7fc5a37e725862b61c79f7553084dbc5c2

Thanks,
Hai

**Comment by hhuijser** [comment]
@yuhai @Seiphon let's not revert a commit from 5 years ago.
Just wanted to make sure you had checked that old ticket. Can you link those two tickets and document on the LPS?

I reviewed and send to Jon Mak: https://github.com/jonmak08/liferay-portal/pull/1900

**Comment by yuhai** [comment]
thanks, Hugo.  
done. :)

**Pull request closed without merging**
