### PR TITLE
LPS-105380 Enforce name of var to match type for type 'SearchRequest' and 'SearchResponse'

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/6d06c51ef0c9e0e9ea2d0c08438324aa9da81f6e

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4861

**Pull request closed without merging**
