### PR TITLE
LPS-135504

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by nikki-pru** [comment]
Hi @hhuijser,
It looks like the changes to this file: https://github.com/hhuijser/liferay-portal/commit/3b0adfe5138718dbe866cf9121d74ebc939d0687#diff-18d26abadc4366cbe2f4fc3db3443621180c6d5c8eea0a748be56e713fcd5a92
is causing the [failures](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8137/) indicated in this PR. 
[Testray shows](https://testray.liferay.com/home/-/testray/cases/1546914511) that the tests in the previous link consistently passes otherwise.

**Comment by hhuijser** [comment]
Thanks @nikki-pru !

@Preston-Crary can you check why that file would be breaking stuff?

**Comment by Preston-Crary** [comment]
Please see https://github.com/hhuijser/liferay-portal/pull/5938

**Pull request closed without merging**
