### PR TITLE
LPS-84119 Add check for test.properties

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

**Issues:**
https://github.com/liferay/liferay-portal/commit/01d6d7df697c4cb61e7fbc7db781ecf74a50a430
https://github.com/liferay/liferay-portal/commit/b20586d3ae75796fe104ee313a4632f26143d61d
https://github.com/liferay/liferay-portal/commit/d67fd54b5030d1e6b6cfb3ff515964c1d075361e

I added check for test.properties, if it's good to you, I will try to apply it to *properties.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang, why don't we apply this to other *.properties files?
Do we have properties where we don't want alphabetical ordering?

**Comment by ling-alan-huang** [comment]
@hhuijser, yes, we have some values that are not in alphabetical order.
I just list some of them:

https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L2305
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L2678 
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L2882
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L5939
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L11827

**Comment by hhuijser** [comment]
I see... it worries me to automatically sort things, when order **does** matter in quite a few cases.

**Comment by ling-alan-huang** [comment]
**Note:**
```
Hugo Huijser:city_sunset:  12:27 PM
Thing is that order matters for a bunch of them. we can either whitelist or blacklist, what's yoru opinion?
12:28
Examples where order matters:
12:28
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L2305
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L2678
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L2882
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L5939
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal.properties#L11827

Brian Chan  12:29 PM
whitelist
12:30
I care mainly about the test ones.
12:30
the test.proeprties since QA is usually sloppier
12:30
so regex whitelist

Hugo Huijser:city_sunset:  12:30 PM
k, sounds good
```

**Comment by ling-alan-huang** [comment]
Closing, I will resend.

**Pull request closed without merging**
