### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by wincent**
Adds one commit on top of https://github.com/hhuijser/liferay-portal/pull/4093

I don't think it was complaining about the lines that your PR touched, Hugo. But seeing as those files were touched, Prettier checked and formatted the entire file, and found that the formatting was wrong. The bad formatting seems to have been added in 60baf5388b0500885d257bdcf00d52d8281f4c0a and d1ae251381e839b39424807496a81607d8188b03, which correspond to:

- https://github.com/brianchandotcom/liferay-portal/pull/85435
- https://github.com/brianchandotcom/liferay-portal/pull/85423

Both of those got merged despite failing `ci:test:sf`.

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
No idea what that rebase error is about. Will try once more and if that doesn't work will do manual rebase myself.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
Ok, two rebase errors in a row. Going to push a manual rebase.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
```
There should be an empty line before line '278', as we finished referencing variable 'gson', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/missing_empty_line_check.markdown: ./modules/apps/data-engine/data-engine-rest-impl/src/main/java/com/liferay/data/engine/rest/internal/dto/v2_0/util/DataLayoutUtil.java
```

Looks like one more SF needed.

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
Closing as no longer relevant.

**Comment by hhuijser** [comment]
@wincent it's on my list, just low priority, so I'll get to it later. thanks for the help!

**Pull request closed without merging**
