### PR TITLE
LPS-109807 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
cc @gamerson & @david-truong,

This will turn ON our 3 NPM project templates for 7.2 and 7.3 again. We don't have to make an announcement on this until we drop support for standalone gradle.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/85905

**Pull request closed without merging**
