### PR TITLE
LPS-105380 BaseTagAttributesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

_Issue:_
https://github.com/liferay/liferay-portal/commit/1e0c984904ae473ebf6b4eae8d18191641a730a0?branch=1e0c984904ae473ebf6b4eae8d18191641a730a0&diff=unified

_Related pull:_
7.3.x: https://github.com/hhuijser/liferay-portal-ee/pull/3196
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3197
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3198

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:reevaluate:1212004_7515

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
