### PR TITLE
LPS-74849

### PR DESCRIPTION
**Pull request by petershin**
Hi Hugo,

The portal-kernel.jar has a lot of dependencies.

The StringBundler class is also in [petra-string](https://github.com/liferay/liferay-portal/blob/master/modules/core/petra/petra-string/src/main/java/com/liferay/petra/string/StringBundler.java) and your [last commit](https://github.com/hhuijser/liferay-portal/pull/3056/commits/4bdaabd35aa94fffec9774b904370d2ba80b1646) changed one module to use that jar.

Would it be ok to use the petra-string jar everywhere?

/cc @shuyangzhou

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@petershin 

Shuyangs team is working on changing all usage of StringBundler to use petra. I'll leave that to them. Just fixing this one as it was giving problems.

**Comment by petershin** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/52642

**Pull request closed without merging**
