### PR TITLE
LPS-58438

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
he pull request extends from https://github.com/juliocamarero/liferay-portal/pull/3652


Please see the fix logic from Julio.
https://github.com/juliocamarero/liferay-portal/pull/3652#issuecomment-140436899

Please see the fix explanation:
https://github.com/juliocamarero/liferay-portal/pull/3652#issuecomment-140651634

**Comment by hhuijser** [comment]
@yuhai 

In the VerifyProcess, we are now setting the expirationDate of the latest version to all articles without checking the journal.article.expire.all.versions property. Isn't that a bit too aggressive?

**Comment by yuhai** [comment]
Hi Hugo,

Sorry, I forgot that. this is wrong and we should add that logic.

Thanks,
Hai

**Comment by hhuijser** [comment]
@yuhai 

I think doing the logic in VerifyProcess (even when checking for the property journal.article.expire.all.versions) is a bit too aggressive.

The documentation for that property says:
# Set this to true to expire all article versions when expiring an article. Set
# this to false to only expire the latest approved article version when expiring
# an article.

Let's say I have had that property set to false for a while now and now I decide to set it to true, that doesn't mean I necessarily want all my old articles to be effected? It only says it will do it "when expiring an article".

What do you think?

**Comment by yuhai** [comment]
Hi Hugo,

Firstly, I want to explain that property explanation has some confusion. LPS-53479 fix the issue so that when the latest version of article is expired, we set the article is expired. That is to say, no matter what the property is true or false. It only check the latest version whether be expired.

I think I have similar focus from https://github.com/juliocamarero/liferay-portal/pull/3652#
But for now logic, we can skip it.

For your mentioned case, for example,

1. When set false. we have two articles A and B. If A latest approved version's expireDate is not null and B latest approved version's expireDate is null.
2. Change the true, we only change article A. This fits with our property's explanation. Because once set true and our listener works, the article also will be expired.

I think I can understand your meaning. If the end users still change the property between true and false, once the verify works, some articles might be changed. For setting true, our logic is setting all old versions have some expireDate if its latest approved version expireDate is not null.

From another viewpoint. If that property set to false for a while now, and we have some latest approved version's expireDate is not null. If we don't change those data which were created when the property is false. After change true, the issue will occur.(asset publisher will display the old version).

Thanks,
Hai

**Comment by yuhai** [comment]
Hi Hugo,

I don't have better solution to fix those old datas.
Please kindly give some guidance regarding this. :)

Thanks,
Hai

**Comment by hhuijser** [comment]
Won't the listener take care of that? This was only a problem for a short while (between the moment of expiring and the listener running)?

**Comment by hhuijser** [comment]
Closing, Hai will resend...

**Pull request closed without merging**
