### PR TITLE
LPS-105380_BNDCategoryCheck_20200924

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue:
https://github.com/brianchandotcom/liferay-portal/pull/92034#discussion_r463625272

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
See: https://github.com/hhuijser/liferay-portal/pull/4894

**Pull request closed without merging**
