### PR TITLE
 [Auto SF] LPS-130505 UnnecessaryMethodCallsCheck Auto SF_11

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
What's `ReleaseInfo` doing in there?

**Comment by ling-alan-huang** [comment]
That one happens sometimes, I close this pull, because I will rework UnnecessaryMethodCallsCheck.

**Pull request closed without merging**
