### PR TITLE
LPS-105380 AssertEqualsCheck, use Assert.assertTrue and Assert.assertFalse

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/brianchandotcom/liferay-portal/commit/61068ea5d596bfc10e71c47edb4190548a420efc

We can't simply replace `Assert.assertEquals(faluse` with `Assert.assertFalse(`,
because we need typecase for some cases: https://github.com/hhuijser/liferay-portal/commit/3731ea8fdc5bcfb30477dfb5febc9a7c8f8baec6#diff-962ae1fc4457698f6074fea2c6a09272fc41857144ce5ce1b0198b95ddd8e77aR160

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang can we use `GetterUtil.getBoolean` to typecast?

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
