### PR TITLE
LPS-105380 XMLWorkflowDefinitionFileNameCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
Hey @hhuijser can you check 1f1b1aa again, see: https://github.com/liferay/liferay-portal/commit/71ab5c30d20de9a1cd91665118c3578cc687e34c#diff-91fdcdec1ef9cd76eaf5b5a8d898bde5c77455a89f6f8e469ed8b8ac5c14b6f4L183-L184

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/5733

**Pull request closed without merging**
