### PR TITLE
LPS-84119 JSP Style

### PR DESCRIPTION
**Pull request by ling-alan-huang**
@hhuijser,

Issue 1: https://github.com/liferay/liferay-portal/commit/7e76f571287c1238ce202fb9548398808ca7a0f2

Issue 2: Jsp Style  Check

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@ling-alan-huang @hhuijser I pushed just the disable commit e936fc4 directly to BChan https://github.com/brianchandotcom/liferay-portal/pull/87721. I modified the commit message slightly to reflect the cause.

**Comment by ling-alan-huang** [comment]
Rebase and retest.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
