### PR TITLE
LPS-129341 ToolsUtily

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Hugo,
Issue: https://issues.liferay.com/browse/LPS-129341

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
