### PR TITLE
LPS-15380 PoshiEmptyLinesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/aa4e474063f4ba1e4036da7a8a84755b9bec290b

Related pulls:
7.3.x: https://github.com/ling-alan-huang/liferay-portal-ee/pull/204
7.2.x: https://github.com/ling-alan-huang/liferay-portal-ee/pull/205
7.1.x: https://github.com/ling-alan-huang/liferay-portal-ee/pull/206
7.0.x: https://github.com/ling-alan-huang/liferay-portal-ee/pull/207

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
