### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@rodrigocunhaa @cvanut Please see forms and workflow POSHI test failures on the second test run. Passed on the first.

**Comment by rodrigocunhaa** [comment]
Hi @jpince , I fixed those testes here: https://github.com/rodrigocunhaa/liferay-portal/pull/103
(There was a change on a HTML tag which made many Workflow testes start to failing)

**Comment by jpince** [comment]
@rodrigocunhaa was that a workflow or FI (Frontend Infrastructure) change? If it was FI, please contact John Co so FI is running the right tests when making changes.

**Comment by cvanut** [comment]
Hey @jpince 
The error on Forms tests is due to this issue: [LPS-115498](https://issues.liferay.com/browse/LPS-115498). Front-end infrastructure team is aware of the bug and working on it.
`Element is not present at "//a[contains(@class,'nav-link')]//span[contains(text(),'Rules')]/../../a`

**Comment by jpince** [comment]
@cvanut should that test be quarantined, then?

**Comment by cvanut** [comment]
Yes @jpince. We'll add the tests related to rules to quarantine and monitore the bug fix. As soon as the fix is merged, we'll remove the tests from quarantine. 
Thanks.

**Comment by cvanut** [comment]
@jpince tests added to quarantine. We'll track the bug fix. 
https://issues.liferay.com/browse/LRQA-59470

**Comment by rodrigocunhaa** [comment]
@jpince , yes, it was FI. I'll contact John Co. Thanks!

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
Resent here with quarantines https://github.com/hhuijser/liferay-portal/pull/4426

fyi @rodrigocunhaa

**Comment by brianwulbern** [comment]
ci:test:bundle

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4430

**Pull request closed without merging**
