### PR TITLE
LPS-77404 expand timer action and nofication elements so that they ac…

### PR DESCRIPTION
**Pull request by arthurchan35**
…cept task execution type to match frontend

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Inacio for review: https://github.com/inacionery/liferay-portal/pull/141

**Pull request closed without merging**
