### PR TITLE
LPS-67565

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

I changed something after your changes: https://github.com/brianchandotcom/liferay-portal/pull/78212, so I use the same LPS number.

**Issue:**
**Before SF:**
```
@Component(
	immediate = true,
	property = {
		...
		...
		"javax.portlet.init-param.template-path=/META-INF/resources/",
		"javax.portlet.init-param.view-template=/polls_display/view.jsp",
		"javax.portlet.name=" + PollsPortletKeys.POLLS_DISPLAY,
		"javax.portlet.resource-bundle=content.Language",
		"javax.portlet.security-role-ref=power-user,user",
		"javax.portlet.supports.mime-type=text/html"
	},
	service = Portlet.class
)
public class PollsDisplayPortlet extends MVCPortlet {
}
```

**After SF:**
```
@Component(
	immediate = true,
	property = {
		...
		...
		"javax.portlet.init-param.config-template=/polls_display/configuration.jsp",
		"javax.portlet.init-param.template-path=/META-INF/resources/",
		"javax.portlet.init-param.view-template=/polls_display/view.jsp",
		"javax.portlet.name=" + PollsPortletKeys.POLLS_DISPLAY,
		"javax.portlet.resource-bundle=content.Language",
		"javax.portlet.security-role-ref=power-user,user",

	, "javax.portlet.portlet-mode=text/html;config"},
	service = Portlet.class
)
public class PollsDisplayPortlet extends MVCPortlet {
}
```

**SFDebug console:**
```
■Start formatting on /home/alan/liferay_code/7.0.x/7.1.x-liferay-portal-ee/modules/apps/polls/polls-web/
Loading jar:file:/home/alan/SFDebug/otherjars/portal-impl.jar!/system.properties
/home/alan/liferay_code/7.0.x/7.1.x-liferay-portal-ee/modules/apps/polls/polls-web/src/main/java/com/liferay/polls/web/internal/portlet/PollsDisplayPortlet.java:55:2: expecting RCURLY, found ','
/home/alan/liferay_code/7.0.x/7.1.x-liferay-portal-ee/modules/apps/polls/polls-web/src/main/java/com/liferay/polls/web/internal/portlet/PollsDisplayPortlet.java:57:1: expecting IDENT, found ')'
/home/alan/liferay_code/7.0.x/7.1.x-liferay-portal-ee/modules/apps/polls/polls-web/src/main/java/com/liferay/polls/web/internal/portlet/PollsDisplayPortlet.java:55:2: expecting RCURLY, found ','
/home/alan/liferay_code/7.0.x/7.1.x-liferay-portal-ee/modules/apps/polls/polls-web/src/main/java/com/liferay/polls/web/internal/portlet/PollsDisplayPortlet.java:57:1: expecting IDENT, found ')'
/home/alan/liferay_code/7.0.x/7.1.x-liferay-portal-ee/modules/apps/polls/polls-web/src/main/java/com/liferay/polls/web/internal/portlet/PollsDisplayPortlet.java (JavaParser)
/home/alan/liferay_code/7.0.x/7.1.x-liferay-portal-ee/modules/apps/polls/polls-web/src/main/java/com/liferay/polls/web/internal/portlet/PollsDisplayPortlet.java (SourceCheck:JavaComponentAnnotationsCheck)
/home/alan/liferay_code/7.0.x/7.1.x-liferay-portal-ee/modules/apps/polls/polls-web/src/main/java/com/liferay/polls/web/internal/portlet/PollsDisplayPortlet.java:55:2: expecting RCURLY, found ','
/home/alan/liferay_code/7.0.x/7.1.x-liferay-portal-ee/modules/apps/polls/polls-web/src/main/java/com/liferay/polls/web/internal/portlet/PollsDisplayPortlet.java:57:1: expecting IDENT, found ')'
```

**Related pulls:**
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/2958
7.1.x-private: https://github.com/hhuijser/liferay-portal-ee/pull/2957

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The SF failure is not related to my changes.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
The SF failure is not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/78424

**Pull request closed without merging**
