### PR TITLE
LPS-101108 Integrate whatever logic we have in XMLFormatter and move to SF

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

https://issues.liferay.com/browse/LPS-101108

Basically, task `formatXML` uses [XMLFormatter.java](https://github.com/liferay/liferay-portal/blob/master/modules/util/xml-formatter/src/main/java/com/liferay/xml/formatter/XMLFormatter.java#L60)->[Dom4jUtil.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/petra/petra-xml/src/main/java/com/liferay/petra/xml/Dom4jUtil.java#L56) to format XML.

Let me summarize what dose Dom4jUtil.java do:
1.  [SAXReader](https://github.com/liferay/liferay-portal/blob/master/modules/apps/petra/petra-xml/src/main/java/com/liferay/petra/xml/Dom4jUtil.java#L120)
I didn't integrate this logic to SF, because this logic will use something to recreate the xml.
For example: See [diff](https://github.com/ling-alan-huang/liferay-portal/pull/115/files#diff-7ae681e5fe4c5d36aba967e29afb78b1L2)
Some attributes were add by `SAXReader`, because this class will use [hibernate-mapping-3.0.dtd](https://github.com/liferay/liferay-portal/blob/master/definitions/hibernate-mapping-3.0.dtd#L325-L343) to recreate XML, and the added attributes are default values, I think we don't need this logic.

2. [Dom4jUtil.toString](https://github.com/liferay/liferay-portal/blob/master/modules/apps/petra/petra-xml/src/main/java/com/liferay/petra/xml/Dom4jUtil.java#L56-L101)
I checked this method, I found that the only one logic that SF does't have is replacing `"<?xml version="1.0" encoding="UTF-8"?>"` with `"<?xml version="1.0"?>"`

So I only integrate replacing `"<?xml version="1.0" encoding="UTF-8"?>"` with `"<?xml version="1.0"?>"` to SF(added XMLStylingCheck).

Related pulls:
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/2949
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/2948

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
Two files that are formatted are generated files.
Can you make sure SourceFormatter skips those files?

Please resend. Thanks!

**Comment by ling-alan-huang** [comment]
Resend: https://github.com/hhuijser/liferay-portal/pull/3755

**Pull request closed without merging**
