### PR TITLE
LPS-73823 remove the unnessary parameter in the URL

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Sergio for review: https://github.com/sergiogonzalez/liferay-portal/pull/3954

**Pull request closed without merging**
