### PR TITLE
LPS-105380 JSPTaglibVariableCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/43a5b587a3ad751e8e2f7675d2d65788563b191a

Related pulls:
7.3.x: https://github.com/hhuijser/liferay-portal-ee/pull/3239
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3238
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3237
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3236

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/102726

**Pull request closed without merging**
