### PR TITLE
Lps 87735 fix

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
Sent to Carlos for review: https://github.com/csierra/liferay-portal/pull/470

**Pull request closed without merging**
