### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
`FriendlyURL` errors might be real. @david-gutierrez-mesa what do you think?

**Comment by david-gutierrez-mesa** [comment]
yes, I think so

**Comment by hhuijser** [comment]
@jpince @david-gutierrez-mesa 
Failures happen before my commits. See https://test-1-1.liferay.com/userContent/jobs/root-cause-analysis-tool/builds/1797/jenkins-report.html

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
@nhpatt is this failing in upstream?
```
StructuredContentResourceTest.testGetStructuredContent
com.liferay.headless.delivery.client.problem.Problem$ProblemException
```

**Comment by nhpatt** [comment]
Yes :(, Brian reformated a test, should be fixed here: https://github.com/brianchandotcom/liferay-portal/pull/88213

**Comment by jpince** [comment]
Javier's fix in upstream here: https://github.com/liferay/liferay-portal/commit/d1d88c2427eca6bb8456fdc0960dbbd540269165
Also waiting for this one to get merged to upstream to fix the PortalLogAssertorTest: https://github.com/brianchandotcom/liferay-portal/commit/81ac7a786c55f7ae04564517ee854a4be2d9da39

**Comment by jpince** [comment]
ci:forward

**Pull request closed without merging**
