### PR TITLE
LPS-114565

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
flaky test: [AppBuilder#PublishAppsInStandaloneAndReuseItsViews](https://testray.liferay.com/home/-/testray/cases/1009252394)

@xbrianlee TikaException noting Search in the stacktrace (looks like it could be network related, if we can't extract text from a file):
```
  [junit] 02:07:16,060 WARN  [http-nio-8080-exec-10][FileImpl:476] Unable to extract text from 20200605020715767KSHPAOYG
    [junit] org.apache.tika.exception.TikaException: TIKA-198: Illegal IOException from org.apache.tika.parser.executable.ExecutableParser@51ddffed
    [junit] 	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:286)
    [junit] 	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
    [junit] 	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
    [junit] 	at com.liferay.portal.util.FileImpl._parseToString(FileImpl.java:1176)
    [junit] 	at com.liferay.portal.util.FileImpl.extractText(FileImpl.java:457)
    [junit] 	at com.liferay.portal.kernel.util.FileUtil.extractText(FileUtil.java:163)
    [junit] 	at com.liferay.portal.kernel.search.DocumentImpl.addFile(DocumentImpl.java:156)
    [junit] 	at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelDocumentContributor.contribute(DLFileEntryModelDocumentContributor.java:114)
    [junit] 	at com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelDocumentContributor.contribute(DLFileEntryModelDocumentContributor.java:61)
```

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4374

**Comment by xbrianlee** [comment]
@brianwulbern This looks very similar to https://issues.liferay.com/browse/LPS-113032 which also had Search classes in the stacktrace. The fix should be made per test most likely instead of in the Search classes.

@alexcandidos Perhaps you can ask your team to look at this and replicate the fix from the ticket above?

**Comment by Preston-Crary** [comment]
See https://github.com/Preston-Crary/liferay-portal/pull/1078

**Pull request closed without merging**
