### PR TITLE
LPS-99481 Add SF rules for YAML: Block Chomping Indicator

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
**SF failures No.1~30:**
```
     [java] 1: ./modules/private/apps/analytics/analytics-connector-web/build.gradle expected:<...t-api", version: "3.[1.0]"
     [java] 	compileOnly group...> but was:<...t-api", version: "3.[0.1]"
     [java] 	compileOnly group...>
     [java] 2: ./modules/private/apps/oauth/oauth-service/build.gradle expected:<...t-api", version: "3.[1.0]"
     [java] 	compileOnly group...> but was:<...t-api", version: "3.[0.1]"
     [java] 	compileOnly group...>

```
`build.gradle` version check. They are not related to my changes.
I don't want to format them in this pull request. I just want to make this pull clear.

------------------

**SF failures No.31:**
```
     [java] 31: ./modules/apps/portal-portlet-bridge/portal-portlet-bridge-soy-impl/package.json expected:<...": "3.0.0-milestone.[2]"
     [java] 	},
     [java] 	"name": "port...> but was:<...": "3.0.0-milestone.[1]"
     [java] 	},
     [java] 	"name": "port...>

```
This failure relates https://github.com/liferay/liferay-portal/commit/72f7b89ad5ebc2193c4feb65bc142636985d5cf8

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/77011

**Pull request closed without merging**
