### PR TITLE
LPS-84119 Add AttributeOrderCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Issue: https://github.com/liferay/liferay-portal/commit/7e258b02018cdd33c6d36783986f23eb90fd4ac6

This is the output of `SFDebugHelper.printStructure(detailAST):` for my testcases:
```
+--INSTANCE_INIT 33
    +--SLIST ({) 33
        +--EXPR 34
            +--ASSIGN (=) 34
                +--IDENT (dataDefinitionId) 34
                +--STRING_LITERAL ("") 34
        +--SEMI (;) 34
        +--EXPR 35
            +--ASSIGN (=) 35
                +--IDENT (appDeployments) 35
                +--LITERAL_NEW (new) 35
                    +--IDENT (AppDeployment) 35
                    +--ARRAY_DECLARATOR ([) 35
                        +--RBRACK (]) 35
                    +--ARRAY_INIT ({) 35
                        +--EXPR 36
                            +--LITERAL_NEW (new) 36
                                +--IDENT (AppDeployment) 36
                                +--LPAREN (() 36
                                +--ELIST 36
                                +--RPAREN ()) 36
                                +--OBJBLOCK 36
                                    +--LCURLY ({) 36
                                    +--INSTANCE_INIT 37
                                        +--SLIST ({) 37
                                            +--EXPR 38
                                                +--ASSIGN (=) 38
                                                    +--IDENT (type) 38
                                                    +--STRING_LITERAL ("productMenu") 38
                                            +--SEMI (;) 38
                                            +--EXPR 39
                                                +--ASSIGN (=) 39
                                                    +--IDENT (settings) 39
                                                    +--METHOD_CALL (() 41
                                                        +--DOT (.) 41
                                                            +--METHOD_CALL (() 39
                                                                +--DOT (.) 39
                                                                    +--IDENT (HashMapBuilder) 39
                                                                    +--TYPE_ARGUMENTS 39
                                                                        +--GENERIC_START (<) 39
                                                                        +--TYPE_ARGUMENT 39
                                                                            +--IDENT (String) 39
                                                                        +--COMMA (,) 39
                                                                        +--TYPE_ARGUMENT 39
                                                                            +--IDENT (Object) 39
                                                                        +--GENERIC_END (>) 39
                                                                    +--IDENT (put) 39
                                                                +--ELIST 40
                                                                    +--EXPR 40
                                                                        +--STRING_LITERAL ("scope") 40
                                                                    +--COMMA (,) 40
                                                                    +--EXPR 40
                                                                        +--LITERAL_NEW (new) 40
                                                                            +--IDENT (String) 40
                                                                            +--ARRAY_DECLARATOR ([) 40
                                                                                +--RBRACK (]) 40
                                                                            +--ARRAY_INIT ({) 40
                                                                                +--EXPR 40
                                                                                    +--STRING_LITERAL ("control_panel") 40
                                                                                +--RCURLY (}) 40
                                                                +--RPAREN ()) 41
                                                            +--IDENT (build) 41
                                                        +--ELIST 41
                                                        +--RPAREN ()) 41
                                            +--SEMI (;) 41
                                            +--RCURLY (}) 42
                                    +--RCURLY (}) 43
                        +--COMMA (,) 43
                        +--EXPR 44
                            +--LITERAL_NEW (new) 44
                                +--IDENT (AppDeployment) 44
                                +--LPAREN (() 44
                                +--ELIST 44
                                +--RPAREN ()) 44
                                +--OBJBLOCK 44
                                    +--LCURLY ({) 44
                                    +--INSTANCE_INIT 45
                                        +--SLIST ({) 45
                                            +--RCURLY (}) 46
                                    +--RCURLY (}) 47
                        +--COMMA (,) 47
                        +--EXPR 48
                            +--LITERAL_NEW (new) 48
                                +--IDENT (AppDeployment) 48
                                +--LPAREN (() 48
                                +--ELIST 48
                                +--RPAREN ()) 48
                                +--OBJBLOCK 48
                                    +--LCURLY ({) 48
                                    +--INSTANCE_INIT 49
                                        +--SLIST ({) 49
                                            +--EXPR 50
                                                +--ASSIGN (=) 50
                                                    +--IDENT (type) 50
                                                    +--STRING_LITERAL ("widget") 50
                                            +--SEMI (;) 50
                                            +--EXPR 51
                                                +--ASSIGN (=) 51
                                                    +--IDENT (settings) 51
                                                    +--LITERAL_NEW (new) 51
                                                        +--IDENT (HashMap) 51
                                                        +--TYPE_ARGUMENTS 51
                                                            +--GENERIC_START (<) 51
                                                            +--GENERIC_END (>) 51
                                                        +--LPAREN (() 51
                                                        +--ELIST 51
                                                        +--RPAREN ()) 51
                                            +--SEMI (;) 51
                                            +--RCURLY (}) 52
                                    +--RCURLY (}) 53
                        +--RCURLY (}) 54
        +--SEMI (;) 54
        +--RCURLY (}) 55
+--INSTANCE_INIT 37
    +--SLIST ({) 37
        +--EXPR 38
            +--ASSIGN (=) 38
                +--IDENT (type) 38
                +--STRING_LITERAL ("productMenu") 38
        +--SEMI (;) 38
        +--EXPR 39
            +--ASSIGN (=) 39
                +--IDENT (settings) 39
                +--METHOD_CALL (() 41
                    +--DOT (.) 41
                        +--METHOD_CALL (() 39
                            +--DOT (.) 39
                                +--IDENT (HashMapBuilder) 39
                                +--TYPE_ARGUMENTS 39
                                    +--GENERIC_START (<) 39
                                    +--TYPE_ARGUMENT 39
                                        +--IDENT (String) 39
                                    +--COMMA (,) 39
                                    +--TYPE_ARGUMENT 39
                                        +--IDENT (Object) 39
                                    +--GENERIC_END (>) 39
                                +--IDENT (put) 39
                            +--ELIST 40
                                +--EXPR 40
                                    +--STRING_LITERAL ("scope") 40
                                +--COMMA (,) 40
                                +--EXPR 40
                                    +--LITERAL_NEW (new) 40
                                        +--IDENT (String) 40
                                        +--ARRAY_DECLARATOR ([) 40
                                            +--RBRACK (]) 40
                                        +--ARRAY_INIT ({) 40
                                            +--EXPR 40
                                                +--STRING_LITERAL ("control_panel") 40
                                            +--RCURLY (}) 40
                            +--RPAREN ()) 41
                        +--IDENT (build) 41
                    +--ELIST 41
                    +--RPAREN ()) 41
        +--SEMI (;) 41
        +--RCURLY (}) 42
+--INSTANCE_INIT 45
    +--SLIST ({) 45
        +--RCURLY (}) 46
+--INSTANCE_INIT 49
    +--SLIST ({) 49
        +--EXPR 50
            +--ASSIGN (=) 50
                +--IDENT (type) 50
                +--STRING_LITERAL ("widget") 50
        +--SEMI (;) 50
        +--EXPR 51
            +--ASSIGN (=) 51
                +--IDENT (settings) 51
                +--LITERAL_NEW (new) 51
                    +--IDENT (HashMap) 51
                    +--TYPE_ARGUMENTS 51
                        +--GENERIC_START (<) 51
                        +--GENERIC_END (>) 51
                    +--LPAREN (() 51
                    +--ELIST 51
                    +--RPAREN ()) 51
        +--SEMI (;) 51
        +--RCURLY (}) 52
```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Looks very nice!
Are there any violations in the 7.x branches?
If so, can you fix those first before I send this to Brian?

**Comment by ling-alan-huang** [comment]
Hi @hhuijser,

I've sent related pulls below:

Branch | Fix Violations
------------ | -------------
master-private | no violations
7.2.x | https://github.com/hhuijser/liferay-portal-ee/pull/2992
7.2.x-private | https://github.com/hhuijser/liferay-portal-ee/pull/2993
7.1.x | https://github.com/hhuijser/liferay-portal-ee/pull/2994
7.1.x-private | no violations
7.0.x | https://github.com/hhuijser/liferay-portal-ee/pull/2995
7.0.x-private | no violations

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/81172

**Pull request closed without merging**
