### PR TITLE
LPS-121804_Python_20201013

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Peter helped us to integrate Python formatter in our portal.

https://github.com/psf/black
https://black.readthedocs.io/en/stable/pyproject_toml.html

Thanks @petershin

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
See https://github.com/ling-alan-huang/liferay-portal/pull/323

**Pull request closed without merging**
