### PR TITLE
run tests

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by hhuijser** [comment]
Is this pull just for testing purposes?

**Comment by arthurchan35** [comment]
@hhuijser,
Yes, once no more failure is detected, I will merge test commits into one, and then resend.

**Comment by hhuijser** [comment]
@arthurchan35, did you consult with the product team before making these changes?

**Comment by arthurchan35** [comment]
@hhuijser, 
I am reaching out to SME right now.

**Pull request closed without merging**
