### PR TITLE
LPS-84119 Clean up source-formatter-suppressions.xml on master

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:help

**Comment by ling-alan-huang** [comment]
Hi @hhuijser,
I ran `ant format-source-all` on my local, there are two issues.

1. The same as the issue here: https://github.com/brianchandotcom/liferay-portal/pull/74266#issuecomment-500279901
2.  `liferay-npm-scripts format` changes some JavaScript files, and this task terminated `ant format-source-all` task

Both of them are not related to my changes.

**Comment by hhuijser** [comment]
Nice!
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/74272

**Pull request closed without merging**
