### PR TITLE
LPS-105380 Add DTOEnumCreationCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Previous pull: https://github.com/hhuijser/liferay-portal/pull/5905

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
