### PR TITLE
LPS-105380 XMLSourceProcessor

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://liferay.slack.com/archives/C02292JBZEC/p1620746312000100

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:tset:sf

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
SF failure is not related to my changes, I asked for help here: https://github.com/brianchandotcom/liferay-portal/pull/102078/files#diff-67fda2317293d01c1bd796dda8bb16f13911957223ba901af8385592d662ad4eR3

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/102173

**Pull request closed without merging**
