### PR TITLE
OAUTH2-239 SF Rename property name (master)

### PR DESCRIPTION
**Pull request by ling-alan-huang**
@hhuijser,

See: https://github.com/brianchandotcom/liferay-portal/pull/67490#issuecomment-459802301

master fix: this pull
sub-repo fix: https://github.com/hhuijser/com-liferay-apio-architect/pull/1

7.1.x fix: https://github.com/hhuijser/liferay-portal-ee/pull/2873
sub-repo fix: @hhuijser, please fork https://github.com/liferay/com-liferay-commerce, so that I can send the fix to you.

The property name `oauth2.scopechecker.type `can not be found in private or 7.0.x.

Thanks.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
@ling-alan-huang , will you add logic to SF as well to make catch future cases?

Can you resend? merging conflicts

**Pull request closed without merging**
