### PR TITLE
LPS-53194 Simplify

### PR DESCRIPTION
**Pull request by igorspasic**

### CODE REVIEW

**Comment by lipusz** [comment]
Technical Support

**Comment by lipusz** [comment]
Hey Hugo,

I was wondering if you had time to review this pull. Please, push it forward as soon as possible. An SDH has already been released, but I don't want to let this LPS become a backlog ticket.

Thanks,
-tibor

@hhuijser

**Comment by hhuijser** [comment]
Hey @lipusz 

Sorry for the delay, I was on holiday...

**Comment by hhuijser** [comment]
Sent to Brian for further review: https://github.com/brianchandotcom/liferay-portal/pull/24087

**Comment by lipusz** [comment]
Oh, then n, sorry for bothering you with this... I didn't know. 😃

Thanks,
-tibor

**Pull request closed without merging**
