### PR TITLE
LPS-76807

### PR DESCRIPTION
**Pull request by yuhai**
Hi Hugo,

The PR extends from https://github.com/hhuijser/liferay-portal/pull/3154.

Please refer to the explanation from https://github.com/hhuijser/liferay-portal/pull/3160#issue-291830904

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Sergio for review: https://github.com/sergiogonzalez/liferay-portal/pull/4193

**Pull request closed without merging**
