### PR TITLE
LPS-143349 Fix logic to get the correct results regardless of the checks order

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Hugo,

**Issue 1: Jsp**
Without this changes, if `JSPUnusedTermsCheck` goes first, it will remove `String cssClass = "cssClass";`

Before enforcing checks order you made before, other jsp check(`JSPTag..check`? I forgot) will change
`cssClass='<%= \"language-value \" + cssClass %>'
`to
`cssClass='<%= "language-value " + cssClass %>'
` first, then go into `JSPUnusedTermsCheck`

```
<%--
/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */
--%>

<%@ include file="/init.jsp" %>

<%@ taglib uri="http://liferay.com/tld/aui" prefix="liferay-ui" %>

<%
String cssClass = "cssClass";
String editorName = "editorName";
String inputEditorName = "inputEditorName";
String randomNamespace = "randomNamespace";
String placeholder = "placeholder";
String toolbarSet = "toolbarSet";

boolean portletTitleBasedNavigation = true;
%>

<liferay-ui:input-editor
	contents="<%= mainLanguageValue %>"
	contentsLanguageId="<%= languageId %>"
	cssClass='<%= \"language-value \" + cssClass %>'
	editorName="<%= editorName %>"
	name='<%= inputEditorName %>'
	onChangeMethod='<%= randomNamespace + \"onChangeEditor\" %>'
	placeholder="<%= placeholder %>"
	toolbarSet="<%= toolbarSet %>"
/>

<div <%= portletTitleBasedNavigation ? "class=\"container-fluid-1280\"" : StringPool.BLANK %>>
</div>
```

**Issue 2: yaml**
Fixed in this pull.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
