### PR TITLE
LPS-104679 JSP checkstyle

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

I added method to skip checking for JSP.
```
Include method call 'data.put' (88) in 'HashMapBuilder' (74): apps/product-navigation/product-navigation-control-menu-web/src/main/resources/META-INF/resources/view_resources.jsp 74 (Checkstyle:MapBuilderCheck)
Include method call 'data.put' (43) in 'HashMapBuilder' (31): apps/product-navigation/product-navigation-site-administration/src/main/resources/META-INF/resources/sites/site_administration_body.jsp 31 (Checkstyle:MapBuilderCheck)

```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant modules-unit failure was fixed in upstream

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@austinchiang @xbrianlee
```
    [junit] 15:05:25,691 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:46] STARTED com.liferay.document.library.test_1.0.0 [1069]
    [junit] 15:06:43,129 WARN  [com.liferay.document.library.test-executor-thread][FileImpl:466] Unable to extract text from q7JFQ0JN
    [junit] org.apache.tika.exception.TikaException: TIKA-198: Illegal IOException from org.apache.tika.parser.executable.ExecutableParser@6fac7b35
...
com.liferay.document.library.internal.search.spi.model.index.contributor.DLFileEntryModelDocumentContributor.contribute(DLFileEntryModelDocumentContributor.java:114)
```

@vicnate5
```
    [junit] 15:02:06,134 INFO  [Portal Dependency Manager Component Executor--1][VerifyProcess:80] Completed verification process com.liferay.polls.internal.verify.PollsServiceVerifyProcess in 5 ms
    [junit] 15:02:07,050 ERROR [Portal Dependency Manager Component Executor--1][JDBCExceptionReporter:234] Duplicate entry 'com.liferay.portal.repository.portletrepository.PortletRepositor' for key 'IX_B27A301F'
```

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Thanks @jpince

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Rebase and resolved violation, retesting...

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@hhuijser, SF failure is resolved on https://github.com/hhuijser/liferay-portal/pull/4164#issuecomment-619569658

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4169

**Pull request closed without merging**
