### PR TITLE
LPS-105380 Case sensitive sort the properties

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,
Issue: https://github.com/brianchandotcom/liferay-portal/pull/91926

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang Closing this for now (see https://liferay.slack.com/archives/DFLN543EZ/p1596074366001200)
Please reopen if you need to

**Pull request closed without merging**
