### PR TITLE
LPS-105380_TXTSourceProcessor_20201030

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo:

_Issues:_
https://github.com/liferay/liferay-portal/commit/12061b5824f2691e960f28dc6df57325c38750e6
https://github.com/brianchandotcom/liferay-portal/commit/6ed7b4ba0615d08b6f8e0682672c8e9cf42df31c (SF already skip checking third party directory)
https://github.com/brianchandotcom/liferay-portal/commit/b87bd6827fd08170da2f82dad9472492787ec62b

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
