### PR TITLE
LPS-76278 avoid removin 2 quo chars when there is 1 char in string

### PR DESCRIPTION
**Pull request by arthurchan35**
LPS-76278 avoid removin 2 quo chars when there is 1 char in string

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Shuyang for review: https://github.com/shuyangzhou/liferay-portal/pull/5400

**Pull request closed without merging**
