### PR TITLE
LPS-105380_Checkstyle_20200727_4

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:bundel

**Comment by ling-alan-huang** [comment]
ci:test:bundle

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4563

@ling-alan-huang See my changes... we prefer using `Objects.equals`.
These days we try to avoid depending on `portal-kernel` as much as we can.

**Pull request closed without merging**
