### PR TITLE
LPS-105380_UnnecessaryVariableDeclarationCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: liferay@935d755

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@hhuijser looks like you fixed some violations a few months ago: 2d1e4597da6da366907d8b3fb2ce280468771b40
There are still a lot of violations on 7.x, 300+ on 7.3.x, do you think we should add this SF rule?

**Comment by ling-alan-huang** [comment]
. That no problem
I can use regex to it.

**Comment by hhuijser** [comment]
@ling-alan-huang how many violations do we have in master?
Let's just apply to master and not worry about older branches?

**Comment by ling-alan-huang** [comment]
not too much, all violations in master are fixed in this pull.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
closing, i will resend.

**Pull request closed without merging**
