### PR TITLE
LPS-105380 FTL

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4334

- I took out this commit https://github.com/hhuijser/liferay-portal/pull/4330/commits/306166b0affc349cd4f07cb5cd4ea3c1f0bc6492. If order matters, there should have been an empty line between the two tags
- Backports here:
https://github.com/brianchandotcom/liferay-portal-ee/pull/30601
https://github.com/brianchandotcom/liferay-portal-ee/pull/30602
https://github.com/brianchandotcom/liferay-portal-ee/pull/30603

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4334

- I took out this commit https://github.com/hhuijser/liferay-portal/pull/4330/commits/306166b0affc349cd4f07cb5cd4ea3c1f0bc6492. If order matters, there should have been an empty line between the two tags
- Backports here:
https://github.com/brianchandotcom/liferay-portal-ee/pull/30601
https://github.com/brianchandotcom/liferay-portal-ee/pull/30602
https://github.com/brianchandotcom/liferay-portal-ee/pull/30603

**Pull request closed without merging**
