### PR TITLE
LPS-137707 Add support for Portlet 3.0 EL keywords to Source Formatter (SF) JSPUnusedTermsCheck

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@hhuijser This is an extremely simple change that should be very easy and fast for you to review. If you approve of the changes, please `ci:forward` to Brian. Thank you.

**Comment by hhuijser** [comment]
ci:forward

**Comment by ngriffin7a** [comment]
@hhuijser SF failure was in CProductItemSelectorView.java which is unrelated to the commit in this pull.

**Comment by hhuijser** [comment]
@ngriffin7a, yup, when the other tests pass, I'll forward manually

**Comment by ngriffin7a** [comment]
@hhuijser Could you try `ci:forward` again? I think these failures are unrelated. Thank you.

**Comment by hhuijser** [comment]
Forwarded to Brian: https://github.com/brianchandotcom/liferay-portal/pull/105993

**Pull request closed without merging**
