### PR TITLE
Lps 61841 sf

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
The 1st commit has sent to brian already at https://github.com/brianchandotcom/liferay-portal/pull/34135

This pull is for the new SF check.

**Comment by hhuijser** [comment]
@shuyangzhou 

Isn't your extra check redundant?

Matthews initial regex is checking for:
1. Starting with upper case
AND
2. no period --> no package path

The fact that package name can start with upper case seems not relevant to his check?

**Comment by shuyangzhou** [comment]
Yeah, you are right. Not sure what I was thinking:(

Please just drop my commit then, thanks!

**Comment by hhuijser** [comment]
Sounds good...
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/34139

**Pull request closed without merging**
