### PR TITLE
LPS-84119 Avoid metal-cli and liferay-module-condig-generator usage

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser,

See: https://issues.liferay.com/browse/LPS-90378

If this is good for you, you can review https://github.com/hhuijser/liferay-portal-ee/pull/2874 for 7.1.x.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
Rename as discussed

**Pull request closed without merging**
