### PR TITLE
LPS-84119 SF Json 

### PR DESCRIPTION
**Pull request by ling-alan-huang**
**Issue:**
https://github.com/brianchandotcom/liferay-portal/pull/76781#issuecomment-519708560

**Related pulls:**
master-private: https://github.com/hhuijser/liferay-portal-ee/pull/2923

7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/2922
7.1.x-private: No violations

7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/2921
7.0.x-private: https://github.com/hhuijser/liferay-portal-ee/pull/2920

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are in private branch.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/77176

**Pull request closed without merging**
