### PR TITLE
LPS-105380 Add DTOEnumCreationCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

https://github.com/brianchandotcom/liferay-portal/pull/106818#issuecomment-915278092

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang not a big fan of that long list in `source-formatter.properties`

Simply enforcing the package to match `*.dto.v[0-9]_[0-9].*` won't work?

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/5915

**Pull request closed without merging**
