### PR TITLE
pull-request-1532

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @hhuijser,

Attached is an update for https://github.com/jonmak08/liferay-portal/pull/1532.  I fixed the rebase issue and the typo in the commit message.

Everything looks good in the files you committed.  Can this source format also update ```.ftl``` files too?

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @jonmak08 

I was concerned that for example the changes in modules/apps/deprecated/network-utilities/network-utilities-web/src/main/resources/META-INF/resources/view.jsp were incorrect.
But you're saying that even for those <pre> tags, it's okay to add those tabs?

I'll see if we can apply this to *.ftl as well.

Thanks!

**Comment by jonmak08** [comment]
Hey @hhuijser,

You are right, the ```<pre>``` tags cannot be formatted as you would like since the spaces actually result to indentations in the code being displayed.  Sorry I missed that!

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
Before change:
screen shot 2016-03-31 at 9 34 35 am

screen shot 2016-03-31 at 9 34 47 am

After change:
screen shot 2016-03-31 at 9 29 00 am

screen shot 2016-03-31 at 9 28 47 am

**Comment by hhuijser** [comment]
Thanks @jonmak08, there is no other tags we should be careful with?

**Comment by jonmak08** [comment]
Hey @hhuijser,

Not that I know of.  Everything else should be good.

Please let me know if you have any questions. Thanks!

**Pull request closed without merging**
