### PR TITLE
LPS-71558 Source formatter is using xercesImpl 2.6.2 but should use 2.11.0

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
See full explanation in https://issues.liferay.com/browse/LPS-71558

In https://github.com/hhuijser/liferay-portal/pull/2850/commits/1b94a116080ac1c9db1a296779a5d406a21ab8a9 I change xercesImpl 2.11 from "provided" to "compile"

In https://github.com/hhuijser/liferay-portal/pull/2850/commits/d9c00ad3b9ca1b494188b8c1f734e777f4100a53 I added a source formatter exclude because I had some troubles during compilation, both JavaIllegalImportsCheck.java and JavaStylingCheck.java were broken in formatSource execution.

Rest of commits are added in order to publish the updated version of source formatter in gradle cache and very that LPS-71278 works with new version

@Ithildir

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Andrea for further review: https://github.com/Ithildir/liferay-portal/pull/659

**Pull request closed without merging**
