### PR TITLE
LPS-105380 JavaTestMethodAnnotationsCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/3aa6b8cbffea39eb89d36735f33779e502d5d99a

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Okay, see https://github.com/hhuijser/liferay-portal/pull/4375

So, let's get rid of the `@Override` annotation clause, but add the following (see last commit in that pull)
- skip methods with parameters
- skip methods in child classes

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/4392

**Pull request closed without merging**
