### PR TITLE
LPS-106524 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
@lawrence-lee you mind fixing the conflict and resend?

**Comment by lawrence-lee** [comment]
https://github.com/hhuijser/liferay-portal/pull/3961

**Pull request closed without merging**
