### PR TITLE
LPS-105380 ChainingCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Previous pull: https://github.com/hhuijser/liferay-portal/pull/4200

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:bundle

**Comment by jpince** [comment]
If no further changes are needed, this pull should forward without running additional tests due to new “no unique failures” forwarding logic https://liferay.slack.com/archives/C19PWQ74J/p1590699203393900

**Comment by ling-alan-huang** [comment]
Thanks for checking @jpince

**Comment by hhuijser** [comment]
conflicts :(
Can you resend?

**Pull request closed without merging**
