### PR TITLE
LPS-114165

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
[SharedAppBuilder#CreateTableViewsWithFixedEntriesFilter](https://testray.liferay.com/home/-/testray/cases/1151951925) failing consistently at head @alexcandidos

**Comment by brianwulbern** [comment]
[Forms#SubmitFormWithCustomTextContainingValidation](https://testray.liferay.com/home/-/testray/cases/867487625) failing consistently at head @cvanut

**Comment by brianwulbern** [comment]
@austinchiang, looks like some Depot tests are failing consistently now:
[DepotNavigation#AccessViaSiteNavigation](https://testray.liferay.com/home/-/testray/cases/892140723) [LRQA-58873](https://issues.liferay.com/browse/LRQA-58873) (Yvonne seems to be working on it)

Interestingly, these two tests only failed when tested on this pull:
[DepotApplication#Smoke](https://testray.liferay.com/home/-/testray/cases/1034057945)
[DepotCollections#Smoke](https://testray.liferay.com/home/-/testray/cases/1105329267)

Can your team investigate those two deeper?  Thanks!

**Comment by brianwulbern** [comment]
@alexcandidos, @austinchiang, @cvanut

[Testray result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1184718758) for this pull

**Comment by austinchiang** [comment]
@brianwulbern  yeah that's being fixed [here](https://github.com/liferay-lima/liferay-portal/pull/97)

**Comment by hhuijser** [comment]
ci:forward

**Comment by alexcandidos** [comment]
hi @brianwulbern and @hhuijser ,

A lot of Forms/App-Builder scenarios were impacted in the builds from Saturday and so on. Those tests are not broken, they fail due to this PR https://github.com/brianchandotcom/liferay-portal/pull/89111.
Jeyvison sent a new PR https://github.com/brianchandotcom/liferay-portal/pull/89180 reverting those changes but it is still on BChan queue since yesterday was a holiday in US.

Thanks!

**Comment by cvanut** [comment]
Hi @brianwulbern
Last Friday, [this pull request](https://github.com/brianchandotcom/liferay-portal/pull/89111) related to LPS-113779 was merged and made Forms and App Builder tests to fail, then [this pull request](https://github.com/jeyvison/liferay-portal/pull/744) was sent to revert the code that caused these issues. I believe the revert will be merged soon.

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
The integration failures look like known flukes - the `DLFileEntryIndexerLocalizedContentTest` [suite of tests](https://testray.liferay.com/home/-/testray/cases/index?p_p_state=normal&orderByCol=testrayComponentName_sortable&orderByType=asc&testrayProjectId=849925375&name=DLFileEntryIndexerLocalizedContentTest) all fail out on:
`java.lang.AssertionError: ??????->[]`

Then the `DLFileEntryFileNameSearchTest` [suite of tests](https://testray.liferay.com/home/-/testray/cases/index?p_p_state=normal&orderByCol=testrayComponentName_sortable&orderByType=asc&testrayProjectId=849925375&name=DLFileEntryFileNameSearchTest) all fail out with similar `???` assertion errors:
```
 [exec]     java.lang.AssertionError: {"from":0,"size":10000,"query":{"bool":{"must":[{"bool":{"must":[{"bool":{"should":[{"bool":{"must":[{"match":{"comments":{"query":"??????"}}}],"should":[{"match_phrase":{"comments":{"query":"??????","slop":50}}},{"match_phrase":{"comments":{"query":"??????","boost":2.0}}}]}},{"bool":{"must":[{"match":{"content":{"query":"??????"}}}],"should":[{"match_phrase":{"content":{"query":"??????","slop":50}}},{"match_phrase":{"content":{"query":"??????","boost":2.0}}}]}},{"bool":{"must":[{"match":{"description":{"query":"??????"}}}],"should":[{"match_phrase":{"description":{"query":"??????","slop":50}}},{"match_phrase":{"description":{"query":"??????","boost":2.0}}}]}},{"bool":{"should":[{"wildcard":{"properties":{"wildcard":"*??????*"}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"title":{"query":"??????"}}},{"match_phrase_prefix":{"title":{"query":"??????"}}}]}}],"should":[{"match_phrase":{"title":{"query":"??????","boost":2.0}}}]}},{"bool":{"should":[{"match_phrase":{"url":{"query":"??????"}}},{"bool":{"should":[{"wildcard":{"url":{"wildcard":"*??????*"}}}]}},{"match_phrase_prefix":{"url":{"query":"??????","max_expansions":300}}}]}},{"bool":{"should":[{"wildcard":{"userName":{"wildcard":"*??????*"}}}]}},{"bool":{"must":[{"match":{"assetCategoryTitles_ja_JP":{"query":"??????"}}}],"should":[{"match_phrase":{"assetCategoryTitles_ja_JP":{"query":"??????","slop":50}}},{"match_phrase":{"assetCategoryTitles_ja_JP":{"query":"??????","boost":2.0}}}]}},{"bool":{"must":[{"bool":{"should":[{"match":{"assetTagNames_ja_JP":{"query":"??????"}}},{"match_phrase_prefix":{"assetTagNames_ja_JP":{"query":"??????"}}}]}}],"should":[{"match_phrase":{"assetTagNames_ja_JP":{"query":"??????","boost":2.0}}}]}},{"bool":{"must":[{"match":{"ddmContent":{"query":"??????"}}}],"should":[{"match_phrase":{"ddmContent":{"query":"??????","slop":50}}},{"match_phrase":{"ddmContent":{"query":"??????","boost":2.0}}}]}},{"bool":{"must":[{"match":{"extension":{"query":"??????"}}}],"should":[{"match_phrase":{"extension":{"query":"??????","slop":50}}},{"match_phrase":{"extension":{"query":"??????","boost":2.0}}}]}},{"bool":{"must":[{"match":{"fileEntryTypeId":{"query":"??????"}}}],"should":[{"match_phrase":{"fileEntryTypeId":{"query":"??????","slop":50}}},{"match_phrase":{"fileEntryTypeId":{"query":"??????","boost":2.0}}}]}},{"bool":{"should":[{"wildcard":{"path":{"wildcard":"*??????*"}}}]}},{"bool":{"must":[{"match":{"content_ja_JP":{"query":"??????"}}}],"should":[{"match_phrase":{"content_ja_JP":{"query":"??????","slop":50}}},{"match_phrase":{"content_ja_JP":{"query":"??????","boost":2.0}}}]}}]}}]}}],"filter":[{"bool":{"must":[{"bool":{"should":[{"bool":{"must":[{"term":{"entryClassName":{"value":"com.liferay.document.library.kernel.model.DLFileEntry"}}},{"term":{"hidden":{"value":"false"}}},{"term":{"hidden":{"value":"false"}}},{"terms":{"status":["0"]}},{"terms":{"status":["0"]}}]}}]}}]}}]}},"explain":false,"stored_fields":"*","track_scores":true}->[] expected:<1> but was:<0>
```

@austinchiang fyi

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
@brianwulbern BChan is looking for data on what tests (and/or tickets) have been negatively impacting teams' ability to build. Can you please Slack him with any info you have and I can follow up? Just send what you can gather today. Thank you!

**Comment by jpince** [comment]
ci:forward SF and semver failures were fixed in upstream. Hopefully the segments tests were also flaky.

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@rafaprax
[HistogramMetricResourceTest#testGetProcessHistogramMetric](https://testray.liferay.com/home/-/testray/cases/1110043594) is hitting a fluke assertion error in 8 of the past 200 runs, since 5/22  Can you find a way to stabilize it any more?  

Here's [an example log](https://testray.liferay.com/reports/production/logs/test-1-14/1590382999184/test-portal-testsuite-upstream(master)/261/modules-integration-mariadb102-jdk11_open/37/jenkins-console.txt.gz), with the relevant output below:
```
 [exec] com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.HistogramMetricResourceTest > testGetProcessHistogramMetric FAILED
     [exec]     java.lang.AssertionError: {"histograms": [{"key": "2020-05-24T00:00", "value": 1.0}], "value": 30.0} does not equal {"histograms": [{"key": "2020-05-24T00:00", "value": 0.0}], "value": 0.0}
     [exec]     	at org.junit.Assert.fail(Assert.java:88)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]     	at com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.BaseHistogramMetricResourceTestCase.assertEquals(BaseHistogramMetricResourceTestCase.java:215)
     [exec]     	at com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.HistogramMetricResourceTest._assertMetric(HistogramMetricResourceTest.java:142)
     [exec]     	at com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.HistogramMetricResourceTest._testGetProcessMetric(HistogramMetricResourceTest.java:222)
     [exec]     	at com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.HistogramMetricResourceTest.testGetProcessHistogramMetric(HistogramMetricResourceTest.java:107)
     [exec]     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:234)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.TimeoutTestRule$1.evaluate(TimeoutTestRule.java:89)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:143)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:181)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.base/java.lang.Thread.run(Thread.java:834)
     [exec] 
```

**Comment by brianwulbern** [comment]
@CarlosBrichete, these tests are failing consistently at head, but only as of 2pm, 5/27 LA time.
[DefaultSegmentsEntryProviderTest#testGetSegmentsEntryIdsWithMultipleModelCriterion](https://testray.liferay.com/home/-/testray/cases/863816480)
[DefaultSegmentsEntryProviderTest#testGetSegmentsEntryClassPKsWithMultipleCriterion](https://testray.liferay.com/home/-/testray/cases/863810892)
[DefaultSegmentsEntryProviderTest#testGetSegmentsEntryClassPKsWithMultipleCriterionNotMatching](https://testray.liferay.com/home/-/testray/cases/863815322)

The [comparison](https://github.com/liferay/liferay-portal/compare/bba34af40c1fa62c1d52bac73d26ecb4dc15c68e...9617f95b39dbb47f032785f08b71932038e1bb9e) is too wide to be useful for me, but maybe it can help you.

**Comment by brianwulbern** [comment]
@CarlosBrichete, I've created https://issues.liferay.com/browse/LPS-114493 to track the issue.

**Comment by jpince** [comment]
@rodrigocunhaa see Brian Wulbern's comment above about `HistogramMetricResourceTest#testGetProcessHistogramMetric`

**Comment by jpince** [comment]
fix for Segments is being tested here: https://github.com/cgoncas/liferay-portal/pull/499

**Comment by rodrigocunhaa** [comment]
Hi @brianwulbern , I reopened this ticket: https://issues.liferay.com/browse/LPS-113131 and I'll also disable ignore this test for now. Thanks!

cc: @jpince

**Comment by jpince** [comment]
New fix for segments: https://github.com/cgoncas/liferay-portal/pull/501

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

@rodrigocunhaa flaky tests `LocalFile.WorkflowDDL#EditDDLRecordViaMyWorkflowTasks` `LocalFile.WorkflowPageComments#EditCommentAssignedToMe`

**Comment by rodrigocunhaa** [comment]
@jpince , all the flaky were sent to be ignored https://github.com/brianchandotcom/liferay-portal/pull/89381 and https://github.com/brianchandotcom/liferay-portal/pull/89382

**Comment by jpince** [comment]
@yichenroy git dev node failure?

**Comment by yichenroy** [comment]
ci:forward

@jpince the downstreams couldn't find cached branches that are supposed to be on the github dev nodes. We're investigating the cause, but restarting the test should be okay.

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
ci:forward

**Comment by austinchiang** [comment]
43jqto

@brianwulbern @hhuijser

**Comment by brianwulbern** [comment]
@xbrianlee @BryanEngler

It looks like some Aggregate and Reindexing tests are [failing flakily](https://github.com/hhuijser/liferay-portal/pull/4295#issuecomment-636602420), is there anything you guys can do to stabilize them?  Thanks!

**Comment by jpince** [comment]
ci:forward

**Comment by xbrianlee** [comment]
@brianwulbern The unit test failures are covered under https://issues.liferay.com/browse/LRQA-57722 and I reopened https://issues.liferay.com/browse/LPS-113705 for the integration test failures. They're in our queue to work on.

**Comment by brianwulbern** [comment]
Thanks, @xbrianlee

**Pull request closed without merging**
