### PR TITLE
LPS-119446

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@jpince

**Comment by jpince** [comment]
@hhuijser this startup error looks like it might be related to your changes in saml-web, can you please take a look?
```
 [parallel] 2021-04-19 15:03:42.715 ERROR [main][ResourceBundleRegistrator:93] bundle com.liferay.saml.web:5.0.5 (824)[com.liferay.saml.web.internal.resource.bundle.ResourceBundleRegistrator(7841)] : The activate method has thrown an exception 
 [parallel] java.lang.IllegalArgumentException: The service parameter is null
```

**Comment by jpince** [comment]
2. asked about memory errors [here](https://liferay.slack.com/archives/C19PWQ74J/p1618943097138700?thread_ts=1618943055.138600&cid=C19PWQ74J)
3. ignore semver failures, due to Brian Chan publishing (and so now you have a merge conflict)

**Comment by hhuijser** [comment]
> @hhuijser this startup error looks like it might be related to your changes in saml-web, can you please take a look?
> 
> ```
>  [parallel] 2021-04-19 15:03:42.715 ERROR [main][ResourceBundleRegistrator:93] bundle com.liferay.saml.web:5.0.5 (824)[com.liferay.saml.web.internal.resource.bundle.ResourceBundleRegistrator(7841)] : The activate method has thrown an exception 
>  [parallel] java.lang.IllegalArgumentException: The service parameter is null
> ```

Don't think that's related

**Comment by jpince** [comment]
@hhuijser you're correct, I see it in another pull, so probably a race condition (I will file a separate LPS), so we can ignore this error in your PRs

**Comment by jpince** [comment]
@hhuijser I would advise rebasing and sending directly to Brian Chan. I think the risk in missing tests is low enough that we can move forward (vs. waiting for another round of tests).

**Comment by hhuijser** [comment]
Okay, will send this to Brian. Thanks Jason

**Comment by hhuijser** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/100952

**Pull request closed without merging**
