### PR TITLE
LPS-121804_Python_20201219

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Hugo,

I used these repos to check my logic.

https://github.com/liferay/com-liferay-osb-asah-private/tree/7.0.x/osb-asah-spark
https://github.com/liferay/liferay-learn

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang how come this file is changed: https://github.com/hhuijser/liferay-portal/pull/5161/commits/689f12c40d27c87b9e6fa0873f1610846e9d63aa#diff-c57cfa0b2eb150c758c27034794698c823a25a22b7ef8267f2cc2e4b0ba814b7R8

**Comment by ling-alan-huang** [comment]
@hhuijser My bad, I just removed the changes on `../.project`

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/5166

**Pull request closed without merging**
