### PR TITLE
[TS] LPS-81240 additional commits

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevent

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:test:relevent

**Comment by hhuijser** [comment]
Sent to Preston for review: https://github.com/Preston-Crary/liferay-portal/pull/556

**Pull request closed without merging**
