### PR TITLE
Lps 74188

### PR DESCRIPTION
**Pull request by amosfong**
@bawachhe, made it so the regex is not run on every file

### CODE REVIEW

**Comment by amosfong** [comment]
actually I'm not sure if that actually does anything until it hits find()

**Comment by amosfong** [comment]
ci:repoen

**Comment by amosfong** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Thanks @bawachhe @amosfong 

Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/50960

**Pull request closed without merging**
