### PR TITLE
LPS-60238

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Hugo,
I am not sure if this fix is correct, because we have two way to fix this issue, one is to import com.liferay.portal.kernel.util package and one is to include all the class portal can not found (ParamUtil and StringUtil etc and all the class that the two class referenced)

Import com.liferay.portal.kernel.util package is simple to maintain for developer and make the bundle jar more smaller

The include method will copy class into the bundle jar to make jar get more big.

I not know what is the standard to choose which way to use in our portal.

is it a performance concern to choose include not import a package? I know if include class into bundle it does not need across class loader to get object, probably it can save time.

Looks forward to your opinion.
Thanks,
Dale

**Comment by hhuijser** [comment]
I think we try to keep the jar as compact as possible and only import what we need.

@daviddotzhang 

How many classes do we end up with having to add to Include-Resource if we go that route?

**Comment by daledotshan** [comment]
@hhuijser 
Before we have a pull request use include but brian reject it
https://github.com/brianchandotcom/liferay-portal/pull/30821#issuecomment-146081514

**Comment by hhuijser** [comment]
Sent to Andrea for review: https://github.com/Ithildir/liferay-portal/pull/130

**Pull request closed without merging**
