### PR TITLE
LPS-84119 SF gradle

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
Hi Hugo,
I Auto SF on master to fix other issues and sent to you here: https://github.com/hhuijser/liferay-portal/pull/3772

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/78760

**Pull request closed without merging**
