### PR TITLE
[TS] LPS-78856

### PR DESCRIPTION
**Pull request by yuhai**
Hi Hugo,

The PR extends from https://github.com/rafaprax/liferay-portal/pull/404. The error occured in the junit test (not Integration test). I append one commit to solve the NPE error. And it works for DDMFormTemplateContextFactoryTest class.

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by hhuijser** [comment]
ci:test

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Rafael for review: https://github.com/rafaprax/liferay-portal/pull/417

**Pull request closed without merging**
