### PR TITLE
LPS-141244 PoshiDependenciesFileLocationCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Hugo,

I added an additional check.
See: https://github.com/vicnate5/liferay-portal/pull/1895#issuecomment-976092359

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:relevant

**Comment by ling-alan-huang** [comment]
_Violations:_
```
java.lang.Exception: Found 8 formatting issues:
1: Test dependencies file '/Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/Spaceport.jpg' is only referenced by one module, move it to module dependencies directory: /Users/alan/liferay_code/master/liferay-portal/modules/apps/digital-signature/digital-signature-test/src/testFunctional/tests/tests/DigitalSignatureDM.testcase (SourceCheck:PoshiDependenciesFileLocationCheck)
2: Test dependencies file '/Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/Document_2.pptx' is only referenced by one module, move it to module dependencies directory: /Users/alan/liferay_code/master/liferay-portal/modules/dxp/apps/document-library-opener/document-library-opener-onedrive-test/src/testFunctional/OneDrive.testcase (SourceCheck:PoshiDependenciesFileLocationCheck)
3: Test dependencies file '/Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/condition_workflow_invalid.xml' is only referenced by one module, move it to module dependencies directory: /Users/alan/liferay_code/master/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-test/src/testFunctional/tests/Kaleodesigner.testcase (SourceCheck:PoshiDependenciesFileLocationCheck)
4: Test dependencies file '/Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/TempFile.txt' is only referenced by one module, move it to module dependencies directory: /Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/bundleblacklist/BundleBlacklist.testcase (SourceCheck:PoshiDependenciesFileLocationCheck)
5: Test dependencies file '/Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/license/portal-dxp-license-custom-expiration-48-hours.xml' is only referenced by one module, move it to module dependencies directory: /Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/license/DXPLicense.testcase (SourceCheck:PoshiDependenciesFileLocationCheck)
6: Test dependencies file '/Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/license/dxp-license-virtual-cluster.xml' is only referenced by one module, move it to module dependencies directory: /Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/clustering/clusteringframework/ClusteringLicense.testcase (SourceCheck:PoshiDependenciesFileLocationCheck)
7: Test dependencies file '/Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/これは文書です.txt' is only referenced by one module, move it to module dependencies directory: /Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/documentmanagement/documentsadministration/DMLocalization.testcase (SourceCheck:PoshiDependenciesFileLocationCheck)
8: Test dependencies file '/Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/Document -_.jpg' is only referenced by one module, move it to module dependencies directory: /Users/alan/liferay_code/master/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/fields/FormsUploadField.testcase (SourceCheck:PoshiDependenciesFileLocationCheck)

```

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
I fetched this and fixed the violations, merging together with the SF rule still enabled
https://github.com/vicnate5/liferay-portal/pull/1897

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
Resent https://github.com/vicnate5/liferay-portal/pull/1898

**Pull request closed without merging**
