### PR TITLE
LPS-105380 PoshiCommandsOrderCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/david-gutierrez-mesa/liferay-portal/pull/160/commits/3400e332baf8fbb0beb6db30d6700631776e90b3#diff-80f9a0633844f491066484bade03ae917d153fac7d9b11ca76918285e72cff12L1301

I fixed regex to grab this line.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
