### PR TITLE
LPS-120734 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @lawrence-lee I really dislike these nested if statements because those are hard to read: https://github.com/hhuijser/liferay-portal/pull/4808/commits/ba54e97d3031372ec0ffb587c90ae88034ba99be#diff-ec7b00103ca8db6d647ff347de4a524aR5-R21

Anything we can do about that (while keeping format of generated files nicely formatted)?

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
There's nothing we can do about the nested if statements. 

We have to choose between clean archetypes (small amounts of if statements) or clean project files (lots of if statements).

**Comment by lawrence-lee** [comment]
@hhuijser

**Comment by hhuijser** [comment]
@lawrence-lee, understood.
Failing test related?

**Comment by lawrence-lee** [comment]
@hhuijser, yes. I need to fix these tests. 

One last thought on the if statements. I'm just doing a partial revert of how things were 2 months ago. We had all of these nested if statements. I tried to clean it up by using the `release.portal.api` for everything, but we ran into lots of issues with legacy branches, so we decided to only implement the `release.portal.api` jar usage for 7.3+. I do eventually want to go back to using the `release.portal.api` for all branches of Liferay Portal and going back will get rid of the multiple/nested if statements.

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
