### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@vicnate5 is this a reoccurrence of https://issues.liferay.com/browse/LPS-113032?
```
Unable to extract text from G6CVe1fp
org.apache.tika.exception.TikaException: TIKA-198: Illegal IOException from org.apache.tika.parser.executable.ExecutableParser@45f5e0b8
```

**Comment by vicnate5** [comment]
@jpince It looks like a similar issue, I just made a new ticket and sent to the Lima team (https://issues.liferay.com/browse/LPS-113625)

**Pull request closed without merging**
