### PR TITLE
LPS-105380_JSONUtilCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/aa94538e9bfc91058d6ef801a5047b84fef9ad7a

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
```
return String.valueOf(JSONUtil.put("city", "Los Angeles"));

+--LITERAL_RETURN (return) 32
    +--EXPR 32
        +--METHOD_CALL (() 32
            +--DOT (.) 32
                +--IDENT (String) 32
                +--IDENT (valueOf) 32
            +--ELIST 32
                +--EXPR 32
                    +--METHOD_CALL (() 32
                        +--DOT (.) 32
                            +--IDENT (JSONUtil) 32
                            +--IDENT (put) 32
                        +--ELIST 32
                            +--EXPR 32
                                +--STRING_LITERAL ("city") 32
                            +--COMMA (,) 32
                            +--EXPR 32
                                +--STRING_LITERAL ("Los Angeles") 32
                        +--RPAREN ()) 32
            +--RPAREN ()) 32
    +--SEMI (;) 32

-----------------------

String s = String.valueOf(
	JSONUtil.put(
		"city", "Los Angeles"
	).put(
		"country", "United States"
	));
+--ASSIGN (=) 37
    +--EXPR 37
        +--METHOD_CALL (() 37
            +--DOT (.) 37
                +--IDENT (String) 37
                +--IDENT (valueOf) 37
            +--ELIST 40
                +--EXPR 40
                    +--METHOD_CALL (() 40
                        +--DOT (.) 40
                            +--METHOD_CALL (() 38
                                +--DOT (.) 38
                                    +--IDENT (JSONUtil) 38
                                    +--IDENT (put) 38
                                +--ELIST 39
                                    +--EXPR 39
                                        +--STRING_LITERAL ("city") 39
                                    +--COMMA (,) 39
                                    +--EXPR 39
                                        +--STRING_LITERAL ("Los Angeles") 39
                                +--RPAREN ()) 40
                            +--IDENT (put) 40
                        +--ELIST 41
                            +--EXPR 41
                                +--STRING_LITERAL ("country") 41
                            +--COMMA (,) 41
                            +--EXPR 41
                                +--STRING_LITERAL ("United States") 41
                        +--RPAREN ()) 42
            +--RPAREN ()) 42






```

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
