### PR TITLE
LPS-61627

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by hhuijser** [comment]
@bejondshao 

Did you try running TestLDAPSettings?
Got a feeling that one is broken...

**Comment by hhuijser** [comment]
@bejondshao 
You still on this one?

**Comment by bejondshao** [comment]
Hey hugo, I tried some command but I can't test it. So what's the specific ant command?

Thanks

**Comment by hhuijser** [comment]
I don't know...

**Comment by bejondshao** [comment]
Hey Hugo, you might concern about the return type is changed to Array. I do search for all the methods. All invocations are changed to Array. Besides, I didn't find any test about the methods I modified. Would you check for this?

Thanks

**Comment by hhuijser** [comment]
@bejondshao 

TestLDAPSettings.getErrorPasswordHistory is overriding LDAPSettings.getErrorPasswordHistory 

LDAPSettings.getErrorPasswordHistory changed from returning String to String[]

Without running that test, I am pretty sure that won't compile...

**Comment by bejondshao** [comment]
Hi Hugo,

Yes, you are right. I'm sorry I exclude the test folder so I didn't find the file. I'll commit again, thanks.

**Pull request closed without merging**
