### PR TITLE
LPS-68984 Do not reject view action on omni-admin if the view action is performed by non-omni-admins. Also, for normal company admins, we restrict actions from others on them. Just like what we did in ee-6.2.X

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Hugo

As we discussed, I exclude the view action for permission checking here. And we only treat omni-admin as an exception...

Thanks
John.

### CODE REVIEW

**Comment by daledotshan** [comment]
ci:reopen

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zxdgoal** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Ray for review: https://github.com/rotty3000/liferay-portal/pull/1245

**Comment by zxdgoal** [comment]
ci:reopen

**Comment by zxdgoal** [comment]
ci:retest

**Comment by hhuijser** [comment]
Looks like the CompanyLocalServiceTest.testDeleteCompanyDeletesPortalInstance is caused by this?

**Comment by zxdgoal** [comment]
I did check the code.

{code}
	@Test
	public void testDeleteCompanyDeletesPortalInstance() throws Exception {
		Company company = addCompany();

		CompanyLocalServiceUtil.deleteCompany(company);

		for (long companyId : PortalInstances.getCompanyIds()) {
			Assert.assertNotEquals(
				"Company instance was not deleted", company.getCompanyId(),
				companyId);
		}
	}
{code}

It is not obvious related to my changes.

John.

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zxdgoal** [comment]
It seems the preceding error is not there any more

**Comment by hhuijser** [comment]
reopened and resting on Ray's branch

**Pull request closed without merging**
