### PR TITLE
LPS-114565

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@pyoo47 @yichenroy I'm not sure why the functional jobs are failing out ([example1](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/323137//consoleText)) seemingly on:
`Error response from daemon`

Below that error, there's also a JSON related error:
```
ERROR: Build step failed with exception
com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input within/between Array entries
 at [Source: (InputStreamReader); line: 15, column: 1665]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipAfterComma2(ReaderBasedJsonParser.java:2331)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2301)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:674)
	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$LongDeser.deserialize(PrimitiveArrayDeserializers.java:759)
Caused: com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input within/between Array entries
 at [Source: (InputStreamReader); line: 15, column: 223] (through reference chain: net.masterthought.cucumber.Trends["durations"]->long[][69])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$LongDeser.deserialize(PrimitiveArrayDeserializers.java:780)
	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$LongDeser.deserialize(PrimitiveArrayDeserializers.java:723)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3049)
	at net.masterthought.cucumber.ReportBuilder.loadTrends(ReportBuilder.java:197)
Caused: net.masterthought.cucumber.ValidationException: File '/opt/java/jenkins/jobs/test-portal-acceptance-pullrequest-batch(master)/configurations/axis-AXIS_VARIABLE/1/axis-label_exp/!master/cucumber-reports/cucumber-trends.json' could not be parsed as file with trends!
	at net.masterthought.cucumber.ReportBuilder.loadTrends(ReportBuilder.java:199)
	at net.masterthought.cucumber.ReportBuilder.loadOrCreateTrends(ReportBuilder.java:189)
	at net.masterthought.cucumber.ReportBuilder.updateAndSaveTrends(ReportBuilder.java:172)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:111)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:324)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:248)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Cucumber reports' marked build as failure
```

cc @jpince

**Comment by yichenroy** [comment]
@brianwulbern thanks for reporting. 
`Error response from daemon` isn't an actual issue since it's after the docker container stops, this is present in all builds that use a database container.

The JSON error, however, is a real issue that we're currently investigating, it was also reported in #ci: https://liferay.slack.com/archives/C19PWQ74J/p1591212535428800?thread_ts=1591199746.425200&cid=C19PWQ74J

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
