### PR TITLE
LPS-80283

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@petershin, is this something that @brianchandotcom requested?
We need all this stuff for SB as well, will you do the same thing for SB?
Instead, can we move it to a petra module, so we don't end up with a lot of duplicate code?

**Comment by petershin** [comment]
@hhuijser - I agree! 🙂 Will ask Brian how he wants to coordinate the work

**Comment by petershin** [comment]
Updated pull: https://github.com/hhuijser/liferay-portal/pull/3269

**Pull request closed without merging**
