### PR TITLE
LPS-63827

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @hhuijser,

Attached is an update for http://issues.liferay.com/browse/LPS-63827.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:stop

**Comment by jonmak08** [comment]
ci:stop

**Comment by hhuijser** [comment]
Fixed by @shuyangzhou

**Comment by jonmak08** [comment]
Fixed with https://github.com/brianchandotcom/liferay-portal/pull/43465

**Pull request closed without merging**
