### PR TITLE
LPS-105380 JavaServiceObjectCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

I found this issue when I tried to run Auto SF on 7.2.x.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:bundle

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
