### PR TITLE
LPS-84119 Enforce naming variables of type UnsyncBufferedReader

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/3ec47738b3d130e8768a854ca761f5d58683d5ea

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
If we do this one, we should enforce for all `com.liferay.kernel.io.unsync` classes

**Comment by ling-alan-huang** [comment]
Closing, I will resend.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/4036

**Pull request closed without merging**
