### PR TITLE
LPS-52927

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Information from Hai:

The issue was caused by friendlyURL filed of layout and layoutfriendlyurl table have different value when create layout by using page template and uncheck "Automatically apply changes done to the page template.".

Please refer to the below explanation:
1. Create a new site template
2. Create a new site "Site" using template
3. Add a new page to the site called "testpage"(its friendlyURL is "testpage")
4. Create a page template "test1"
5. Add a page to the site template called "testpage", using page template "test1" and uncheck "Automatically apply changes done to the page template." to add the page
**At this time, please see friendlyURL field (value:/testpage) of layoutfriendlyurl table and friendlyURL field(value:/3(layoutId)) of layout table. So for same layout and same language, they have different value and friendlyURL field(value:/3(layoutId)) of layout table is wrong**

6 Visit actual site again and the ERROR "Duplicate entry IX_A6FC2B28" will occur.

When visit "Site", the process of propagation will start. 
In LayoutStagedModelDataHandler.doImportStagedModel() {
353 line
String friendlyURL = layout.getFriendlyURL();
406- 419 line
LayoutFriendlyURL layoutFriendlyURL =
	LayoutFriendlyURLLocalServiceUtil.fetchFirstLayoutFriendlyURL(groupId, privateLayout, friendlyURL);  
	if ((layoutFriendlyURL != null) && (existingLayout == null)) {
              return;
	}
}
**From 406-419 lines, if friendlyURL=3, it won't check the friendlyURL is conflicted between siteTemplate page and "Site" page. And siteTemplate page "testpage" will be imported. Later, it will invoke below code:**

632 line
importLayoutFriendlyURLs(portletDataContext, layout); // it will invoke importLayoutFriendlyURLs() 984 line.

In importLayoutFriendlyURLs(){
**It will use datas of layoutfriendlyurl table to import related friendlyURL. However, friendlyURL field of layoutfriendlyurl table is "/testpage", it will conflict with existed "Site"'s "testpage" so that the issue occured.**
}

**So the issue occurs due to generated  friendlyURL field's value("/3") of layout table is wrong when create layout by using page template and uncheck "Automatically apply changes done to the page template.".**

When add one layout by using page template and uncheck "Automatically apply changes done to the page template.", it will invoke the below code fragment
in LayoutLocalServiceImpl.addLayout() {
//383 line
SitesUtil.applyLayoutPrototype(layoutPrototype, layout, layoutPrototypeLinkEnabled);
}
**At this time, adding related layoutFriendlyURL logic doesn't be executed yet.** So in SitesImpl.applyLayoutPrototype(){
**targetLayout.getFriendlyURLMap() (256 line) will always return a empty map because adding related layoutFriendlyURL logic will be executed after this logic finished.**
} 

So in LayoutLocalServiceStagingAdvice.updateLayout() {
//249 line
friendlyURLMap = layoutLocalServiceHelper.getFriendlyURLMap(
	groupId, privateLayout, layoutId, StringPool.BLANK, friendlyURLMap);
//**friendlyURLMap will be handle for "{en_US=/3}" due to friendlyURLMap is null**
}

So the fix should firstly add previous validated the layout's friendlyURL and then execute following operation.

Previous validated the layout's friendlyURL occur in 
LayoutLocalServiceImpl.addLayout() {
//290-293 line
friendlyURLMap = layoutLocalServiceHelper.getFriendlyURLMap(
groupId, privateLayout, layoutId, name, friendlyURLMap);

String friendlyURL = friendlyURLMap.get(LocaleUtil.getSiteDefault());
//325 line
layout.setFriendlyURL(friendlyURL);
}

Please help review it.

**Comment by hhuijser** [comment]
@yuhai 

Is this one somehow related to LPS-52927?

**Comment by yuhai** [comment]
Hi Hugo,

It is a little related. However, the roor issue is different.

The issue occurs when create layout by using page template and uncheck "Automatically apply changes done to the page template." The error only occurs when the process of propagation will start. 

**Actually, the issue was caused by by friendlyURL filed of layout and layoutfriendlyurl table have different value. It should not be related with process of export/import. It is related with creating new layout**

Thanks,
Hai

**Comment by hhuijser** [comment]
Sent to Sergio for further review: https://github.com/sergiogonzalez/liferay-portal/pull/1924

**Pull request closed without merging**
