### PR TITLE
LPS-78860 since backend storage var and return type of getAvaliableLo…

### PR DESCRIPTION
**Pull request by arthurchan35**
…cales() have been changed to Set(hashset), it no longer preserve ordering. Plus it's not really beneifital to have ordering anyway. Make left list the same as right list

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Eudaldo for review: https://github.com/ealonso/liferay-portal/pull/1518

**Pull request closed without merging**
