### PR TITLE
LPS-105380 Use lookahead zero-width assertions for better performance

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Hugo,
Can I do this way?

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Also, I am working on applying the new Pattern/Matcher to other SF classes and see if we can fix more issues.

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
