### PR TITLE
LPS-105380_Chaining_20200731

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,
Can we allow subtract() call for chaining?
See: 
https://github.com/liferay/liferay-portal/blob/master/modules/apps/oauth2-provider/oauth2-provider-web/src/main/resources/META-INF/resources/admin/assign_scopes_tab1.jspf#L115

https://github.com/liferay/liferay-portal/blob/master/modules/apps/oauth2-provider/oauth2-provider-web/src/main/resources/META-INF/resources/admin/assign_scopes_tab2.jspf#L96

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang let's not allow chaining on `substract` and fix instead.

**Comment by ling-alan-huang** [comment]
@hhuijser, I got it, I will resend.

**Pull request closed without merging**
