### PR TITLE
 LPS-93513 Temporarily add suppression, Alan will revert when everything is fixed

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

My fix broke two Poshi files, I reverted them and add suppressions temporarily.
See:
https://github.com/brianchandotcom/liferay-portal/commit/ce991ebba3b15cc639ff6173c29aeb63f2b736c5?diff=unified#diff-174d3b2ccf2044404f0f902bd142edd3L241
https://github.com/brianchandotcom/liferay-portal/commit/ce991ebba3b15cc639ff6173c29aeb63f2b736c5?diff=unified#diff-819e6cb0ac59b8283caf7b997fb8fadaL690

SF rules should ignore for multiline comments

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to this pull.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/72219

**Pull request closed without merging**
