### PR TITLE
LPS-114570

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
This bug fix for jsp, hope test will be green as soon as possible, I will do backports for 7.x after this one is merged

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
@brianwulbern maybe we need to quarantine? `WorkflowMetrics#ReassignWorkflowInstance` `Forms#ConfigureAutosave` failures are consistent

cc/ @rodrigocunhaa @cvanut

**Comment by rodrigocunhaa** [comment]
@jpince , the fix for `WorkflowMetrics#ReassignWorkflowInstance` is already on BChan queue: https://github.com/brianchandotcom/liferay-portal/pull/89584

**Comment by jpince** [comment]
Rodrigo's fix pushed to Brian Chan's origin: https://github.com/brianchandotcom/liferay-portal/commit/f576b89c60a48a9f097feb87fa12593325b41109

**Comment by cvanut** [comment]
Hey @jpince there is a fix on the way for the test you mentioned. It failed due to a change performed by App Builder team.

Here's the PR link: https://github.com/carolmariaabb/liferay-portal/pull/82/commits/86027b43fe0aa9d2bf4800e1e0fb6236eedfe9ea

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@yichenroy, @pyoo47 the [modules-unit-project-templates](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/323060//consoleText) suite is failing on this (it seems to be outside the actual test):
```
ERROR: Build step failed with exception
com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input within/between Array entries
 at [Source: (InputStreamReader); line: 15, column: 1665]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipAfterComma2(ReaderBasedJsonParser.java:2331)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2301)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:674)
	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$LongDeser.deserialize(PrimitiveArrayDeserializers.java:759)
Caused: com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input within/between Array entries
 at [Source: (InputStreamReader); line: 15, column: 223] (through reference chain: net.masterthought.cucumber.Trends["durations"]->long[][69])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$LongDeser.deserialize(PrimitiveArrayDeserializers.java:780)
	at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$LongDeser.deserialize(PrimitiveArrayDeserializers.java:723)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3049)
	at net.masterthought.cucumber.ReportBuilder.loadTrends(ReportBuilder.java:197)
Caused: net.masterthought.cucumber.ValidationException: File '/opt/java/jenkins/jobs/test-portal-acceptance-pullrequest-batch(master)/configurations/axis-AXIS_VARIABLE/1/axis-label_exp/!master/cucumber-reports/cucumber-trends.json' could not be parsed as file with trends!
	at net.masterthought.cucumber.ReportBuilder.loadTrends(ReportBuilder.java:199)
	at net.masterthought.cucumber.ReportBuilder.loadOrCreateTrends(ReportBuilder.java:189)
	at net.masterthought.cucumber.ReportBuilder.updateAndSaveTrends(ReportBuilder.java:172)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:111)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:324)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:248)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Cucumber reports' marked build as failure
```

@ling-alan-huang @hhuijser ci-forwards will still fail on LocalFile.Forms#ConfigureAutosave until it's fixed/quarantined.  Sadly, [master stable](https://test-1-0.liferay.com/job/test-portal-testsuite-upstream-controller(master_stable)/) was stuck all day, and I just got it going again after a retrigger.

**Comment by brianwulbern** [comment]
@ling-alan-huang @hhuijser ci-forwards will still fail on LocalFile.Forms#ConfigureAutosave until it's fixed/quarantined.  Sadly, [master stable](https://test-1-0.liferay.com/job/test-portal-testsuite-upstream-controller(master_stable)/) was stuck all day, and I just got it going again after a retrigger.  So even the other fix for `WorkflowMetrics#ReassignWorkflowInstance` hasn't been synced to upstream.

**Comment by brianwulbern** [comment]
[Quarantining](https://github.com/brianchandotcom/liferay-portal/pull/89608) Forms test for the time being.  Please un-ignore it @rodrigocunhaa @carolmariaabb alongside your fix.  Thanks!

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@rodrigocunhaa @cvanut `WorkflowMetrics#ViewPendingItems`([log](https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/396942/consoleText)) ([poshi report](https://testray.liferay.com/reports/production/logs/test-1-20/1591247078406/test-portal-acceptance-pullrequest%28master%29/8687/functional-tomcat90-mysql57-jdk8/12/0/LocalFile.WorkflowMetrics_ViewPendingItems/index.html.gz)) is failing in latest run

**Comment by brianwulbern** [comment]
@Tim-Cao it looks like the acceptance quarantine change [you made here](https://github.com/liferay-continuous-integration/liferay-portal/commit/c3374f3929842a710c1d49fa7e12455310751ed1#diff-4e8f7054c38e35a00aa8a3973b921670R1546) doesn't stop this test from [failing on PRs](https://github.com/hhuijser/liferay-portal/pull/4343#issuecomment-638658434)

**Comment by brianwulbern** [comment]
@hhuijser I'm resending this with an ignore on top here https://github.com/hhuijser/liferay-portal/pull/4368

**Comment by brianwulbern** [comment]
ci:close (trying again at https://github.com/hhuijser/liferay-portal/pull/4368)

**Pull request closed without merging**
