### PR TITLE
LPS-105380 Improve logic to sort sql in test.properties

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

**Issue 1:**
https://github.com/liferay/liferay-portal/commit/bdebb53553e8b3bc94579b4d3fad234590b3cfe1
https://github.com/liferay/liferay-portal/commit/d6cacf681461046ace720fa0c0a7ac5acb45f039
https://github.com/liferay/liferay-portal/commit/9bac1049e312ebe942a16b01b3d61adb36ceb281

I know you have done this a few days ago, I just made some tine improvements.

-----------

**Issue 2:** Format single line SQL clause
I'm not sure if this is an issue, just do it.
https://github.com/liferay/liferay-portal/blob/master/test.properties#L1193

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:stop

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
I like it... Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/86664

**Pull request closed without merging**
