### PR TITLE
[TS] LPS-73636

### PR DESCRIPTION
**Pull request by yuhai**
Hi Hugo,

One EE customer has reported that they are encountering java.io.FileNotFoundException for _sprite.properties related to their custom theme during the server startup process. It seems that this issue is a very rare case with a failure rate of 1%--the customer was only able to reproduce 3 times out of 300 startup events. The problem is that if this error is encountered, the theme fails to load. Sorry we can't reproduce the issue.

The issue is related with java.io.FileOutputStream by checking the error stack (from LPS-73636 description)
```
private native void open0(String name, boolean append)
        throws FileNotFoundException;
```
The native method should be related with local environment. So the issue should be related with local environment. 

Up to a point, the fix belongs to a protection so that theme can be deployed successful when the error occurs.

Reference:
https://dev.liferay.com/develop/tutorials/-/knowledge_base/6-2/using-image-sprites
For can't generate related sprite images/properties, they also can be rendered as individual image files.

If you have other concerns, please kindly let me know.

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by hhuijser** [comment]
@yuhai, we should figure out why this file was not found (I assume you have spend time on that). Did you find anything there?

**Comment by yuhai** [comment]
Hi @hhuijser 

I did some research before submit the fix. I didn't find the similar issue. I tried to find the implementation regarding the native method  so that I can know which case break this.

```
java.io.FileOutputStream.java {

private native void open0(String name, boolean append)
        throws FileNotFoundException;

}
```

But I didn't find the implementation (The implementation was from other language). From my understanding, it should depends on different local environment (hardware or OS).

The fix belongs to a protection. I am not sure whether the similar issue will occur in other places.
Based on your response, I will create one SME to ask the root issue and close the PR.

Regards,
Hai

**Pull request closed without merging**
