### PR TITLE
LPS-105380 Add SF dependent files

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

SF needs to check `source-formatter.properties` and `source-formatter-suppressions.xml` if there are deleted or renamed files in commits.

See issue here: https://github.com/brianchandotcom/liferay-portal/pull/103606

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@ling-alan-huang Nice one!

**Pull request closed without merging**
