### PR TITLE
LPS-56934

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @daledotshan 

I think you're accidentally changing logic here: https://github.com/daledotshan/liferay-portal/commit/97f98c8b1ca4e03475897c8eecc8d00e8306e2d8

set.contains("asdf")

is different from

for (String s : set) {
   s.contains("asdf")
}

The last one will only return true if one of the String equals "asdf", where the second one will already return true if one of the entries contains "asdf".
I assume we should use Bejond's logic and check if any entry contains cdnExcludePath?

**Comment by daledotshan** [comment]
Hey Hugo,
I changed the logic purposely, my logic is more strictly, portal will not use cdn only the path user set equal the friendly url user access.

Portal set friendly url in service method of FriendlyURLServlet class (on here  request.setAttribute(WebKeys.FRIENDLY_URL, getFriendlyURL(pathInfo));)

the friendly like /web/xxxx, /group/xxxxx  etc

**Comment by hhuijser** [comment]
Hey Dale,

I actually think I prefer your more strict logic, so I will go ahead and review this.
It's just that I wasn't sure if you changed accidentally or on purpose. Your commit message made me think it was accidental, because it only mentioned the multiple instances support.
Next time, try to make changes like that clear with your commit message.

**Comment by daledotshan** [comment]
ok, I will make the change with a clearly commit message next time

**Comment by bejondshao** [comment]
Hey @daledotshan @hhuijser , I think the original logic is better. Because during my test, friendly url would change, sometimes it's "/group/control_panel", but sometimes it's "/group/control_panel/manage". Strict logic seems not so friendly for portal-ext settings. If customer sets exclude url "/group/control_panel", then we can't disable cdn when friendly url is "/group/control_panel/manage".

**Comment by bejondshao** [comment]
And also, dale removed line "cdnHost = PortalUtil.getCDNHost(request);", which is essential.

**Comment by hhuijser** [comment]
Hey @bejondshao 

Thanks for explaining that. From your example it does make sense that we are getting a bit too strict now. What do you think, Dale?

Either way, I am going to close this for now.
Let's make sure that from the comments in portal.properties it's very clear what exactly the meaning of this property is. Right now, it doesn't even tell you we're dealing with friendlyURLs here?

**Comment by daledotshan** [comment]
Bejond is correct, cdnHost = PortalUtil.getCDNHost(request) is essential

**Pull request closed without merging**
