### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
@hhuijser, I am resolving SF errors.

**Comment by hhuijser** [comment]
@ling-alan-huang , thanks! Can you send me a new pull? Closing this one

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/4124

**Pull request closed without merging**
