### PR TITLE
LPS-84119 Enforce variable name for *ExceptionMapper.java

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi @hhuijser,

The issue here: liferay@2f25357

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/75410

Please check my changes

**Comment by ling-alan-huang** [comment]
Too many changes, my bad.
Your changes are good. Today I am working on Peter's yaml issue.

**Pull request closed without merging**
