### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward https://liferay.slack.com/archives/C19PWQ74J/p1591212749430100?thread_ts=1591212578.429600&cid=C19PWQ74J

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by brianwulbern** [comment]
@yichenroy I think you already got emailed for [this one](https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/395280//consoleText):
```
[beanshell] Executing commands: git for-each-ref refs/heads --format="%(refname)"
[beanshell] Executing commands: git rev-parse ecuting Bash commands.
[beanshell] java.lang.NullPointerException
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.getUpstreamLocalGitBranch(GitWorkingDirectory.java:1673)
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.checkoutUpstreamLocalGitBranch(GitWorkingDirectory.java:195)
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.cleanTempBranches(GitWorkingDirectory.java:229)
```

**Comment by yichenroy** [comment]
ci:forward

Retesting, we took down the bad slave causing null pointer exception in the previous test result:
```
[beanshell] Executing commands: git rev-parse ecuting Bash commands.
[beanshell] java.lang.NullPointerException
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.getUpstreamLocalGitBranch(GitWorkingDirectory.java:1673)
```

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
