### PR TITLE
LPS-71333 NullPointerException when sorted the DM

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
ci:test

**Comment by daviddotzhang** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@daviddotzhang, why is `results` null?
Looks like that should not happen?

See https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/dao/search/SearchContainer.java#L575

**Comment by daviddotzhang** [comment]
@hhuijser  we are able to use the setResults to make  "_result"  NULL.
this is caused by from /liferay-portal/modules/apps/collaboration/document-library/document-library-web/classes/META-INF/resources/document_library/view_entries.jsp.

while I think we need to fix it in a common way in "SearchContainerResultsTag.java"

**Comment by hhuijser** [comment]
It's still a random place to do the fix, since we have many other places where we can have a NPE if `results` is null. Just search for `searchContainer.getResults()` and you can easily find em.

So, either we somehow never allow `results` to be null, or we have to be much more careful in places like `view_entries.jsp`

I would rather fix this one by changing the initial value of `results` to `new ArrayList<>()` on line 88 of `view_entries.jsp` (and maybe other places as well?)

**Comment by daviddotzhang** [comment]
@hhuijser,  I have updated the pull request, also tested blog portlet, which does not have the NPE problem.

**Comment by hhuijser** [comment]
Sent to Eudaldo for review: https://github.com/ealonso/liferay-portal/pull/1540

**Pull request closed without merging**
