### PR TITLE
LPS-84119 Jsp format

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/ec438a265757dee958664fa833f3f5c7be66444d

master-private: https://github.com/hhuijser/liferay-portal-ee/pull/2959
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/2960
7.1.x-private: https://github.com/hhuijser/liferay-portal-ee/pull/2961
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/2962
7.0.x-private: https://github.com/hhuijser/liferay-portal-ee/pull/2963

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/78562

**Pull request closed without merging**
