### PR TITLE
LPS-105380 BaseEmptyLinesCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issues:
https://github.com/brianchandotcom/liferay-portal/pull/107066#issuecomment-918449350
https://github.com/brianchandotcom/liferay-portal/pull/107436#issuecomment-922109894

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related my changes.

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
