### PR TITLE
LPS-105380_57_alan

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
@hhuijser ,

If I didn't change [this](https://github.com/hhuijser/liferay-portal/pull/4108/commits/66f186ea54ff520230b3b15d095ec15ba896fa97#diff-179747575e35f46d0c0e9c8a59ade1f7L38), SF will complains:
`Combine calls 'JSONFactoryUtil.createJSONArray' (39) and 'availableDefinitionsJSONArray.put' (131) into single call 'JSONUtil.put': /home/alan/liferay_code/master/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-web/src/main/resources/META-INF/resources/admin/process/fields.jsp 39 (Checkstyle:JSONUtilCheck)`

So I combined them, then `compileJSP FAILED`:
```
     [exec] > Task :dxp:apps:portal-workflow:portal-workflow-kaleo-forms-web:compileJSP FAILED
     [exec] 
     [exec] > Task :dxp:apps:saml:saml-impl:jar
     [exec] > Task :dxp:apps:saml:saml-impl:autoUpdateXml SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-forms-web/build/jspc/org/apache/jsp/admin/process/fields_jsp.java:906: error: cannot find symbol
     [exec]           out.print( availableDefinitionsJSONArray.toString() );
     [exec]                      ^
     [exec]   symbol:   variable availableDefinitionsJSONArray
     [exec]   location: class fields_jsp

```

Looks like it's the scope issue.

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
The failures are not related to this pull.

**Comment by ling-alan-huang** [comment]
@hhuijser, I just also fixed violation on ee repo, and sent to you.

7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3036
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3037
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3038
7.0.x-private: https://github.com/hhuijser/liferay-portal-ee/pull/3039

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/87222

**Pull request closed without merging**
