### PR TITLE
LPS-104679 Apply checkstyles to jsp_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

_Related pulls:_
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3026
7.1.x:https://github.com/hhuijser/liferay-portal-ee/pull/3024
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3023

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Hey @ling-alan-huang, I sent some of this to Brian: https://github.com/brianchandotcom/liferay-portal/pull/83867

I left out the `RedundantBranchingStatementCheck`
For *.java files this check makes sense and we can always remove the entire if statement.
For *.jsp, there could be tags that are affected (as you can see in your SF commit), and we should leave things as they are.

Sorry for responding so late, I could have saved you work if I had looked at this in detail earlier.

**Comment by ling-alan-huang** [comment]
Hi @hhuijser, you are right, I should think more about it.

**Pull request closed without merging**
