### PR TITLE
LPS-79348 filter out entries that are not displayable, because there …

### PR DESCRIPTION
**Pull request by arthurchan35**
…is an inconsistency between dynamic view and manual view of asset publisher.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Feels like this is not the right location for the filtering.

How come we have different results for dynamic view and manual view? What are the method calls to get the entries in the two jsp files?

**Comment by arthurchan35** [comment]
@hhuijser 
Dynamic view is calling here:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/asset/asset-publisher-web/src/main/resources/META-INF/resources/view_dynamic_list.jspf#L18
Manual view is calling here:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/asset/asset-publisher-web/src/main/resources/META-INF/resources/view_manual.jspf#L18

The difference is that for dynamic view, it eventual calls one of the overloaded method getAssetEntries(), the one I am adding filtering logic to.
While manual view eventual calls the other getAssetEntries(), which has filtering logic already, see here:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/asset/asset-publisher-web/src/main/java/com/liferay/asset/publisher/web/util/AssetPublisherUtil.java#L513

**Comment by hhuijser** [comment]
Thanks! Very clear explanation.

Instead of changing the API, can we add another method and add parameter `boolean includeNonVisibleAssets`?

**Comment by hhuijser** [comment]
Sent to Eudaldo for review: https://github.com/ealonso/liferay-portal/pull/1564

**Pull request closed without merging**
