### PR TITLE
LPS-136864 XMLServiceFinderNameCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Hugo,

See: https://github.com/brianchandotcom/liferay-portal/pull/105225

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
