### PR TITLE
LPS-104679 SF some JSP

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang. Very nice! Let's see if the tests pass...

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by ling-alan-huang** [comment]
@hhuijser, I don't understand the test failures, if you use forward test to yourself, this pull will not be sent to Brian, right?

**Comment by hhuijser** [comment]
@ling-alan-huang, let's see

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@vicnate5 is there a bug here? see blacklist & setupwizard tests

@patriciajeanperez @rodrigocunhaa flaky tests? `MessageboardsUsecase#SearchMBThreadCategory` `WorkflowMetrics#ViewSLABreachesOfTopSteps`

**Comment by vicnate5** [comment]
@jpince There is a new change in upstream failing this Blacklist tests, it not related to this PR.
Pulling them alongside the flaky setup wizard tests: https://github.com/brianchandotcom/liferay-portal/pull/87488

**Comment by patriciajeanperez** [comment]
@jpince Looks flaky to me. I went ahead and put the test in quarantine. https://github.com/brianchandotcom/liferay-portal/pull/87492

cc @austinchiang

**Comment by jpince** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/87505

**Comment by rodrigocunhaa** [comment]
@jpince , I was OoO due to a national holiday. Yes, it is flaky. I'll quarantine it in case it keeps failing.

**Pull request closed without merging**
