### PR TITLE
LPS-100170 Add SF rule to enforce moving non-MP, deprecated apps

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-100170

Related pulls:
master-private: https://github.com/hhuijser/liferay-portal-ee/pull/2926
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/2927

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures No.4 is in private branch.

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/77341

**Pull request closed without merging**
