### PR TITLE
LPS-130505_UnnecessaryMethodCallsCheck_20210415_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/brianchandotcom/liferay-portal/commit/854d18b69dd3823ff6d1cbdd8a7c469d4936e083

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Hey @ling-alan-huang very nice!

Is it possible to simplify your check by checking JAVA_CLASS (we can find the childJavaTerms and JavaMethod has the return information already)?

**Comment by ling-alan-huang** [comment]
I got it, I will try that way.

**Pull request closed without merging**
