### PR TITLE
LPS-84119 Yaml: Enforce double quote instead of single quote

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/brianchandotcom/com-liferay-osb-asah-private/commit/ee0b0b4f907c14d4c1ae435ab6fc6f9ccb7b7334

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures is not related to this pull, it is fixed here: https://github.com/hhuijser/liferay-portal/pull/3883

**Comment by ling-alan-huang** [comment]
Closing, I will resend.

**Comment by ling-alan-huang** [comment]
Reopened, the failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/81424

**Pull request closed without merging**
