### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by susanchen3** [comment]
Hi @hhuijser based on the most recent relevant run, the failures look flaky to me. Looks ok to manually forward :+1: 

LocalFile.FormRules#SyncBetweenFormAndRuleBuilder is a common Forms failure reported here: [LRQA-72017](https://issues.liferay.com/browse/LRQA-72017)

LocalFile.PortalSmoke#Smoke looks like a flaky Search failure reported here: [LPS-117223](https://issues.liferay.com/browse/LPS-117223)

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/111922

**Pull request closed without merging**
