### PR TITLE
LPS-121804_Python_ImportPackage

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang looking very good!

One small thing. Can you deprecate the constructor in `ImportPackage` instead of removing? We should avoid a major version increase for `portal-impl`

**Comment by hhuijser** [comment]
Think Jason has pushed up the copyright stuff by now, so you can take that out?

**Comment by ling-alan-huang** [comment]
Closing, I will resend.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/5214

**Pull request closed without merging**
