### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@jpince, no unique failures, but still failing :(

**Comment by jpince** [comment]
Asked QA for help in https://liferay.slack.com/archives/CL84ZPHAT/p1588599627416400. Please use this channel in the future, I will jump in if needed.
`DLAdminDisplayContextTest.testGetSearchContainer` will be resolved by https://github.com/brianchandotcom/liferay-portal/pull/88297

**Comment by jpince** [comment]
@hhuijser all issues have been resolved thus far except for https://issues.liferay.com/browse/LPS-112939. You can ignore this test if it's not fixed by the time you get in today.

**Comment by jpince** [comment]
@hhuijser fix is here: https://github.com/shuyangzhou/liferay-portal/pull/9035/commits/ce1f052a32ff0560f8127a51a53b5f0d3d5e04d3, feel free to cherry-pick to your branch, as it probably won't make it to upstream until much later today or tomorrow.

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
@austinchiang sharepoint test failures?

**Comment by austinchiang** [comment]
@jpince Those test shouldn't be running in pull requests. I am fixing them [here](https://github.com/brianchandotcom/liferay-portal/pull/88424). Thanks!

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
