### PR TITLE
LPS-43918 Removing CalEvent from taglibs

### PR DESCRIPTION
**Pull request by brandizzi**
Hello Hugo. @marcellustavares asked me to submit this pull request for your review. Please let me know of any problems.

Thanks!

### CODE REVIEW

**Comment by marcellustavares** [comment]
Hey @hhuijser, we're sending this PR to you b/c SB is not propagating the deprecate annotation we're setting for the CalEvent model. Could you please take a look? Ideally we'd like to deprecate the model but it's not possible we can just leave the annotation on the service layer.

Thx

**Comment by hhuijser** [comment]
Hey @marcellustavares 

Just checking if I understand correctly..
Looks like SB is propagating the deprecation tags/annotations, but not the SuppressWarnings annotation, right?

I think this is how things are supposed to be. You can see in service_util.ftl how we're only propagating the deprecation annotations and this is how we've been doing this for methods with SuppressWarnings annotations as well.

**Comment by marcellustavares** [comment]
Hey Hugo, sorry for the confusion. I've anotated the Caleventimpl model but the problem is SB is not propagating to the interface. 

Is this something supported? Or the propagation just works for the service layer? 

Thx

**Comment by hhuijser** [comment]
Ah, I see what you mean now...
I think we should propagate the depreciation tags/annotations there as well.
I'll look into that a bit more

**Comment by hhuijser** [comment]
Added logic to SB and sent to Brian for further review: https://github.com/brianchandotcom/liferay-portal/pull/27933

**Pull request closed without merging**
