### PR TITLE
LPS-93509 Poshi Script SF: Enforce new lines between commands

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,
If this pull is OK to you, please send to Kenji to SF Poshi Script files.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
SF test result: https://github.com/ling-alan-huang/liferay-portal/pull/63#issuecomment-492172804

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@ling-alan-huang 

Let's catch more missing empty lines. (@kenjiheigel, can you confirm this is okay?)
Also enforce empty line when missing for cases like:  

https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduseree/wcm/contenttargeting/BaseContentTargetingUserSegment.testcase#L3

https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduseree/wcm/contenttargeting/BaseContentTargetingUserSegment.testcase#L11

https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduseree/wcm/contenttargeting/BaseContentTargetingUserSegment.testcase#L68

Also, you can simplify the regex a little by not making the group non-capturing: https://github.com/hhuijser/liferay-portal/pull/3561/files#diff-d0c9b782d94c25598c892ad9a4a754e6R54

**Comment by ling-alan-huang** [comment]
> @ling-alan-huang
> 
> Let's catch more missing empty lines. (@kenjiheigel, can you confirm this is okay?)
> Also enforce empty line when missing for cases like:
... ...
... ...
> Also, you can simplify the regex a little by not making the group non-capturing: https://github.com/hhuijser/liferay-portal/pull/3561/files#diff-d0c9b782d94c25598c892ad9a4a754e6R54

Got it, closing and I will do it later.
Thanks.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/3566

**Comment by kenjiheigel** [comment]
@hhuijser, @ling-alan-huang yep these changes are good. Thanks guys!

**Pull request closed without merging**
