### PR TITLE
LPS-136864 XMLServiceFinderNameCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Hugo,

Issue: https://github.com/brianchandotcom/liferay-portal-ee/pull/34935#issuecomment-881171343

I opened a new ticket for this.

I will enable this check when I fixed violations.

Here is the list of violations:
Also, I fixed No.9 in this pull by three commits:
https://github.com/liferay/liferay-portal/commit/ab0610ed7677f39437598950cf9b247516459e37, 
https://github.com/liferay/liferay-portal/commit/ea9cbe1c76e942ec08762ddc3f12abf6427a7be2,
https://github.com/liferay/liferay-portal/commit/7e76a0f0dcad9ed87e14588d429ab76343e27970

```
java.lang.Exception: Found 46 formatting issues:
1: Finder name 'OAuthApplication#C_N' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/archived/oauth-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
2: Finder name 'OAuthApplication#U_N' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/archived/oauth-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
3: Finder name 'SyncDLFileVersionDiff#ExpirationDate' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/archived/sync-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
4: Finder name 'SyncDLObject#M_R' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/archived/sync-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
5: Finder name 'SyncDLObject#M_R_NotE' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/archived/sync-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
6: Finder name 'SyncDLObject#T_NotE' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/archived/sync-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
7: Finder name 'SyncDLObject#TreePath' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/archived/sync-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
8: Finder name 'SyncDevice#C_U' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/archived/sync-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)


9: Finder name 'BookmarksFolder#F_C_P_NotS' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/bookmarks/bookmarks-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
10: Finder name 'CalendarResource#C_C_A' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/calendar/calendar-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
11: Finder name 'CommerceDiscountUsageEntry#A_D' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-discount-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
12: Finder name 'CommerceDiscountUsageEntry#A_O_D' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-discount-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
13: Finder name 'CommerceDiscountUsageEntry#O_D' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-discount-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
14: Finder name 'CommercePriceList#CatalogBasePriceList' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-price-list-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
15: Finder name 'CommerceTierPriceEntry#C_LtM' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-price-list-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
16: Finder name 'CommerceTierPriceEntry#C_LtM_S' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-price-list-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
17: Finder name 'CommerceAddress#C_C_C_C' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
18: Finder name 'CommerceOrderItem#C_I' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/commerce/commerce-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
19: Finder name 'DLSyncEvent#ModifiedTime' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/document-library/document-library-sync-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
20: Finder name 'JournalFolder#F_C_P_NotS' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/journal/journal-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
21: Finder name 'KBArticle#G_S_L' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/knowledge-base/knowledge-base-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
22: Finder name 'KBArticle#G_S_M' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/knowledge-base/knowledge-base-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
23: Finder name 'KBArticle#G_S_S' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/knowledge-base/knowledge-base-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
24: Finder name 'MBMessage#T_notS' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/message-boards/message-boards-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
25: Finder name 'OAuth2Authorization#AccessTokenContentHash' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
26: Finder name 'OAuth2Authorization#RefreshTokenContentHash' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
27: Finder name 'KaleoTaskAssignmentInstance#assigneeClassName' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/portal-workflow/portal-workflow-kaleo-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
28: Finder name 'KaleoTaskAssignmentInstance#kaleoTaskInstanceTokenId' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/portal-workflow/portal-workflow-kaleo-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
29: Finder name 'SharingEntry#ExpirationDate' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/apps/sharing/sharing-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
30: Finder name 'SamlIdpSpSession#CreateDate' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/dxp/apps/saml/saml-persistence-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
31: Finder name 'SamlIdpSsoSession#CreateDate' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/dxp/apps/saml/saml-persistence-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
32: Finder name 'SamlSpAuthRequest#CreateDate' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/dxp/apps/saml/saml-persistence-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
33: Finder name 'SamlSpMessage#ExpirationDate' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/modules/dxp/apps/saml/saml-persistence-service/service.xml (SourceCheck:XMLServiceFinderNameCheck)
34: Finder name 'Group#C_T_S' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
35: Finder name 'Group#G_C_C_P' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
36: Finder name 'Group#G_C_P' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
37: Finder name 'Group#G_C_P_S' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
38: Finder name 'Layout#G_P_P_LtP' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
39: Finder name 'Organization#C_T' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
40: Finder name 'Organization#Locations' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
41: Finder name 'Organization#O_C_P' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
42: Finder name 'PluginSetting#C_I_T' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
43: Finder name 'User#U_C' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
44: Finder name 'UserGroup#U_C_P' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portal/service.xml (SourceCheck:XMLServiceFinderNameCheck)
45: Finder name 'DLFolder#F_C_P_NotS' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portlet/documentlibrary/service.xml (SourceCheck:XMLServiceFinderNameCheck)
46: Finder name 'DLFolder#G_M_T_H' should be combined by finder colume names(at least the first character) following by each comparator prefix with delimiter '_': /Users/alan/liferay_code/master/liferay-portal/portal-impl/src/com/liferay/portlet/documentlibrary/service.xml (SourceCheck:XMLServiceFinderNameCheck)

```

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Rebase

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Rebase and fixed SF issue.

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
