### PR TITLE
LPS-63910

### PR DESCRIPTION
**Pull request by bejondshao**

### CODE REVIEW

**Comment by bejondshao** [comment]
Hey Hugo, 

It says ruby compiles failed. I think it's nothing with my fix.

**Comment by hhuijser** [comment]
@bejondshao @daledotshan

Couple of things:

1. We never use Validator.isNotNull for objects like User, you should use user != null

2. Let's use existing language key "the-user-could-not-be-found" instead of adding a (very similar) new one.

3. Not sure if I like the fact that you simply placing that error message in your jsp there. Usually those x-not-be-found messages are handled through NoSuchXExceptions. Can we do that for this code? (search for 'could-not-be-found' in *.jsp to see what I mean).
If not, I'd probably still would use the liferay-ui:message tag instead?

**Comment by bejondshao** [comment]
Hey @hhuijser ,

for 3, I think we can't through NoSuchXExceptions, because this kind of exception shows in jsp with red or blue area to notice user, while in this use case, the info is just shown in an input field of a table. You can find the UI in LPS-63910. So let's keep the key in jsp.

for 2, "the-user-could-not-be-found" seems ok. But will it be a little longer to put it in a field? If it ok, please change for it.

**Comment by bejondshao** [comment]
Hey Hugo,

I redo the pull request as you asked.

**Comment by bejondshao** [comment]
ci:retest

**Comment by bejondshao** [comment]
Hey Hugo,

I really don't see the connection with the fails. My change just in the jsp and not uses other API but fetchXXX(). 

And there's an error "Could not find com.liferay.portal:com.liferay.portal.kernel:1.0.4-SNAPSHOT.", which is not about the changing.

Thanks

**Comment by hhuijser** [comment]
Sent to Drew for review: https://github.com/drewbrokke/liferay-portal/pull/179

**Pull request closed without merging**
