### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@jpince

**Comment by jpince** [comment]
ci:test:relevant @hhuijser this needs a retest due to the aborted builds. The command might not work due the [GH webhook outage](https://liferay.slack.com/archives/C19PWQ74J/p1618588389137100). Please check again later to make sure tests started.

**Comment by hhuijser** [comment]
ci:forward

**Comment by jpince** [comment]
ci:stop duplicate relevant test run

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
@yichenroy we accidentally initiated relevant twice on this PR. When I commented `ci:stop`, I expected only one of the jobs to stop. Does `ci:stop` kill all builds in progress?

**Comment by jpince** [comment]
@hhuijser sorry for the delay, and thank you for allowing your PR to be the test case for CII functionality :sweat_smile:

**Comment by hhuijser** [comment]
@jpince, anytime :)

**Comment by yichenroy** [comment]
@jpince yes `ci:stop` blanket stops anything that is in progress.

If there is a specific test suite you want to stop then you can do `ci:stop:<testsuite>`, however in this case if you have two identical test suites running I don't think we have any way to stop only one of them through github comments.

**Pull request closed without merging**
