### PR TITLE
LPS-74544 Automatically remove dependencies that do not have export packages

### PR DESCRIPTION
**Pull request by petershin**
This is just the first pass. It only works for portal master.

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by hhuijser** [comment]
@petershin 
Can we use SourceFormatterUtil.filterFileNames to retrieve the ExportPackageBundleSymbolicNames instead of doing a Files.walkFileTree?
Scanning directories is slowing down SF, trying to avoid when I can.

See https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/JSPTagAttributesCheck.java#L452-L454

Also, let's open a new ticket for this

**Comment by petershin** [comment]
@hhuijser - Created a new ticket [LPS-77143](https://issues.liferay.com/browse/LPS-77143)

The files in _allFileNames changes based on the SF args passed and the new check needs to see all bnd files in portal.

Here are some other options to remove bad dependencies:

- integrate gradle plugin that takes care of removing bad dependencies into SF: [nebula-lint-plugin](https://github.com/nebula-plugins/gradle-lint-plugin/wiki/Unused-Dependency-Rule)
- dumb down the check and have a property that has a list of bad dependency names

The second approach means the performance team will need to manually add a new property after they update a module.  Its not ideal, but might be a good compromise.  What do you think?

**Comment by hhuijser** [comment]
@petershin 
Can you check how much this slows down things on a full SF and when doing a format-source-current-branch?

Use `setShowDebugInformation`

**Comment by petershin** [comment]
Made some minor updates: https://github.com/hhuijser/liferay-portal/pull/3139  Will post test results there.

**Pull request closed without merging**
