### PR TITLE
LPS-105380_Chaining_20200802_1

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:bundle

**Comment by hhuijser** [comment]
@ling-alan-huang see https://github.com/hhuijser/liferay-portal/pull/4594

(only took the chaining commits, the other commits are already included in all my other pulls)

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4595

@ling-alan-huang I only took the chaining commits.
The other commits are already included in the other pull requests in my queue

**Pull request closed without merging**
