### PR TITLE
LPS-134571 Move deps from bintray to s3

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:gradle-plugins

**Comment by lawrence-lee** [comment]
cc @petershin

**Comment by hhuijser** [comment]
ci:forward

**Comment by lawrence-lee** [comment]
@hhuijser I can send fixes for the gradle tests in follow up pulls. But this PR needs to go through in order for the tests to run.

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/103654

**Pull request closed without merging**
