### PR TITLE
LPS-74544 Allow chaining for WebClient

### PR DESCRIPTION
**Pull request by petershin**
@Ithildir

### CODE REVIEW

**Comment by Ithildir** [comment]
Thank you @petershin!!

**Comment by hhuijser** [comment]
@Ithildir @petershin , what's the use case for this?

**Comment by Ithildir** [comment]
It's about https://liferayeng.slack.com/archives/C1SJ64S9X/p1524209837000207?thread_ts=1523963823.000191&cid=C1SJ64S9X.

**Comment by hhuijser** [comment]
@petershin @Ithildir, ugh, I knew that was going to happen at some point...
When retrieving the variable type, using Checkstyle, SF is not able to retrieve the type, when it's a protected var that is defined in a super class.

I see you got a workaround for now, using `checkstyle.chaining.check.allowedClassNames`.
I'll see if I can make SF smart enough to handle protected vars, so not merging this for now.

**Pull request closed without merging**
