### PR TITLE
LPS-96091 Add SF rules for HTML self-closing tags

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-96091

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/73763

**Comment by hhuijser** [comment]
There was a conflict, I fixed it here: https://github.com/brianchandotcom/liferay-portal/pull/73764

**Comment by ling-alan-huang** [comment]
Good changes.

**Pull request closed without merging**
