### PR TITLE
LPS-105380 TaglibUtil.java

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issue: https://github.com/liferay/liferay-portal/commit/17aafda078de618fdff931a745a8c02ada3d5fda

Can I do this way?

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
Nope, this one fixed the issues: https://github.com/liferay/liferay-portal/commit/282ed18c

**Comment by hhuijser** [comment]
Just tested (without your fix), and both violations in that pull seem to get fixed by SF after my commit

**Comment by ling-alan-huang** [comment]
@hhuijser I don't understand it, I manually changed `large="<%= true %>"` to `large="true"`, SF doesn't fix it. 

Your regex fix is changing tag naming rule, with your fix SF can sort `CPCatalogEntry` and `large`.

**Comment by hhuijser** [comment]
@ling-alan-huang I tested again, and both changes from that pull got fixed by current SF. Gonna close this pull

**Pull request closed without merging**
