### PR TITLE
LPS-119134 LPS-122478 Delete Solr 7

### PR DESCRIPTION
**Pull request by BryanEngler**
hey hugo, just wondering if you could take a look at the last commit in regards to source formatter and make sure im not deleting something im not supposed to (or if theres any additional things i should delete that i missed). thanks!

### CODE REVIEW

**Comment by hhuijser** [comment]
@BryanEngler your commit looks good.
Do we still need that check in 7.x.x branches though?

**Comment by BryanEngler** [comment]
@hhuijser sounds good
yes, solr will still be in 7.3.x and below. for 7.4 we are completely removing solr

**Comment by BryanEngler** [comment]
i actually did have one other question. SF seems to take a long time on this branch and then fails
https://github.com/BryanEngler/liferay-portal/pull/537#issuecomment-714755188
https://github.com/BryanEngler/liferay-portal/pull/537#issuecomment-716721888

any idea why?

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
never mind, looks like its failing upstream too https://issues.liferay.com/browse/LRQA-62652

**Pull request closed without merging**
