### PR TITLE
sf0410

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

@patriciajeanperez flaky test? `CPRoles#AssignNewUserToRegularRole`

**Comment by patriciajeanperez** [comment]
Yes, I put the test in quarantine in the meantime. https://github.com/brianchandotcom/liferay-portal/pull/87492. Thanks @jpince!

**Comment by jpince** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:test:relevant

**Pull request closed without merging**
