### PR TITLE
LPS-93505 Poshi Script SF: Sorting the names of commands in macro files or function files

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

This check can change over 80 Poshi Script files, if it is OK for you, we would sent to Kenji.

Thanks.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
SF test see: https://github.com/ling-alan-huang/liferay-portal/pull/59#issuecomment-487472546

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Sent to Kenji for review: https://github.com/kenjiheigel/liferay-portal/pull/489

**Comment by ling-alan-huang** [comment]
@hhuijser, your changes are very good.

**Pull request closed without merging**
