### PR TITLE
LPS-78406 due to code changes from LPS-70467, parent class of secureFilter forces to true, thus we re-pick up property in sharePointFilter init.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Hi @arthurchan35,

 I reused your commit message because it was certainly appropriate, but made some changes to be able to not only set the property but override the isFilterEnabled method. This way the new property can be read since the SecureFilter.isFilterEnabled always returns true.

Let me know if you have any doubts related with these changes please :)

Kind regards.

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by hhuijser** [comment]
Thanks @marianoalvarosaiz !

Sent to Tomas for further review: https://github.com/topolik/liferay-portal/pull/490

**Comment by marianoalvarosaiz** [comment]
Hi @arthurchan35,
 about your second proposal: it does not work. It's ok calling the setter method from the _SharepointFilter.init_ method, but it isn't enough because when you call the _isFilterEnabled_ is going to call its parent method that is overridden and will always return true. So, although _isFilterEnabled will have the correct information it isn't retrieved when calling the isFilterEnabled. For example, with _com.liferay.portal.sharepoint.SharepointFilter=false_ the setter will assign false to _BasePortalFilter._filterEnabled_, but calling _SharepointFilter.isFilterEnabled_ will call _SecureFilter.isFilterEnabled_ that always returns true. So the _SharepointFilter_ will appear as enabled when is not.

Regarding the first proposal, you're right in that the only way to disable the _SecureFilter_ would be by explicitly disabling it in the _portal-ext.properties_, but that's what we're trying to avoid. We removed the property from _portal.properties_, but anyway if someone still has it on their _portal-ext.properties_ the _SecureFilter_ would be disabled, and that's something we cannot accept.

Probably the solution of changing the __filteredEnabled_ to protected would have been the best option, but it implies widening the visibility of the attribute and affecting other implementations.

Kind regards.

**Comment by arthurchan35** [comment]
@marianoalvarosaiz,
Thanks for reminding me the overridden method, I forgot about it ealier.
So what do you think about my second proposal + removing the overridden method in secureFilter? Because you have already forced it to be true in SecureFIlter.init?

**Comment by marianoalvarosaiz** [comment]
Hi @arthurchan35,
 it doesn't sound bad, the problem is that programmatically the value could be changed using the _setFilterEnabled_ and in that case, even if during the init we force the enabling of the filter, the _SecureFilter_ could be disabled. That's why we override the _SecureFilter.isFilterEnabled_ to always return true. Because the setter is public we cannot prevent anyone from calling it, but at least we can ensure that even after setting it to false it will appear as enabled.
Kind regards.

**Comment by arthurchan35** [comment]
@marianoalvarosaiz,
I dont know. It sounds like we are worrying bit too much. Yes theoretically speaking, someone can use the setter outside, but it's like saying we have to think of all possible cases to prevent every potential wrong use cases.
If someone writes some code to set it to true in a commit, then that commit should not be approved at all.

After talking to Samuel Kong, we have come up a comprised solution, let we know what you think:
my second proposal + overriding the getter method in sharedPointFilter so that in sharePointFilter we will again read from member field.

**Comment by arthurchan35** [comment]
@marianoalvarosaiz 
Do we have an update?

**Comment by hhuijser** [comment]
New pull: https://github.com/marianoalvarosaiz/liferay-portal/pull/83

**Pull request closed without merging**
