### PR TITLE
LPS-56442

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Hugo,
This issue caused by we use contains method to check a plugin type and get wrong plugin type
for example hook default-web-content-hook, this hook contain "web" character in hook name, portal will treat it as a web type not a hook type, actually this plugin resides in hook folder

I wrote regular expression to check plugin type more strictly.
for example the following plugin names portal will treat them as hook plugin 
default-web-content-hook.war(zip)
default-web-content-hook-7.0.0.1.war(zip)
default-web-content-hook-7.0.0.1+.war(zip)

for example the following plugin names portal will treat them as  web plugin 
default-hook-content-web.war(zip)
default-hook-content-web-7.0.0.1.war(zip)
default-hook-content-web-7.0.0.1+.war(zip)

Please help to check if the solution is reasonable.

**Comment by hhuijser** [comment]
Hey @daledotshan 

A few things regarding your fix.

1. It looks like the method isJarFile has become redundant after your fix. For every case where we check isJarFile, we already know that only war/hook files are allowed (either through one of your regex or because we already call isMatchingFile).
Actually, even before your fix, we already had a few cases where we didn't need to call isJarFile (in isHookPlugin, isThemePlugin and isWebPlugin)

2. Before your fix, in every method we checked the extension to be either war or hook except for the method isExtPlugin. In your fix, you added that check there as well with your regex.
Did you double check if that method on purpose allowed other extensions as well (except for .jar)?

3. Try to avoid chaining: _webPluginPattern.matcher(fileName).find()
If you want to keep it on one line, you could do fileName.matches(regexString).

4. Keep regex as simple as possible. It makes it better readable and less chance for error.
Example:

-[t|T][h|H][e|E][m|M][e|E] --> -(theme|Theme)

This does the same, unless you want to allow something like tHeME (but that's not the case, I think). You made 2 little errors that you probably would not have made if you had done the simpler option (for extPluginPattern you did [e|T] and for webPluginPattern you did [e|W]).

I think I'd write the regex like this: "-(theme|Theme)[-.0-9]*\\+?\\.(war|zip)$"

Thanks

**Comment by daledotshan** [comment]
Hey Hugo,
I updated this pull request please help to check it.

One thing I want to mentioned is that I did not remove following code in method isMatchingFile(File file, String checkXmlFile) because the method deploy of class PortletAutoDeployListener need it
if (!isMatchingFileExtension(file)) {
    return false;
}

If we really want to remove it, I think we need to call method isMatchingFileExtension several times  in class PortletAutoDeployListener (I do not like it), if you have good idea please let me know

Thanks,
Dale

**Comment by hhuijser** [comment]
Sent to Jorge for further review: https://github.com/JorgeFerrer/liferay-portal/pull/551

**Comment by hhuijser** [comment]
Sent to Ray for further review: https://github.com/rotty3000/liferay-portal/pull/909

**Comment by hhuijser** [comment]
Sent to Miguel for review: https://github.com/migue/liferay-portal/pull/480

**Pull request closed without merging**
