### PR TITLE
LPS-93506 Poshi Script SF: Sorting of annotations

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
Looks good! Sent to Brian for review: https://github.com/brianchandotcom/liferay-portal/pull/71306

**Pull request closed without merging**
