### PR TITLE
LPS-99481 Add SF rules for YAML: Block Chomping Indicator

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-99481

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
SF failures are not related to my changes.

**Comment by hhuijser** [comment]
@ling-alan-huang 
Looks really good!
Can you make the following (small) changes and resend?

- rename the test files, maybe simply `StyleBlock` instead of `DoNotFormatStyleBlock`?
- return `List<String>` instead of `String[]` for `YMLSourceUtil.getContentBlocks`? Or is there specific reason we can't do that?

Thanks!

**Comment by ling-alan-huang** [comment]
@hhuijser,

Sure, I will resend, closing..

**Comment by ling-alan-huang** [comment]
Resend: https://github.com/hhuijser/liferay-portal/pull/3693

**Pull request closed without merging**
