### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
ci:test:sf

**Comment by jpince** [comment]
@tinatian `     [java] java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./portal-impl/src/com/liferay/portal/servlet/JasperVersionDetector.java`
https://test-1-7.liferay.com/job/test-portal-source-format/3152/console

**Comment by tinatian** [comment]
@hhuijser Could you please fix this? This is going to block enabling license for commerce modules.

Thanks.
Tina.

**Comment by jpince** [comment]
ci:test:sf I saw errors like this in upstream yesterday, but they have since been resolved. I'm hoping that means this will pass.

**Comment by hhuijser** [comment]
@jpince @tinatian we're getting runs of over an hour and `OutOfMemoryError` for `ant format-source-all` since we merged `commerce` into master.
Still figuring out the problem with that one.
I will send this one straight to Brian

**Comment by hhuijser** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/93611

**Pull request closed without merging**
