### PR TITLE
LPS-115714

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@dantewang

**Comment by brianwulbern** [comment]
@austinchiang this one has a [flaky history on Testray](https://testray.liferay.com/home/-/testray/cases/865685798), with two failing like this in the past week.  Is your team aware of this kind of error affecting any other tests recently?  [PortalClientBuilderTest](https://github.com/liferay/liferay-portal/blob/master/portal-impl/test/unit/com/liferay/portal/tools/PortalClientBuilderTest.java) falls to Shuyang's team, but integrates different touch points across portal, so I'm not certain where the fix would need to come from.

**Comment by hhuijser** [comment]
ci:forward

**Comment by austinchiang** [comment]
We haven't seen that error recently. There is a ticket for it, but it's filed a long time ago... https://issues.liferay.com/browse/LRQA-54814

**Pull request closed without merging**
