### PR TITLE
LPS-123723 Change command names to match class name

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
Thanks @adolfopa !
Looks like the failing test is related and you can probably fix that much faster then me :)

**Comment by hhuijser** [comment]
See https://github.com/adolfopa/liferay-portal/pull/1450

**Pull request closed without merging**
