### PR TITLE
LPS-134335 Format *.path

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

Issues:
https://github.com/liferay/liferay-portal/commit/b6c2144c8aedd7fd24a17bbd41d68f3a62b3307e
https://github.com/liferay/liferay-portal/commit/4adaddb26cda50ba7c0e206492398ca69f9e7318
https://github.com/brianchandotcom/liferay-portal/commit/17b869417e8d9b370614af7e244cc99c763913e6
https://github.com/liferay/liferay-portal/commit/a8086f70225371790590223266c4d045c97d0d6a
https://github.com/brianchandotcom/liferay-portal/commit/46ecc46d83a6a23b39e928c1ec755b8cbb93408e
https://github.com/liferay/liferay-portal/commit/5d0b3e9852a34357ca2858a314016cf9bc988a64

checked with ci team:
https://github.com/ling-alan-huang/liferay-portal/pull/434#issuecomment-844242675
https://liferay.slack.com/archives/CL3TWSMHQ/p1623814174091800

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:acceptance-functional

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:acceptance-functional

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:acceptance-functional

**Comment by ling-alan-huang** [comment]
ci:test:acceptance-functional

**Comment by michaelhashimoto** [comment]
These errors looked okay to me.

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/103510

**Pull request closed without merging**
