### PR TITLE
LPS-105380 YMLWhitespaceCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Previous pull: https://github.com/hhuijser/liferay-portal/pull/5602

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Pull request closed without merging**
