### PR TITLE
LPS-105380_XMLDTDVersionCheck_20210217_master

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hey Hugo,

_Issue:_
https://github.com/brianchandotcom/liferay-portal-ee/pull/32123#issuecomment-721369758

_Backport pulls:_
7.3.x: https://github.com/hhuijser/liferay-portal-ee/pull/3203
7.2.x: https://github.com/hhuijser/liferay-portal-ee/pull/3204
7.1.x: https://github.com/hhuijser/liferay-portal-ee/pull/3205
7.0.x: https://github.com/hhuijser/liferay-portal-ee/pull/3206

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/98902

**Pull request closed without merging**
