### PR TITLE
LPS-77143

### PR DESCRIPTION
**Pull request by petershin**
I ran 3 tests for each:

For ```ant format-source-current-branch '-Dskip.npm=true' '-Dsource.formatter.show.debug.information=true'```:

- old: 57s, 53s, 55s
- new: 51s, 60s, 51s

For ```ant format-source-all '-Dskip.npm=true' '-Dsource.formatter.show.debug.information=true'```:

- old: 2min 38s, 2min 36s, 2min 44s
- new: 2min 47s, 2min 35s, 2min 58s

The times vary a bit and I'm guessing its because there's multiple threads running?  Please test on your laptop too.

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
@mtambara

**Comment by hhuijser** [comment]
Can you resolve conflicts and resend?

**Pull request closed without merging**
