### PR TITLE
LPS-106524 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
Project Template Tests passed here: https://github.com/gamerson/liferay-portal/pull/376#issuecomment-571735100 

SF Tests Passed here: https://github.com/gamerson/liferay-portal/pull/376#issuecomment-571698692

**Comment by jorgediaz-lr** [comment]
Hi @lawrence-lee @hhuijser 

It is also necessary to increase kernel version here:
- https://github.com/hhuijser/liferay-portal/blob/47d90fa9abc23d7da392e9975a3f9f6812d4bc09/modules/sdk/project-templates/project-templates-service-builder/src/main/resources/archetype-resources/__artifactId__-service/build.gradle#L54

from 2.6.0 to **2.42.0**:

` compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.42.0" `

More info see my PR for blade samples: https://github.com/lawrence-lee/liferay-blade-samples/pull/77/files

This change is only necessary in version 7.0.

**Comment by lawrence-lee** [comment]
@jorgediaz-lr, Thanks for this. I will update and resend

**Comment by lawrence-lee** [comment]
resent here: https://github.com/hhuijser/liferay-portal/pull/3948

**Pull request closed without merging**
