### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
ci:forward

**Comment by hhuijser** [comment]
@jpince, can you have someone check these failures? Thanks!

**Comment by hhuijser** [comment]
Seems unrelated as I am seeing the same failure here? https://github.com/hhuijser/liferay-portal/pull/5822

**Comment by jpince** [comment]
int test failures are a known intermittent issue https://issues.liferay.com/browse/LPS-136151

lpkg-base failure looks like a fluke, passed in the previous run.

@hhuijser you should be able to manually dforward to Brian.

**Comment by hhuijser** [comment]
thanks @jpince
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/106015

**Pull request closed without merging**
