### PR TITLE
LPS-136864 XMLServiceFinderNameCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Hi Hugo,

**Issues**:

1. Duplicate finder names:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/message-boards/message-boards-service/service.xml#L280-L285
and
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service.xml#L1417-L1422

2. All caps for specific names: I copied the logic from [VariableNameCheck.java](https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checkstyle/checks/VariableNameCheck.java#L190)
https://github.com/liferay/liferay-portal/blob/master/modules/apps/data-engine/data-engine-service/service.xml#L32-L34

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Rebase..

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/105810

**Pull request closed without merging**
