### PR TITLE
[TS] LPS-76604 apply to other places

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
ci:test

**Comment by daviddotzhang** [comment]
ci:retest

**Comment by hhuijser** [comment]
I'll wait for this one to be reviewed first: https://github.com/liferay/com-liferay-journal/pull/562

**Comment by daviddotzhang** [comment]
@hhuijser the first part is merged. you can continue to review it.

**Comment by hhuijser** [comment]
Sent to Brian: https://github.com/brianchandotcom/liferay-portal/pull/53914

**Pull request closed without merging**
