### PR TITLE
[TS] LPS-77431

### PR DESCRIPTION
**Pull request by yuhai**
Hi Hugo,

The issue only occured when add one record (the record include "Documents and Media" field) in the dialog, if the "Documents and Media" field repeatable=true, it will require class="lfr-form-content" element exist in this form. Please refer to the below logic.

https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L3176
->
https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/ddm_form.js#L3082-L3098

You may check the error in the browser. When the field repeatable=false, the issue won't occur.

**Fix Reference:**
The fix refers to LPS-67326, it add same fix in other modules(journal, kb, blogs,dl,bookmarks). I also check other module which can be added from Asset Publisher portlet in the dialog, please refer to https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/calendar/calendar-web/src/main/resources/META-INF/resources/edit_calendar_booking.jsp#L289

**The second commit:**
The module is different from other modules, it exists sidenav-container {position: relative;} (https://github.com/hhuijser/liferay-portal/blob/279fa83481423c0aaf53320b91b0df12e43c4e67/modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-web/src/main/resources/META-INF/resources/edit_record.jsp#L114) and lfr-form-content is using {position: absolute;}, the commit will solve the display issue to override "position: absolute"(Please refer to 005c0d83106dfe39656dd61cc6cf5659b838b9ee). 

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:retest

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by hhuijser** [comment]
Sent to Marcellus for review: https://github.com/marcellustavares/liferay-portal/pull/1894

**Pull request closed without merging**
