### PR TITLE
LPS-57500 Adding test cases.

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Hugo

I updated test cases for HtmlBBCodeTranslatorImpl, not solely for LPS-57500.

Meanwhile, I found one more bug : LPS-57372, which is rebased on the top of LPS-57500.

Here are those LPS to be tested:

testCode() : [LPS-54972](https://issues.liferay.com/browse/LPS-54972).
testEmotion() : [LPS-57372](https://issues.liferay.com/browse/LPS-57372).
testFontSize() : [LPS-56439](https://issues.liferay.com/browse/LPS-56439).
testIncompleteTag() : [LPS-57500](https://issues.liferay.com/browse/LPS-57500).
testInvalidTag() and testInvalidTagAndValidTag() : [LPS-57500](https://issues.liferay.com/browse/LPS-57500), [LPS-56926](https://issues.liferay.com/browse/LPS-56926), [LPS-56642](https://issues.liferay.com/browse/LPS-56642), [LPS-56480](https://issues.liferay.com/browse/LPS-56480).
testOrderedList(): [LPS-56739](https://issues.liferay.com/browse/LPS-56739), [LPS-56287](https://issues.liferay.com/browse/LPS-56739).
testStar(): [LPS-57041](https://issues.liferay.com/browse/LPS-57041).
testUnorderList(): [LPS-56411](https://issues.liferay.com/browse/LPS-56411).
testUrl(): [LPS-55011](https://issues.liferay.com/browse/LPS-55011).

Please help review.

Thanks
John.

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @zxdgoal 

Looks very nice!
Can you add the different testcases with the LPS number that those are related to?
It's okay that it ends up in a lot of commits. 
Just easier if we need to fix or modify later on if we can trace back what ticket it's related to.

**Comment by zxdgoal** [comment]
It's done, Could you re-fetch please?

**Comment by zxdgoal** [comment]
Will resend

**Comment by zxdgoal** [comment]
Here it is : LPS 57500 Update basic test cases

**Pull request closed without merging**
